angular/angular.io

- public/docs/js/latest/quickstart.jade
just some syntax fixes form the examples.
Angular2 looks good, the same should go the the syntax :bowtie:
> fixing example syntax

- public/_includes/_footer.jade
- public/docs/dart/latest/resources.jade
- public/docs/js/latest/resources.jade
- public/resources/css/base/_type.scss
- public/resources/css/module/_alert.scss
Also update chat to point to gitter
> Docs(resources): Add ng-conf video and forms blog post

- public/docs/js/latest/guide/displaying-data.jade
```
change from "template: '{{ myName }} <ul> <li *for="#name of names"<{{ name }}>/li< >/ul<',"
to "template: '{{ myName }} <ul> <li *for="#name of names">{{ name }}</li> </ul>',"
```
> Fixed bugs of lt or gt

- public/docs/dart/latest/quickstart.jade
- public/index.jade
Rename concepts due to https://github.com/angular/angular/commit/bf7933714a884e10124ce43aa27d63791fc37e6a
> fix(Templates) rename Template to View

- public/docs/js/latest/guide/setup.jade
Fixes issue https://github.com/angular/angular.io/issues/94 by adding the `my-app` directive to the html.
> Added my-app directive to the ES5 'Getting started' guide

- public/docs/js/latest/guide/displaying-data.jade
In the code example below it, we use the `names` variable, so, `todos` here will be confused.
> change the variable `todos` to `names`

- public/contribute.jade
> docs(contribute): Update the Contribute to Angular to add AngularDart

- public/docs/js/latest/api/annotations/_data.json
- public/docs/js/latest/api/change_detection/ChangeDetection-class.jade
- public/docs/js/latest/api/change_detection/DynamicChangeDetection-class.jade
- public/docs/js/latest/api/change_detection/JitChangeDetection-class.jade
- public/docs/js/latest/api/core/ViewContainerRef-class.jade
- public/docs/js/latest/api/di_annotations/DependencyAnnotation-class.jade
- public/docs/js/latest/api/di_annotations/Inject-class.jade
- public/docs/js/latest/api/di_annotations/InjectLazy-class.jade
- public/docs/js/latest/api/di_annotations/InjectPromise-class.jade
- public/docs/js/latest/api/di_annotations/Injectable-class.jade
- public/docs/js/latest/api/di_annotations/Optional-class.jade
- public/docs/js/latest/api/pipes/AsyncPipeFactory-class.jade
- public/docs/js/latest/api/pipes/CollectionChangeRecord-class.jade
- public/docs/js/latest/api/pipes/IterableChanges-class.jade
- public/docs/js/latest/api/pipes/KVChangeRecord-class.jade
- public/docs/js/latest/api/pipes/KeyValueChanges-class.jade
- public/docs/js/latest/api/pipes/KeyValueChangesFactory-class.jade
- public/docs/js/latest/api/pipes/NullPipe-class.jade
- public/docs/js/latest/api/pipes/NullPipeFactory-class.jade
- public/docs/js/latest/api/pipes/Pipe-class.jade
- public/docs/js/latest/api/pipes/WrappedValue-class.jade
- public/docs/js/latest/api/pipes/_data.json
- public/docs/js/latest/api/router/Router-class.jade
- public/docs/js/latest/api/router/_data.json
- public/docs/js/latest/api/router/routerInjectables-var.jade
- public/docs/js/latest/api/view/Compiler-class.jade
- public/docs/js/latest/api/view/ComponentRef-class.jade
- public/docs/js/latest/api/view/DynamicComponentLoader-class.jade
generated from changes in https://github.com/angular/angular/pull/1886
> docs(api): update API docs to head

- public/docs/js/latest/guide/displaying-data.jade
- public/docs/js/latest/guide/setup.jade
I'll be making some more fixes, based on my internal doc shared with @naomiblack and @alexwolfe
> First round of guide content fixes

- public/_includes/_main-nav.jade
- public/docs/js/latest/quickstart.jade
- public/download/_data.json
- public/download/index.jade
- public/resources/css/layout/_layout.scss
- public/resources/css/module/_card.scss
Creating a pull request in case this is a real issue. 
Before: 
After:
> #128: 5 Min Quickstart small issue fix & #119: Download page formatting

- public/_layout.jade
This is for a magic trick I'll be doing at a conference this coming week.
Shhh, don't tell anybody.
I'll do another PR to revert this.
> chore(layout): update doctype

- public/resources/js/directives/bio.js
This commit fixes #132.
See [this](https://github.com/angular/material/issues/1531) for more detailed information.
> fix(bio): fix dialog bug

- public/docs/js/latest/guide/user-input.jade
fixes #159 
supersedes #161 (This PR as the same content in a single commit)
> docs: misc fixes in user input

- gulpfile.js
- public/doc-shredder/doc-shredder.js
- public/doc-shredder/fileShredder.js
- public/docs/_examples/styleguide/foo.dart
- public/docs/_examples/styleguide/foo.yaml
Added support for shredding dart and yaml files.
> Dev tooling 8

- public/docs/_examples/gettingstarted/ts/package.json
- public/docs/_examples/gettingstarted/ts/src/app.ts
- public/docs/_examples/gettingstarted/ts/src/app/app.ts
- public/docs/_examples/gettingstarted/ts/src/index.1.html
- public/docs/ts/latest/guide/gettingStarted.jade
- public/docs/ts/latest/guide/toh-pt1.jade
- public/docs/ts/latest/guide/user-input.jade
Update GettingStarted for alpha-40 with @View merged into @Component
Started to do the same for ToH-Pt1.  Realized there were many other gaps in conversion, presentation, and flow. Filled them.
> Devguide getting started 4

- public/docs/_examples/gettingstarted/ts/package.json
- public/docs/_examples/gettingstarted/ts/src/app.ts
- public/docs/_examples/gettingstarted/ts/src/app/app.ts
- public/docs/_examples/gettingstarted/ts/src/index.1.html
- public/docs/_examples/gettingstarted/ts/src/tsconfig.json
- public/docs/ts/latest/guide/gettingStarted.jade
- public/docs/ts/latest/guide/toh-pt1.jade
- public/docs/ts/latest/guide/user-input.jade
(docs) Getting Started & ToH-pt1: update for alpha-42, no tsd, `noImplicitAny:false`
> Devguide getting started 5

- public/resources/css/base/_type.scss
> hides api sections when there are no items to display

- public/api-builder/angular.io-package/index.js
- public/api-builder/angular.io-package/templates/class.template.html
- public/api-builder/angular.io-package/templates/function.template.html
- public/api-builder/angular.io-package/templates/var.template.html
- public/api-builder/docs-package/index.js
- public/resources/css/main.scss
- public/resources/css/module/_heading-code.scss
A bunch of fixes to improve the API docs layout
Partially fixes https://github.com/angular/angular/issues/4258
> Improvements to the API templates

- README.md
> docs(readme): clarify dev setup

- public/docs/_includes/styleguide/_code-examples.jade
A few typos I came across while ready the docs styleguide.
> docs(styleguide): fix minor typos

- public/docs/ts/latest/guide/template-syntax.jade
see https://github.com/angular/angular/pull/5146
/cc @wardbell
> doc(template syntax): Short-circuiting is now supported

- public/docs/js/latest/guide/user-input.jade
* `*ngfor` is not right, it should be `*ng-for`
* `addTodo()` should push the value of the DOM element
> Fixed ng-for typo && fix param in addTodo()

- public/docs/_examples/quickstart/dart/ex1/pubspec.yaml
- public/docs/_examples/quickstart/dart/ex2/pubspec.yaml
- public/docs/dart/latest/guide/displaying-data.jade
- public/docs/dart/latest/guide/setup.jade
- public/docs/dart/latest/guide/user-input.jade
- public/docs/dart/latest/quickstart.jade
@kwalrath. Updated dart examples to alpha.45
> Dart update to alpha.45

- public/_includes/_main-nav.jade
- public/_includes/_scripts-include.jade
- public/resources/js/directives/scroll-y-offset-element.js
- public/resources/js/site.js
> fix(app): ensure headings are visible when navigating to in-page anchors

- public/index.jade
> Removed third demo from homepage

- public/resources/css/module/_main-nav.scss
> fixes positioning on main nav buttons

- public/docs/_examples/homepage-todo/ts/app/todo_list.ts
> docs(bugfix):fix class name on todo list sample

- public/docs/_includes/_side-nav.jade
- public/docs/dart/latest/resources.jade
- public/docs/js/latest/resources.jade
- public/docs/ts/latest/cookbook/index.jade
- public/docs/ts/latest/resources.jade
also added some blog posts to resources
> docs: simplify left nav selection/scroll

- public/resources/js/directives/copy.js
> chore: fix copy-button / aside overlap #744

- README.md
Amazing work on the README, will help others when contributing in here.
The link was broken, but was just a typo :)
> chore(README): fix url

- public/docs/_examples/package.json
- public/docs/_examples/quickstart/ts/package.1.json
Overlooked updates while moving to beta.9
> docs(quickstart): update package.1.json versions

- public/docs/_examples/homepage-hello-world/ts/index.1.html
- public/docs/_examples/homepage-tabs/ts/index.1.html
- public/docs/_examples/homepage-todo/ts/index.1.html
- public/docs/_examples/package.json
- public/docs/_examples/quickstart/js/package.1.json
- public/docs/_examples/quickstart/ts/package.1.json
- public/docs/_examples/router/ts/index.1.html
- public/docs/_examples/styleguide/package.1.json
- public/docs/_examples/upgrade/ts/ng2_components/package.1.json
- public/docs/_examples/upgrade/ts/ng2_final/package.1.json
- public/docs/_examples/upgrade/ts/ng2_initial/package.1.json
- tools/plunker-builder/indexHtmlTranslator.js
See issue [#7618](https://github.com/angular/angular/issues/7618)
> chore: update es6-shim to v.0.35.0 per A2 issue #7618

- public/docs/_examples/cb-component-communication/ts/app/hero.ts
- public/docs/_examples/toh-1/ts/app/app.component.ts
- public/docs/_examples/toh-2/ts/app/app.component.ts
- public/docs/_examples/toh-3/ts/app/app.component.ts
- public/docs/_examples/toh-3/ts/app/hero-detail.component.ts
- public/docs/_examples/toh-3/ts/app/hero.ts
- public/docs/_examples/toh-4/ts/app/app.component.ts
- public/docs/_examples/toh-4/ts/app/hero-detail.component.ts
- public/docs/_examples/toh-4/ts/app/hero.ts
- public/docs/_examples/toh-5/ts/app/hero-detail.component.ts
- public/docs/_examples/toh-5/ts/app/hero.ts
- public/docs/_examples/toh-5/ts/app/heroes.component.css
- public/docs/_examples/tutorial/ts/app/app.component.ts
- public/docs/_examples/tutorial/ts/app/dashboard.component.ts
- public/docs/_examples/tutorial/ts/app/hero-detail.component.ts
- public/docs/_examples/tutorial/ts/app/hero.ts
- public/docs/_examples/tutorial/ts/app/heroes.component.css
- public/docs/_examples/tutorial/ts/app/heroes.component.ts
- public/docs/ts/latest/tutorial/toh-pt1.jade
- public/docs/ts/latest/tutorial/toh-pt2.jade
- public/docs/ts/latest/tutorial/toh-pt3.jade
- public/docs/ts/latest/tutorial/toh-pt4.jade
The PR itself is complete, but there is a weird issue with the generated plunker:
http://plnkr.co/edit/fbNckRhMEitZ72XWFsaW?p=preview
That doesn't happen if we do `npm start` at the `toh-3` folder or if I replicate this on a webpack starter I have. Only plunker.
I have no idea why so I leave this here so we can debug it and not forget about this.
> (WIP) chore(toh): change inputs array for input decorator

- gulpfile.js
- public/docs/_examples/package.json
This PR fixes a race condition when starting e2e test suites. Previously, the test suite could start before `tsc` compilation was finished, causing tests to fail.
> fix(e2e): fix race condition

- public/docs/_examples/homepage-hello-world/ts/index.1.html
- public/docs/_examples/homepage-tabs/ts/index.1.html
- public/docs/_examples/homepage-todo/ts/index.1.html
- public/docs/_examples/package.json
- public/docs/_examples/quickstart/js/package.1.json
- public/docs/_examples/quickstart/ts/package.1.json
- public/docs/dart/latest/_data.json
- public/docs/js/latest/_data.json
- public/docs/ts/latest/_data.json
- tools/plunker-builder/indexHtmlTranslator.js
> chore: update to beta.14

- public/docs/_examples/homepage-hello-world/ts/index.1.html
- public/docs/_examples/homepage-tabs/ts/index.1.html
- public/docs/_examples/homepage-todo/ts/index.1.html
- public/docs/_examples/package.json
- public/docs/_examples/quickstart/js/package.1.json
- public/docs/_examples/quickstart/ts/package.1.json
- public/docs/_examples/quickstart/ts/typings.1.json
- public/docs/_examples/router/ts/index.html
- public/docs/_examples/typings.json
- public/docs/dart/latest/_data.json
- public/docs/js/latest/_data.json
- public/docs/ts/latest/_data.json
- tools/plunker-builder/indexHtmlTranslator.js
also restore accidentally deleted router sample files
> docs(ts): update to beta.15

- public/docs/_examples/dependency-injection/dart/.docsync.json
> samples(dart): add a `docsync` file to the dependency-injection example.

- public/docs/_examples/forms/dart/.docsync.json
> samples(dart): add a `docsync` file to the forms example.

- public/docs/_includes/_side-nav.jade
- public/resources/css/module/_side-nav.scss
- public/resources/images/icons/ic_keyboard_arrow_down_black_24px.svg
* New and improved sidenav with collapsed sections
* `5 Min Quickstart` has its own section, called `QUICKSTART`
Live Preview: https://sidenav-restyle.firebaseapp.com/docs/ts/latest/quickstart.html
CLOSES:
https://github.com/angular/angular.io/issues/1117
@naomiblack @petebacondarwin
> docs(sidenav): Restylize sidenav

- public/docs/ts/latest/guide/style-guide.jade
**DO NOT MERGE** Work in progress
Picks up from v.1 #1040
> [WIP] docs(style-guide): add style-guide - v.2

- public/docs/_examples/karma.conf.js
- public/docs/_examples/testing/ts/app/app.component.spec.ts
- public/docs/_examples/testing/ts/app/bad-tests.spec.ts
- public/docs/_examples/testing/ts/app/bag.spec.ts
- public/docs/_examples/testing/ts/app/bag.ts
- public/docs/_examples/testing/ts/app/dashboard.component.spec.ts
- public/docs/_examples/testing/ts/app/http-hero.service.spec.ts
- public/docs/_examples/wallaby.js
closes #1189
Don't like how I extract the directive in `app.component.spec.ts` but it works.
> [WIP] docs(testing) adapt sample code to beta.16 breaking changes

- public/docs/_examples/style-guide/ts/03-05/app/+heroes/shared/hero.service.avoid.ts
- public/docs/_examples/style-guide/ts/03-05/app/+heroes/shared/hero.service.ts
- public/docs/_examples/style-guide/ts/03-06/app/+heroes/shared/hero.service.ts
- public/docs/_examples/style-guide/ts/04-10/app/+heroes/heroes.component.ts
- public/docs/_examples/style-guide/ts/04-10/app/app.component.ts
- public/docs/_examples/style-guide/ts/04-14/app/heroes/heroes.component.ts
- public/docs/_examples/style-guide/ts/05-14/app/shared/toast/toast.component.avoid.ts
- public/docs/_examples/style-guide/ts/05-14/app/shared/toast/toast.component.ts
- public/docs/_examples/style-guide/ts/05-17/app/heroes/hero-list/hero-list.component.avoid.ts
- public/docs/_examples/style-guide/ts/05-17/app/heroes/hero-list/hero-list.component.ts
- public/docs/_examples/style-guide/ts/06-03/app/shared/validate.directive.avoid.ts
- public/docs/_examples/style-guide/ts/06-03/app/shared/validate.directive.ts
- public/docs/ts/latest/guide/style-guide.jade
- public/resources/css/module/_style-guide.scss
- tslint.json
continuation of PR #1204
googlebot:  John approves of this PR for his commits
> Docs style guide 6

- public/docs/_examples/router-deprecated/e2e-spec.js
- public/docs/_examples/router-deprecated/ts/app/app.component.1.ts
- public/docs/_examples/router-deprecated/ts/app/app.component.2.ts
- public/docs/_examples/router-deprecated/ts/app/app.component.3.ts
- public/docs/_examples/router-deprecated/ts/app/app.component.ts
- public/docs/_examples/router-deprecated/ts/index.1.html
- public/docs/_examples/router-deprecated/ts/index.2.html
- public/docs/_examples/router-deprecated/ts/index.3.html
- public/docs/_examples/router-deprecated/ts/index.html
- public/docs/_examples/router/e2e-spec.js
- public/docs/ts/latest/guide/router.jade
> [WIP] docs(router): document new router and samples - phase 2

- public/docs/_examples/quickstart/ts/systemjs.config.1.js
- public/docs/ts/latest/quickstart.jade
Please review and reword as needed.
> docs(quickstart): update to new world

- public/_includes/_util-fns.jade
- public/docs/_examples/component-styles/dart/lib/hero.dart
- public/docs/_examples/component-styles/dart/lib/hero_app_component.dart
- public/docs/_examples/component-styles/dart/lib/hero_app_main_component.dart
- public/docs/_examples/component-styles/dart/lib/hero_controls_component.dart
- public/docs/_examples/component-styles/dart/lib/hero_details_box.css
- public/docs/_examples/component-styles/dart/lib/hero_details_component.css
- public/docs/_examples/component-styles/dart/lib/hero_details_component.dart
- public/docs/_examples/component-styles/dart/lib/hero_team_component.css
- public/docs/_examples/component-styles/dart/lib/hero_team_component.dart
- public/docs/_examples/component-styles/dart/lib/quest_summary_component.css
- public/docs/_examples/component-styles/dart/lib/quest_summary_component.dart
- public/docs/_examples/component-styles/dart/lib/quest_summary_component.html
- public/docs/_examples/component-styles/dart/pubspec.yaml
- public/docs/_examples/component-styles/dart/web/index.html
- public/docs/_examples/component-styles/dart/web/main.dart
- public/docs/_examples/component-styles/ts/app/hero-app.component.ts
- public/docs/_examples/component-styles/ts/app/hero-controls.component.ts
- public/docs/_examples/component-styles/ts/app/hero-details.component.ts
- public/docs/_examples/component-styles/ts/app/quest-summary.component.html
- public/docs/_examples/component-styles/ts/app/quest-summary.component.ts
- public/docs/dart/latest/_util-fns.jade
- public/docs/dart/latest/guide/component-styles.jade
- public/docs/ts/latest/_util-fns.jade
- public/docs/ts/latest/guide/component-styles.jade
Starting point for Dart code was taken from #1171 (thanks @luisvt!).
Could not run e2e test on this TS example because of #1319.
> [review-pending] docs(dev guide): component-styles - new dart prose and code; ts updates

- public/docs/ts/latest/quickstart.jade
> docs(quickstart): fix broken region

- public/docs/_examples/.gitignore
- public/docs/_examples/quickstart/ts/typings.d.1.ts
- public/docs/_examples/typings/typings.d.ts
- public/docs/ts/latest/guide/component-styles.jade
- public/docs/ts/latest/guide/typescript-configuration.jade
- public/docs/ts/latest/quickstart.jade
> docs(typings): add typings.d.ts for module.id and describe it

- public/docs/js/latest/quickstart.jade
- public/docs/ts/latest/quickstart.jade
> docs(quickstart): say 'My First Angular 2 App'

- public/docs/_examples/package.json
- public/docs/_examples/quickstart/js/package.1.json
- public/docs/_examples/quickstart/ts/package.1.json
- public/docs/_examples/toh-6/ts/app/heroes.component.ts
The new in-mem-web-api uses commonjs and thus is webpack compatable
> docs: update api-in-mem-web-api to v.0.0.8

- public/docs/_examples/homepage-hello-world/ts/index.1.html
- public/docs/_examples/homepage-tabs/ts/index.1.html
- public/docs/_examples/homepage-todo/ts/index.1.html
- public/docs/_examples/karma.conf.js
- public/docs/_examples/package.json
- public/docs/_examples/quickstart/ts/package.1.json
- public/docs/_examples/styleguide/package.1.json
- public/docs/_examples/upgrade-adapter/ts/index-1-2-hybrid-bootstrap.html
- public/docs/_examples/upgrade-adapter/ts/index-1-2-hybrid-shared-adapter-bootstrap.html
- public/docs/_examples/upgrade-adapter/ts/index-1-to-2-projection.html
- public/docs/_examples/upgrade-adapter/ts/index-1-to-2-providers.html
- public/docs/_examples/upgrade-adapter/ts/index-2-to-1-providers.html
- public/docs/_examples/upgrade-adapter/ts/index-2-to-1-transclusion.html
- public/docs/_examples/upgrade-adapter/ts/index-downgrade-io.html
- public/docs/_examples/upgrade-adapter/ts/index-downgrade-static.html
- public/docs/_examples/upgrade-adapter/ts/index-upgrade-io.html
- public/docs/_examples/upgrade-adapter/ts/index-upgrade-static.html
- public/docs/_examples/upgrade-phonecat/ts/ng2_components/package.1.json
- public/docs/_examples/upgrade-phonecat/ts/ng2_components/test/karma.conf.1.js
- public/docs/_examples/upgrade-phonecat/ts/ng2_final/package.1.json
- public/docs/_examples/upgrade-phonecat/ts/ng2_final/test/karma.conf.1.js
- public/docs/_examples/upgrade-phonecat/ts/ng2_initial/package.1.json
- public/docs/_examples/upgrade-phonecat/ts/ng2_initial/test/karma.conf.1.js
- public/docs/_examples/wallaby.js
- public/docs/ts/latest/guide/typescript-configuration.jade
- public/docs/ts/latest/quickstart.jade
- tools/plunker-builder/indexHtmlTranslator.js
> chore: more conversion of es6-shim to core-js

- public/docs/_examples/karma-test-shim.js
- public/docs/_examples/karma.conf.js
- public/docs/_examples/testing/ts/app/app.component.spec.ts
- public/docs/_examples/testing/ts/app/app.component.ts
- public/docs/_examples/testing/ts/app/bad-tests.spec.ts
- public/docs/_examples/testing/ts/app/bag.spec.ts
- public/docs/_examples/testing/ts/app/dashboard.component.spec.ts
- public/docs/_examples/testing/ts/app/dashboard.component.ts
- public/docs/_examples/testing/ts/app/hero-detail.component.ts
- public/docs/_examples/testing/ts/app/heroes.component.ts
- public/docs/_examples/testing/ts/app/http-hero.service.spec.ts
- public/docs/_examples/testing/ts/app/mock-router.ts
- public/docs/_examples/wallaby.js
Got them working again ... except for two Observable tests failing. Will dig into those next.
> docs(testing): update samples & test config to RC1

- gulpfile.js
- public/docs/_examples/cb-component-communication/ts/app/countdown-timer.component.ts
- public/docs/_examples/cb-component-relative-paths/e2e-spec.js
- public/docs/_examples/cb-component-relative-paths/ts/app/app.component.ts
- public/docs/_examples/cb-component-relative-paths/ts/app/main.ts
- public/docs/_examples/cb-component-relative-paths/ts/app/some.component.css
- public/docs/_examples/cb-component-relative-paths/ts/app/some.component.html
- public/docs/_examples/cb-component-relative-paths/ts/app/some.component.ts
- public/docs/_examples/cb-component-relative-paths/ts/index.html
- public/docs/_examples/cb-component-relative-paths/ts/plnkr.json
- public/docs/_examples/cb-dependency-injection/ts/app/main.ts
- public/docs/_examples/karma-test-shim.js
- public/docs/_examples/server-communication/ts/app/main.ts
- public/docs/_examples/systemjs.config.js
- public/docs/_examples/systemjs.config.plunker.js
- public/docs/_examples/toh-6/ts/app/main.ts
- public/docs/_examples/wallaby.js
- public/docs/dart/latest/cookbook/_data.json
- public/docs/dart/latest/cookbook/component-relative-paths.jade
- public/docs/js/latest/cookbook/_data.json
- public/docs/js/latest/cookbook/component-relative-paths.jade
- public/docs/ts/latest/cookbook/_data.json
- public/docs/ts/latest/cookbook/component-relative-paths.jade
- public/docs/ts/latest/guide/component-styles.jade
- public/docs/ts/latest/tutorial/toh-pt5.jade
> docs(component-relative-paths): new cookbook

- public/docs/_examples/style-guide/e2e-spec.js
- public/docs/_examples/style-guide/ts/app/main.ts
Tests!
I had to change the router to use Hash based routing (so protractor won't complain) but that is not a biggie.
Thanks to the new improved e2e task and this tests, we can be sure that all the style compiles and what they show on the screen is correct.
> docs(style-guide): add e2e tests

- public/docs/_examples/package.json
- public/docs/_examples/quickstart/js/package.1.json
- public/docs/_examples/quickstart/ts/package.1.json
Has RegExp query option needed for ToH 7: Http+Observables
> docs(chore): update samples to angular-in-mem-web-api v.0.0.11

- public/_includes/_util-fns.jade
- public/docs/dart/latest/_util-fns.jade
- public/docs/dart/latest/quickstart.jade
- public/docs/ts/latest/guide/component-styles.jade
- public/docs/ts/latest/quickstart.jade
This only impacts language dependent variable and path definitions:
- Removed deprecated variable.
- Hoisted useful variable definitions from quickstart into _util-fns.
- Minor fix in regexp of path translation function
> chore(util-fns): minor cleanup and refactoring

- public/docs/_examples/architecture/dart/.docsync.json
- public/docs/_examples/attribute-directives/dart/.docsync.json
- public/docs/_examples/dependency-injection/dart/.docsync.json
- public/docs/_examples/displaying-data/dart/.docsync.json
- public/docs/_examples/forms/dart/.docsync.json
- public/docs/_examples/hierarchical-dependency-injection/dart/.docsync.json
- public/docs/_examples/pipes/dart/.docsync.json
- public/docs/_examples/quickstart/dart/.docsync.json
- public/docs/_examples/server-communication/dart/.docsync.json
- public/docs/_examples/template-syntax/dart/.docsync.json
- public/docs/_examples/toh-1/dart/.docsync.json
- public/docs/_examples/toh-2/dart/.docsync.json
- public/docs/_examples/toh-3/dart/.docsync.json
- public/docs/_examples/toh-4/dart/.docsync.json
- public/docs/_examples/toh-5/dart/.docsync.json
Changes corresponding to updates made to dart-doc-syncer via https://github.com/angular/dart-doc-syncer/pull/13.
> chore(dart): add/cleanup example hosting config files

- public/docs/_examples/cb-dynamic-form-deprecated/e2e-spec.ts
- public/docs/_examples/cb-dynamic-form-deprecated/ts/app/app.component.ts
- public/docs/_examples/cb-dynamic-form-deprecated/ts/app/dynamic-form-question.component.html
- public/docs/_examples/cb-dynamic-form-deprecated/ts/app/dynamic-form-question.component.ts
- public/docs/_examples/cb-dynamic-form-deprecated/ts/app/dynamic-form.component.html
- public/docs/_examples/cb-dynamic-form-deprecated/ts/app/dynamic-form.component.ts
- public/docs/_examples/cb-dynamic-form-deprecated/ts/app/main.ts
- public/docs/_examples/cb-dynamic-form-deprecated/ts/app/question-base.ts
- public/docs/_examples/cb-dynamic-form-deprecated/ts/app/question-control.service.ts
- public/docs/_examples/cb-dynamic-form-deprecated/ts/app/question-dropdown.ts
- public/docs/_examples/cb-dynamic-form-deprecated/ts/app/question-textbox.ts
- public/docs/_examples/cb-dynamic-form-deprecated/ts/app/question.service.ts
- public/docs/_examples/cb-dynamic-form-deprecated/ts/index.html
- public/docs/_examples/cb-dynamic-form-deprecated/ts/plnkr.json
- public/docs/_examples/cb-dynamic-form-deprecated/ts/sample.css
- public/docs/_examples/cb-dynamic-form/ts/app/main.ts
- public/docs/_examples/cb-dynamic-form/ts/app/question-control.service.ts
- public/docs/_examples/package.json
- public/docs/_examples/systemjs.config.js
- public/docs/_examples/systemjs.config.plunker.js
- public/docs/ts/latest/cookbook/_data.json
- public/docs/ts/latest/cookbook/dynamic-form-deprecated.jade
I have added a version of the Dynamic Form Cookbook using the new forms API.
> docs(dynamic-cookbook): upgrade to use new forms api

- public/docs/_examples/pipes/dart/lib/app_component.dart
- public/docs/_examples/pipes/dart/lib/hero_birthday1_component.dart
- public/docs/_examples/pipes/dart/lib/hero_birthday2_component.dart
- public/docs/_examples/pipes/dart/lib/power_boost_calculator_component.dart
- public/docs/_examples/pipes/dart/lib/power_booster_component.dart
- public/docs/_examples/pipes/dart/web/main.dart
Dart-side updates following #1654:
- Updates to follow style guide
- Suites passed:
- public/docs/_examples/pipes/dart
- Suites failed (known issue - #1761):
- public/docs/_examples/pipes/ts
> docs(guide/pipes): follow-up to #1654

- public/_data.json
- public/resources/_data.json
- public/resources/css/module/_resources.scss
- public/resources/index.ejs
- public/resources/js/controllers/resources-controller.js
* Make a new resources page
* https://new-schema.firebaseapp.com/resources/
@StephenFluin
> Restyle resources page with new schema

- public/docs/_examples/cb-dependency-injection/ts/app/hero.service.ts
- public/docs/_examples/router-deprecated/ts/app/crisis-center/crisis.service.ts
- public/docs/_examples/router-deprecated/ts/app/heroes/hero.service.ts
- public/docs/_examples/router/ts/app/crisis-center/crisis.service.ts
- public/docs/_examples/router/ts/app/heroes/hero.service.ts
- public/docs/_examples/testing/ts/app/hero.service.ts
- public/docs/_examples/toh-5/ts/app/hero.service.ts
- public/docs/_examples/toh-6/ts/app/hero.service.ts
> docs: replace xxx.filter(...)[0] with xxx.find(...)

- tools/api-builder/angular.io-package/templates/class.template.html
All the kudos to @chalin for finding this problem.
> chore: add support for multiline annotations in the API

- public/docs/_examples/router/ts/app/app.routes.1.ts
- public/docs/_examples/router/ts/app/app.routes.2.ts
- public/docs/_examples/router/ts/app/app.routes.3.ts
- public/docs/_examples/router/ts/app/app.routes.4.ts
- public/docs/_examples/router/ts/app/app.routes.5.ts
- public/docs/_examples/router/ts/app/app.routes.ts
- public/docs/_examples/router/ts/app/crisis-center/crisis-center.routes.1.ts
- public/docs/_examples/router/ts/app/crisis-center/crisis-center.routes.2.ts
- public/docs/_examples/router/ts/app/crisis-center/crisis-center.routes.3.ts
- public/docs/_examples/router/ts/app/crisis-center/crisis-center.routes.4.ts
- public/docs/_examples/router/ts/app/crisis-center/crisis-center.routes.ts
- public/docs/_examples/router/ts/app/heroes/heroes.routes.ts
- public/docs/_examples/router/ts/app/login.routes.ts
- public/docs/_examples/router/ts/app/main.1.ts
- public/docs/_examples/router/ts/app/main.2.ts
- public/docs/_examples/router/ts/app/main.3.ts
- public/docs/_examples/router/ts/app/main.ts
many of them to make `const` vars conform to style guide.
> docs(router): more little fixes from #1808

- gulpfile.js
> chore: install upgrade with install-example-angular

- public/docs/_examples/toh-6/ts/app/hero-search.component.html
- public/docs/_examples/toh-6/ts/app/hero-search.component.ts
- public/docs/ts/latest/tutorial/toh-pt6.jade
> docs(toh-pt6): bind to a component method rather than a RxJS Subject

- gulpfile.js
- public/docs/dart/latest/cheatsheet.jade
- tools/dart-api-builder/index.js
- tools/dart-api-builder/services/packageInfo.js
> docs(cheatsheet/dart): generate from dart sources

- public/docs/dart/latest/tutorial/toh-pt6.jade
- public/docs/ts/latest/tutorial/toh-pt6.jade
Exclude the new Observables section entirely for now.
> docs(toh-6/dart): quickfix to eliminate "BAD FILENAME" errors

- public/docs/ts/latest/tutorial/toh-pt6.jade
@wardbell I missed a section in the text where the re-throw was mentioned
> docs(toh-6): remove details about throw

- public/docs/_examples/dependency-injection/dart/lib/heroes/heroes_component_1.dart
Fixes #1956 for Dart.
Dart counterpart to #2001.
> docs(DI/dart): fix incorrect snippet import

- public/docs/ts/latest/guide/architecture.jade
Follow-up to https://github.com/angular/angular.io/pull/1972#issuecomment-235738082. Original issue is #1970.
cc @kwalrath @wardbell @Foxandxss
> docs(architecture): give example of libraries in both TS and Dart

- public/docs/dart/latest/guide/_data.json
- public/docs/dart/latest/guide/forms-deprecated.html
- public/docs/dart/latest/guide/forms-deprecated.jade
- public/docs/dart/latest/guide/router-deprecated.jade
- public/docs/dart/latest/guide/router.jade
> [Dart] Ensure {forms|router}{,-deprecated} chapters have proper content

- public/docs/dart/latest/guide/architecture.jade
- public/docs/dart/latest/guide/attribute-directives.jade
- public/docs/dart/latest/guide/component-styles.jade
- public/docs/dart/latest/guide/dependency-injection.jade
- public/docs/dart/latest/guide/displaying-data.jade
- public/docs/dart/latest/guide/hierarchical-dependency-injection.jade
- public/docs/dart/latest/guide/lifecycle-hooks.jade
- public/docs/dart/latest/guide/pipes.jade
- public/docs/dart/latest/guide/server-communication.jade
- public/docs/dart/latest/guide/structural-directives.jade
- public/docs/dart/latest/guide/template-syntax.jade
- public/docs/dart/latest/quickstart.jade
- public/docs/dart/latest/tutorial/toh-pt6.jade
- public/docs/ts/_cache/_quickstart_repo.jade
- public/docs/ts/_cache/_util-fns.jade
- public/docs/ts/_cache/guide/architecture.jade
- public/docs/ts/_cache/guide/attribute-directives.jade
- public/docs/ts/_cache/guide/component-styles.jade
- public/docs/ts/_cache/guide/dependency-injection.jade
- public/docs/ts/_cache/guide/displaying-data.jade
- public/docs/ts/_cache/guide/hierarchical-dependency-injection.jade
- public/docs/ts/_cache/guide/lifecycle-hooks.jade
- public/docs/ts/_cache/guide/pipes.jade
- public/docs/ts/_cache/guide/security.jade
- public/docs/ts/_cache/guide/server-communication.jade
- public/docs/ts/_cache/guide/structural-directives.jade
- public/docs/ts/_cache/guide/template-syntax.jade
- public/docs/ts/_cache/quickstart.jade
- public/docs/ts/_cache/tutorial/toh-pt6.jade
- scripts/refresh-cache.sh
> docs(dart): decouple Dart from TS .jade files temporarily

- public/docs/dart/latest/quickstart.jade
- public/docs/ts/_cache/quickstart.jade
Cf. #2088 and #2077.
cc @kwalrath
> chore(quickstart/dart): refresh ts _cache

- public/docs/ts/_cache/glossary.jade
- scripts/cache.sh
> chore(ts/_cache): add glossary

- public/docs/_examples/toh-1/e2e-spec.ts
- public/docs/_examples/toh-2/e2e-spec.ts
- public/docs/_examples/toh-3/e2e-spec.ts
- public/docs/_examples/toh-4/e2e-spec.ts
> tests(toh-[1-4]): e2e - support space in hero name

- public/docs/ts/latest/tutorial/toh-pt6.jade
Copyedit in file tree.
cc @wardbell @Foxandxss
> docs(toh-6): systemjs.config.json -> systemjs.config.js

- public/docs/ts/latest/tutorial/toh-pt3.jade
> docs(toh-3): fix for empty tab

- public/docs/_examples/toh-2/ts-snippets/app.component.snippets.pt2.ts
> docs(toh-2): align snippet with final example

- public/docs/_examples/style-guide/ts/app/main.ts
> chore(lint): fix whitespace error

- tools/dart-api-builder/index.js
> chore(dart/cheatsheet): adjust path to sources

- .travis.yml
cc @kwalrath @Foxandxss @filipesilva
> chore(travis): build off of angular 2.0.0-rc.5

- public/docs/_examples/karma-test-shim.js
- public/docs/_examples/upgrade-phonecat-2-hybrid/ts/karma-test-shim.1.js
- public/docs/_examples/upgrade-phonecat-2-hybrid/ts/karma.conf.ng1.js
- public/docs/_examples/upgrade-phonecat-3-final/ts/karma.conf.ng1.js
- public/docs/_examples/webpack/ts/config/karma-test-shim.js
Yet another update. I also updated the tests in ngUpgrade because I forgot the last time.
> chore: update karma to zone 0.6.15

- public/docs/ts/_cache/tutorial/toh-pt6.jade
> chore(toh-6): refresh cache file

- public/docs/_examples/toh-1/dart-snippets/app_component_snippets_pt1.dart
> example(toh-1): fix type error in snippet

- public/docs/ts/_cache/guide/lifecycle-hooks.jade
No other changes.
cc @kwalrath
> docs(lifecycle-hooks): update to cache file

- scripts/cache.sh
cc @kwalrath (script only used by Dart docs team)
> chore(cache.sh): cleanup options and usage

- tools/api-builder/angular.io-package/index.js
Also adds the Router testing stuff that we didn't have before.
Fixes #2250
> chore: add testing API back

- public/docs/ts/latest/guide/template-syntax.jade
Peter Fryer-Davis is making these edits as a part of Ashley Kelly's UWaterloo ENGL 210J class.
> Uwaterloo 210J pfryerda edits

- public/docs/ts/latest/quickstart.jade
> docs(quickstart): fix broken link to tutorial

- public/docs/_examples/lifecycle-hooks/dart/lib/do_check_component.dart
Make equivalent TS code changes to Dart sample.
This syncs Dart with all #2177 changes pertinent to Dart.
E2E tests pass now for Dart, Suites passed:
-  public/docs/_examples/lifecycle-hooks/ts
cc @kwalrath
> examples(lifecycle-hooks): update Dart sample to match TS

- public/docs/_examples/quickstart/ts/index.html
- public/docs/dart/latest/guide/_data.json
- public/docs/js/latest/guide/_data.json
- public/docs/ts/latest/guide/browser-support.jade
Ready to go. Decided for now to leave it in the guide (rather than the cookbook)
> docs(browser-support): edits

- public/docs/ts/latest/cookbook/ngmodule-faq.jade
> docs(ngmodule-faq): fix plunker link

- public/docs/ts/latest/cookbook/ngmodule-faq.jade
> docs(ngmodule-faq): eager loaded Routed Feature Module must be imported

- public/docs/ts/latest/cookbook/a1-a2-quick-reference.jade
- public/docs/ts/latest/glossary.jade
- public/docs/ts/latest/guide/architecture.jade
Copy edits to Angular 1 to 2 Quick Ref.
> a1-a2 quick ref copy edits

- public/docs/_examples/router/ts/app/app.routing.1.ts
> fix(router): Added ModuleWithProviders export to configuration example

- public/docs/ts/latest/glossary.jade
This is a test because the kwong-glossary-updates branch kept having merge conflicts. This PR is identical to the work done in that PR but I would like to see if the conflicts have been resolved by starting anew.
> Testing glossary file updates

- public/resources/css/base/_type.scss
- public/resources/css/module/_api.scss
@naomiblack you know what to do...
> more fixes

- public/docs/_includes/_side-nav.jade
@chalin Update title on sidebar.
> update title on sidenav

- public/docs/ts/latest/guide/ngmodule.jade
> fix(ngmodule): fix broken anchor

- public/docs/ts/latest/tutorial/toh-pt6.jade
> docs(tutorial): fix broken link

- public/docs/_examples/toh-6/dart/web/main.dart
> docs(toh-6): remove BrowserClient provider comment

- public/docs/ts/latest/guide/browser-support.jade
Successfully validated in https://github.com/angular/angular/pull/11796
> docs(browser-support): add Safari 10

- public/docs/ts/latest/guide/testing.jade
> Deleted extra 'with'

- public/docs/_examples/style-guide/ts/03-04/app/core/toast.service.avoid.ts
> docs(style-guide): Example of underscore prefix to avoid.

- public/docs/_examples/cb-set-document-title/ts/sample.css
- public/docs/_examples/quickstart/js/package.1.json
also remove /cb-set-document-title/ts/sample.css
> chore: update /quickstart/js/package.1.json

- public/docs/_examples/testing/ts/app/dashboard/dashboard-hero.component.spec.ts
Fixed minor typo in DashboardHeroComponent
> Fixed minor typo in DashboardHeroComponent

- public/docs/ts/latest/quickstart.jade
> docs(quickstart): fix link to styles.css

- public/_includes/_scripts-include.jade
@naomiblack @IgorMinar This should fix the swyftype search problem. Please review and merge. Took a bit to find since there were no console errors and I hadn't touched this.
> reverting changes to swyftype 2.0 library, fixes breaking change

- public/docs/ts/latest/guide/attribute-directives.jade
Copy edits to attribute-directives.jade.
> Kwong attribute directives

- public/docs/_examples/toh-5/ts/app/dashboard.component.ts
- public/docs/_examples/toh-5/ts/app/hero-detail.component.ts
- public/docs/_examples/toh-5/ts/app/heroes.component.ts
- public/docs/ts/latest/tutorial/toh-pt5.jade
> docs(toh5): add moduleId information

- public/docs/ts/latest/guide/router.jade
- public/docs/ts/latest/tutorial/toh-pt6.jade
> docs(toh-pt6,guide): fix a grammatical error

- public/docs/js/latest/quickstart.jade
declarations instead of declaration
> Update quickstart.jade: declarations

- public/docs/ts/latest/guide/server-communication.jade
> fix(server-communication): Grammar fix

- public/docs/_examples/webpack/ts/config/webpack.common.js
> docs(webpack): change resolve ordering

- public/docs/dart/latest/_data.json
- public/docs/js/latest/_data.json
- public/docs/ts/latest/_data.json
We are using these files to generated the sidenav entries in ng2.io, however, they don't seem to have a net effect on the sidenav in ng1.io
cc @chalin @kwalrath
> rename Developer Guides to Guide

- public/docs/_examples/template-syntax/e2e-spec.ts
- public/docs/_examples/template-syntax/ts/app/app.component.html
- public/docs/_examples/template-syntax/ts/app/app.component.ts
- public/docs/_examples/template-syntax/ts/app/app.module.ts
- public/docs/_examples/template-syntax/ts/app/sizer.component.ts
- public/docs/ts/latest/guide/change-log.jade
- public/docs/ts/latest/guide/template-syntax.jade
> docs(template-syntax): explain basic two-way binding

- public/docs/_examples/_boilerplate/tsconfig.json
For Visual Studio and atom IDEs
> chore(tsconfig): add compileOnSave

- public/docs/ts/latest/guide/router.jade
> docs(router): broken link to DI chapter

- public/docs/_examples/quickstart/ts/systemjs.config.1.js
Fix for issue #2667 
ported changes made here https://github.com/angular/quickstart/commit/541bdc5f634e1142860c56cace247234edfaf74b
> fix for issue #2667

- harp.json
> chore(harp.json): remove unused parameters

- public/docs/_examples/template-syntax/ts/app/app.component.html
See https://github.com/angular/angular/issues/12583#issuecomment-256803132
> fix(e2e): remove invalid syntax usage

- public/_layout.jade
**Best viewed by** [ignoring whitespace](https://github.com/angular/angular.io/pull/2686/files?w=1).
cc @ericjim
> chore: support ng2 layout for top-level site pages

- public/resources/css/main.scss
- public/resources/css/module/_quirks.scss
read comment on line 1 of file of `_quirks.scss`
> [ng2] add quirks file which implements material 1 stuff

- src/app/api-list/api-list.component.ts
fixes https://github.com/angular/angular.io/issues/2702
> [ng2] remove reliance on router, and use location service instead for api-list

- public/resources/css/module/_side-nav.scss
fixes https://github.com/angular/angular.io/issues/2731
> [ng2] fix sidenav menu btn 1102

- public/_includes/_version-dropdown.jade
fixes https://github.com/angular/angular.io/issues/2730
> [ng2] add missing uppercase text in language selection dropdown

- public/docs/ts/latest/guide/style-guide.jade
Just a minor glitch, I think :)
> docs(style-guide): fix missing *.ts

- public/docs/_examples/architecture/dart/pubspec.yaml
- public/docs/_examples/attribute-directives/dart/pubspec.yaml
- public/docs/_examples/component-styles/dart/pubspec.yaml
- public/docs/_examples/dependency-injection/dart/pubspec.yaml
- public/docs/_examples/displaying-data/dart/pubspec.yaml
- public/docs/_examples/forms/dart/pubspec.yaml
- public/docs/_examples/hierarchical-dependency-injection/dart/pubspec.yaml
- public/docs/_examples/lifecycle-hooks/dart/pubspec.yaml
- public/docs/_examples/pipes/dart/pubspec.yaml
- public/docs/_examples/server-communication/dart/pubspec.yaml
- public/docs/_examples/structural-directives/dart/pubspec.yaml
- public/docs/_examples/template-syntax/dart/pubspec.yaml
- public/docs/_examples/toh-1/dart/pubspec.yaml
- public/docs/_examples/toh-2/dart/pubspec.yaml
- public/docs/_examples/toh-3/dart/pubspec.yaml
- public/docs/_examples/toh-4/dart/pubspec.yaml
- public/docs/_examples/toh-5/dart/pubspec.yaml
- public/docs/_examples/toh-6/dart/pubspec.yaml
- public/docs/_examples/user-input/dart/pubspec.yaml
> examples(dart): demote some packages to dev_dependencies

- public/docs/_examples/pipes/dart/web/main.dart
Match TS example and only bootstrap AppComponent.
Fixes #2492
> example(pipes): Dart e2e fix

- public/docs/_examples/_boilerplate/systemjs.config.js
- public/docs/_examples/_boilerplate/systemjs.config.web.build.js
- public/docs/_examples/_boilerplate/systemjs.config.web.js
- public/docs/_examples/quickstart/ts/systemjs.config.1.js
- public/docs/_examples/upgrade-phonecat-2-hybrid/ts/systemjs.config.1.js
- public/docs/_examples/upgrade-phonecat-3-final/ts/systemjs.config.1.js
Also merge https://github.com/angular/quickstart/pull/285 afterwards.
/cc @vsavkin @Foxandxss
> chore: add new 2.2.0 entry points

- public/docs/dart/latest/quickstart.jade
- public/docs/ts/_cache/quickstart.jade
- public/docs/ts/latest/quickstart.jade
Also did other minor copyedits.
> docs(quickstart): show qs files via code-tabs for Dart

- public/docs/_examples/dependency-injection/ts/app/app.module.ts
- public/docs/dart/latest/guide/dependency-injection.jade
- public/docs/ts/_cache/guide/dependency-injection.jade
- public/docs/ts/latest/guide/dependency-injection.jade
> [Dart] docs(dependency-injection): updates to match TS; also minor TS fixes

- public/docs/ts/latest/guide/testing.jade
> docs: fix broken link on testing guide

- public/docs/ts/latest/quickstart.jade
Incorporating Shannon's 2 copy edits.
> docs(quickstart): copy edits

- public/docs/_examples/architecture/dart/pubspec.yaml
- public/docs/_examples/attribute-directives/dart/pubspec.yaml
- public/docs/_examples/component-styles/dart/pubspec.yaml
- public/docs/_examples/dependency-injection/dart/pubspec.yaml
- public/docs/_examples/displaying-data/dart/pubspec.yaml
- public/docs/_examples/forms/dart/pubspec.yaml
- public/docs/_examples/hierarchical-dependency-injection/dart/pubspec.yaml
- public/docs/_examples/lifecycle-hooks/dart/pubspec.yaml
- public/docs/_examples/pipes/dart/pubspec.yaml
- public/docs/_examples/quickstart/dart/pubspec.yaml
- public/docs/_examples/server-communication/dart/pubspec.yaml
- public/docs/_examples/structural-directives/dart/pubspec.yaml
- public/docs/_examples/template-syntax/dart/pubspec.yaml
- public/docs/_examples/toh-1/dart/pubspec.yaml
- public/docs/_examples/toh-2/dart/pubspec.yaml
- public/docs/_examples/toh-3/dart/pubspec.yaml
- public/docs/_examples/toh-4/dart/pubspec.yaml
- public/docs/_examples/toh-5/dart/pubspec.yaml
- public/docs/_examples/toh-6/dart/pubspec.yaml
- public/docs/_examples/user-input/dart/pubspec.yaml
- public/docs/dart/latest/_data.json
- pubspec.yaml
- tools/doc-shredder/_test/test_source/multiregion/pubspec.yaml
- tools/doc-shredder/_test/test_source/no-multiregion/pubspec.yaml
> docs(dart): upgrade to 2.1.1

- README.md
> chore(README): don't install harp globally

- package.json
- public/docs/_examples/homepage-hello-world/ts/index.1.html
- public/docs/_examples/homepage-tabs/ts/index.1.html
- public/docs/_examples/homepage-todo/ts/index.1.html
- public/docs/_examples/package.json
- public/docs/_examples/quickstart/ts/package.1.json
- public/docs/_examples/webpack/ts/package.webpack.json
Also updated from 2.0.3 to 2.0.10.
Fixes #2948
> chore: pin TS version to 2.0

- public/docs/_examples/router/ts/app/crisis-center/crisis-detail-resolve.service.ts
- public/docs/ts/latest/guide/router.jade
discussed on Slack with @wardbell
> fix(router): fix Resolve docs and Resolve.resolve signature

- public/docs/ts/latest/guide/displaying-data.jade
> docs(displaying-data): remind to import `Hero` class (#2975)

- public/docs/_examples/toh-4/ts/app/hero.service.ts
- public/docs/_examples/toh-5/ts/app/hero.service.ts
> docs(toh): improve `getHeroesSlowly` in ToH-4/5 (#2443)

- public/_includes/_scripts-include.jade
> chore: upgrade to latest angularjs

- public/docs/ts/latest/tutorial/toh-pt5.jade
> docs(toh-5): clarify that class renaming should be local to file

- public/docs/_examples/attribute-directives/ts/app/app.component.1.html
- public/docs/_examples/attribute-directives/ts/app/app.component.1.ts
- public/docs/_examples/attribute-directives/ts/app/app.component.html
- public/docs/_examples/attribute-directives/ts/app/dummy.module.1.ts
- public/docs/_examples/attribute-directives/ts/app/highlight.directive.2.ts
- public/docs/_examples/attribute-directives/ts/app/highlight.directive.3.ts
- public/docs/_examples/attribute-directives/ts/plnkr.json
- public/docs/ts/latest/guide/attribute-directives.jade
One of our oldest docs was confusing and occasionally incorrect. This PR repairs much of the damage.
> docs(attribute-directives): clarify @Input and aliasing

- public/docs/_examples/package.json
Let's see if this fixes master builds.
> chore: update tsc-wrapped

- public/docs/_examples/package.json
> chore(ci): adjust zone.js version for examples

- .travis.yml
- scripts/deploy-install-preview.sh
- scripts/examples-install-preview.sh
/cc @IgorMinar @wardbell @Foxandxss
> [WIP] ci: add jobs for current release branch

- public/docs/_examples/quickstart/ts/index.html
- public/docs/_examples/setup/ts/index.html
- public/docs/_examples/setup/ts/plnkr.json
styles.css was missing from setup plunker -> 404 in console.  Removed some unused docregions.
> chore(setup): add missing styles.css to plunker + cosmetics

- public/docs/ts/latest/guide/forms.jade
> docs(forms): ngSubmit is an output property of NgForm directive

- public/docs/_examples/server-communication/ts/app/wiki/wiki-smart.component.ts
> docs(server-communication) Don't use constructor, but rather ngOnInit

- public/docs/_examples/cb-aot-compiler/ts/.gitignore
- public/docs/_examples/cb-aot-compiler/ts/app/main-jit.ts
- public/docs/_examples/cb-aot-compiler/ts/app/main.ts
- public/docs/_examples/cb-aot-compiler/ts/index-jit.html
- public/docs/_examples/cb-aot-compiler/ts/rollup-config.js
- public/docs/ts/latest/cookbook/aot-compiler.jade
@torgeirhelgevold - please review.
> chore(aot-cookbook): gitignore gen'd css and skip rollup warn on 'this'

- harp.json
> Update Naomi's bio

- public/docs/ts/latest/guide/testing.jade
But if you ask me, this paragraph doesn't make much sense without understanding what shims are we talking about here
So it might be better to move it below as well?
> Changed the wording to reflect new location

- public/docs/_examples/reactive-forms/ts/plnkr.json
- public/docs/_examples/reactive-forms/ts/src/index-final.html
- public/docs/_examples/reactive-forms/ts/src/main-final.ts
Also took the freedom of moving "main-final" to "src/"
> docs(reactive-forms): fix plunkers

- public/docs/ts/latest/guide/router.jade
> Fixes(typo): Adds missing backtick

- public/resources/css/module/_announcement-bar.scss
> fix(banner): Fixes button positioning (#3038)

- harp.json
Needed to update my bio as I no longer work at Capital One. Thanks!
> chore(bios): update bio for Kapunahele

- tools/plunker-builder/builder.js
This was changed in the wrong file earlier.
> chore: update date for plunkers

- public/docs/ts/latest/guide/reactive-forms.jade
> fixed broken links in reactive forms doc

- public/docs/ts/latest/guide/template-syntax.jade
> Correct a type error

- public/docs/ts/latest/guide/appmodule.jade
- public/docs/ts/latest/guide/reactive-forms.jade
- public/docs/ts/latest/guide/router.jade
- public/docs/ts/latest/guide/style-guide.jade
- public/docs/ts/latest/tutorial/toh-pt6.jade
Fixes #3243
Fixes #3245
Fixes #3253
Fixes #3254
Fixes #3271
> chore: fix a few standing typos

- public/_includes/_footer.jade
> chore: update twitter handle in footer

- public/docs/ts/latest/cookbook/_data.json
- public/docs/ts/latest/cookbook/ajs-quick-reference.jade
These are copy edits to ajs-quick-reference.jade. Thank you!
> docs(ajs-quick-reference): copy edits

- public/docs/ts/latest/guide/component-styles.jade
- public/docs/ts/latest/guide/pipes.jade
@juleskremer here are my edits for the "Component Styles" page. Just three comments/questions in this one--search for "CF:".
> Edits to "Component Styles" and "Pipes"

- public/docs/ts/latest/guide/security.jade
There weren't many issues and I didn't add any inline comments.
> Copyedits in the "Security" page.

- public/docs/_examples/cb-i18n/ts/plnkr.json
> docs(i18n): fix plunker

- tools/plunker-builder/builder.js
- tools/plunker-builder/translator/fileTranslator.js
- tools/plunker-builder/translator/rules/indexHtml.js
- tools/plunker-builder/translator/rules/systemjsConfigExtras.js
> chore: refactor plunker translators with a new systemjs one

- public/docs/ts/latest/cli-quickstart.jade
small evolution from angular CLI config file
> added dot before angular-cli.json

- public/docs/ts/latest/_data.json
- public/docs/ts/latest/cli-quickstart.jade
Copy edits to the CLI Quickstart.
> docs(cli-quickstart): copy edits

- public/docs/ts/latest/glossary.jade
- public/docs/ts/latest/guide/forms.jade
Reverts angular/angular.io#3159
> Revert "Content edits in the Angular 2 Guide."

- public/docs/ts/latest/guide/hierarchical-dependency-injection.jade
Copy edits to follow guidelines and a couple of edits to smooth wording.
> docs(hierarchical-di): copy edits

- public/docs/ts/latest/guide/change-log.jade
Copy edits to reflect guidelines.
> docs(change-log): copy edits

- public/docs/_examples/router/ts/src/app/selective-preloading-strategy.ts
- public/docs/ts/latest/guide/router.jade
Apply guidelines throughout copy and edit TOC to reflect structure of doc. Thanks!
>  docs(routing-nav): copy edits

- public/docs/ts/latest/guide/typescript-configuration.jade
This PR includes copy edits to apply guidelines and to clarify the statement on lines 77-78.
Thank you!
> docs(typescript-config): copy edits applying guidelines

- public/docs/ts/latest/guide/dependency-injection.jade
- copy edits applying guidelines.
- TOC update to reflect shape of doc with all headings.
- a few copy changes to improve clarity.
> docs(DI): copy edits and TOC update

- public/docs/ts/latest/guide/style-guide.jade
This PR contains:
- Updates to the TOC.
- Copy edits to apply writing guidelines.
> docs(style-guide): copy edits applying guidelines

- public/docs/ts/latest/cookbook/component-communication.jade
- Copy edits applying guidelines.
- Updated TOCs.
> docs(component-communication): copy edits and update TOCs

- public/docs/ts/latest/cookbook/_data.json
- public/docs/ts/latest/cookbook/aot-compiler.jade
- copy edits applying guidelines
- update TOCs to reflect shape of doc
- minor edits for clarity
> docs(aot-cookbook): copy edits applying guidelines, update TOCs

- public/docs/ts/latest/tutorial/toh-pt1.jade
Change "data flow" to "data flows" and edit punctuation. Also checked all the other toh pages for plural data, but found none.
@kwalrath fyi
> docs(toh): change data flow to data flows

- public/docs/_examples/cb-dependency-injection/ts/src/app/date-logger.service.ts
- public/docs/_examples/cb-dependency-injection/ts/src/app/hero-of-the-month.component.1.ts
- public/docs/_examples/cb-dependency-injection/ts/src/app/hero-of-the-month.component.html
- public/docs/_examples/cb-dependency-injection/ts/src/app/hero-of-the-month.component.ts
- public/docs/_examples/cb-dependency-injection/ts/src/app/minimal-logger.service.ts
- public/docs/_examples/cb-dependency-injection/ts/src/app/runners-up.ts
- public/docs/_examples/dependency-injection/ts/src/app/app.component.ts
- public/docs/_examples/dependency-injection/ts/src/app/app.config.ts
- public/docs/ts/latest/cookbook/dependency-injection.jade
- public/docs/ts/latest/glossary.jade
- public/docs/ts/latest/guide/dependency-injection.jade
This PR:
- Updates TOC
- Applies guidelines
- Includes minor copy edits for clarity.
> docs(DI-cookbook): copy edits and update TOCs

- public/docs/ts/latest/tutorial/toh-pt3.jade
> Fix typo in tutorial

- public/docs/ts/latest/cookbook/dynamic-form.jade
This PR includes updates to apply guidelines:
- change we -> you 
- apply sentence case to headings
- update TOCs to reflect doc headings
> docs(dynamic-forms): edit copy to guidelines standards

- public/docs/ts/latest/tutorial/toh-pt2.jade
Commit https://github.com/angular/angular.io/pull/3504/commits/0404ae22c7c69c819a3c3e9a324d956a0e6aafee is based on feedback from @kwalrath 
cc @kapunahelewong
> docs(toh-2): copyedits

- public/docs/ts/latest/tutorial/toh-pt1.jade
The 'hero' property is in the AppComponent class, not in Hero.
> Fix minor text error in toh-pt1.jade. The 'hero' property is in the AppComponent class, not in Hero.

- public/docs/ts/latest/tutorial/toh-pt3.jade
In the tutorial, "app.component.ts" is the file to insert the template in. Was incorrectly mentioned as "app.component,html"
> Corrected incorrect file name in tutorial

- public/docs/ts/latest/tutorial/toh-pt3.jade
> docs(toh-pt3): correct spelling mistake

- public/docs/ts/latest/tutorial/toh-pt1.jade
Hero class was referenced instead of AppComponent.
> Bad class reference fixed

- public/docs/ts/latest/tutorial/toh-pt3.jade
> docs(toh-pt3): fix broken link

- public/docs/ts/latest/cookbook/set-document-title.jade
Apply guidelines to copy through minor edits - mostly we->you.
> docs(doc-title-cookbook): apply guidelines

- public/docs/ts/latest/cookbook/i18n.jade
This PR:
- Applies guidelines.
- Updates TOCs.
- Includes minor copy edits.
> docs(i18n): apply guidelines and update TOCs

- public/docs/ts/latest/guide/_data.json
> docs(universal): remove nav link
