- public/_includes/_hero-home.jade
Fixes #3.
@alexwolfe Changed the ng-conf link to the Keynote and YouTube playlist. What do you think of the text "Videos now on YouTube"? I want to set the expectations that the link will take you to YouTube. Ideally I'd like a little play icon in the button, but let me know if that's overkill.
> ng-conf video link

- public/docs/dart/latest/quickstart.jade
@alexwolfe could you patch this in ASAP? The alpha 19 release broke the Dart instructions.
> Update Dart quick start to angular2 alpha 19

- public/docs/js/latest/quickstart.jade
This is ready to go, using a pre-release of typescript 1.5 beta from Mohamed's fork.
Note that we should re-publish this when the beta is released.
> Update quickstart to use TypeScript

- public/docs/dart/latest/guide/displaying-data.jade
- public/docs/dart/latest/guide/setup.jade
- public/docs/dart/latest/guide/user-input.jade
- public/docs/dart/latest/quickstart.jade
@alexwolfe, could you publish these small updates at your earliest convenience?
The existing text isn't wrong, but it shows old version numbers.
> update dart angular2 version, don't display pub get output

- public/docs/dart/latest/quickstart.jade
It turns out that reflection is likely _not_ going away. I've added a step for using the Angular transformer, and made miscellaneous other updates.
> dart quickstart: add transformer, use alpha.25

- public/docs/dart/latest/guide/displaying-data.jade
- public/docs/dart/latest/guide/making-components.jade
- public/docs/dart/latest/guide/setup.jade
- public/docs/dart/latest/guide/user-input.jade
- public/docs/dart/latest/quickstart.jade
This was a fairly substantial change because:
* changed for/if -> ng-for/if
* converted the code to put each file in its own library, instead of using `part of`. (I hadn't realized many people really don't like `part of`, as evinced by the comments on https://github.com/angular/angular/issues/1817.)
* added coverage of the angular2 transformer
* changed every pubspec to include the transformer and to specify a version range for browser (now that "any" is discouraged)
* ran dartfmt over all the files
I've tested everything, but I'd welcome more testing. Anyone up for a run-through of these docs?
Also... I should put the example code files somewhere online.
> Update the Dart guide's code and text to alpha.26 (from 23)

- public/docs/dart/latest/guide/displaying-data.jade
In the text show_properties.dart is (correctly) placed in the lib directory,
while in the comment at the top of the file, it's path is under web.
> Typo in code example of lib/show_properties.dart

- public/docs/js/latest/quickstart.jade
A number of people have commented on github that they get the wrong typescript version, because of Visual Studio's
version being found instead of npm.
Fixes #99
> fix(quickstart): Add helpful note for Windows users

- public/docs/dart/latest/guide/displaying-data.jade
- public/docs/dart/latest/guide/setup.jade
- public/docs/dart/latest/guide/user-input.jade
- public/docs/dart/latest/quickstart.jade
I've tested, and all of the code works in alpha 29 *except* for examples that use directives (NgFor, NgIf) ONLY when run using `pub serve`. Everything's fine in Dartium with a SimpleHttpServer or in Chrome with a SimpleHttpServer & the output of `pub build`.
> Dart alpha 29

- public/_includes/_head-include.jade
- public/_includes/_hero.jade
- public/_includes/_hover-card.jade
- public/_includes/_next-item.jade
- public/_includes/_version-dropdown.jade
- public/_layout.jade
- public/docs/_includes/sidenav/_primary.jade
- public/docs/_includes/sidenav/_secondary.jade
- public/docs/_includes/sidenav/_tertiary.jade
- public/docs/dart/latest/guide/index.jade
- public/docs/js/latest/api/annotations/index.jade
- public/docs/js/latest/api/change_detection/index.jade
- public/docs/js/latest/api/core/index.jade
- public/docs/js/latest/api/di/index.jade
- public/docs/js/latest/api/directives/index.jade
- public/docs/js/latest/api/forms/index.jade
- public/docs/js/latest/api/http/index.jade
- public/docs/js/latest/api/index.jade
- public/docs/js/latest/api/pipes/index.jade
- public/docs/js/latest/api/router/index.jade
- public/docs/js/latest/api/test/index.jade
- public/docs/js/latest/guide/index.jade
This isn't ready to merge yet for two reasons:
1) I can't get `harp compile` to work: the API doc templates are throwing `Error - unexpected token "pipeless-text"` on docs like e.g. `docs/js/latest/api/annotations/ClassDefinition-interface.html`. I couldn't figure out what the error was.
2) I made local changes to some of the API doc index pages that contain vars set by the dgeni template. These should really be fixed in the angular/angular repo. They're in this PR for testing, but the error above makes me think I missed something...?
See https://github.com/angular/angular/issues/3325 in angular/angular for the template issue.
> harp(update): var changes to allow use with harp 0.17.0

- public/docs/dart/latest/guide/displaying-data.jade
- public/docs/dart/latest/guide/setup.jade
- public/docs/dart/latest/guide/user-input.jade
- public/docs/dart/latest/quickstart.jade
How does this look for updating the Dart docs to alpha.33?
The last guide didn't require an update because it doesn't show pubspec.yaml or main.dart.
> Update Dart docs to alpha.33

- public/docs/js/latest/quickstart.jade
fixes #172
^1.5.0-beta means >= 1.5.0 and < 2.0.0 and is technically valid. however
it's probably nicer not to refer to beta versions in the doc.
> Set the minimum typescript version to 1.5.0

- public/docs/js/latest/guide/setup.jade
- public/docs/js/latest/guide/setupAlt.jade
- public/docs/js/latest/quickstart.jade
- `http-server` is already used in the quick start guide,
- fontend devs are less likely to have Python installed
> Step by step guide: use http-server instead of python

- public/api-builder/typescript-package/processors/readTypeScriptModules.js
The latest angular/angular master contains publicly exported abstract classes, which the readTypeScriptProcessor doesn't like.
> fix(doc-gen): ignore resolved symbols that have no declarations

- public/docs/_examples/quickstart/js/app.js
- public/docs/_examples/quickstart/js/index.html
- public/docs/_examples/quickstart/ts/src/index.1.html
- public/docs/_examples/quickstart/ts/src/index.html
- public/docs/ts/latest/testing/_data.json
- public/docs/ts/latest/testing/application-under-test.jade
- public/docs/ts/latest/testing/first-app-tests.jade
- public/docs/ts/latest/testing/jasmine-testing-101.jade
- public/docs/ts/latest/testing/testing-an-angular-pipe.jade
- public/docs/ts/latest/tutorial/index.jade
- public/docs/ts/latest/tutorial/toh-pt1.jade
- public/docs/ts/latest/tutorial/toh-pt2.jade
Incorporates PRs #275, #274, #271, #270, #263
> (docs) testing and toh formatting improvements

- public/api-builder/angular.io-package/index.js
- public/api-builder/angular.io-package/processors/extractDirectiveClasses.js
- public/api-builder/angular.io-package/processors/extractDirectiveClasses.spec.js
- public/api-builder/angular.io-package/processors/matchUpDirectiveDecorators.js
- public/api-builder/angular.io-package/templates/class.template.html
- public/api-builder/angular.io-package/templates/directive.template.html
- public/api-builder/angular.io-package/templates/function.template.html
- public/api-builder/angular.io-package/templates/var.template.html
- public/api-builder/docs-package/index.js
- public/api-builder/docs-package/processors/extractDirectiveClasses.js
- public/api-builder/docs-package/processors/extractDirectiveClasses.spec.js
- public/api-builder/typescript-package/index.js
- public/api-builder/typescript-package/processors/readTypeScriptModules.js
- public/docs/ts/latest/api/index.jade
- public/resources/css/main.scss
- public/resources/css/module/_heading-code.scss
The new processor will convert classes that are annotated (decorated) as Directives, to a new doc type of `directive` and also extract the juicy directive metadata into the doc so that it can be displayed nicely.
> Directive doctypes - initial functionality

- gulpfile.js
- package.json
- tools/api-builder/angular.io-package/index.js
- tools/api-builder/target-package/index.js
- tools/api-builder/target-package/inline-tag-defs/target.js
- tools/api-builder/target-package/inline-tag-defs/target.spec.js
- tools/api-builder/target-package/mocks/mockPackage.js
- tools/api-builder/target-package/services/targetEnvironments.js
- tools/api-builder/target-package/services/targetEnvironments.spec.js
The `target` package allows us to filter blocks of content in our API docs by target language.
This PR implements this package also updates the gulp API build process.
* the `build-api-docs` task now runs two other tasks `build-js-api-docs` and `build-ts-api-docs`
* these two sub-tasks, which can be run independently, will generate API docs from the TS source code and output into the `docs/js/latest/api` and `docs/ts/latest/api` folders respectively.
The target package contains a new start-stop inline type definition of the form `{@target ts}...{@endtarget}`. The target can take one or more "targets" - in our case it is going to be either `ts` or `js`. If the target of a block doesn't match the current target environment for the dgeni run, the block is excluded.
For example you could …
> api-builder: add target package

- public/features.jade
Angular 2 isn't just ES6 + types and annotations, so this will confuse people.
As an example, here's a file using two huge features that aren't part of ES6 classes - [object properties and privacy](https://github.com/jeffmo/es-class-static-properties-and-fields).
> (docs) Angular 2 isn't ES6, it's TypeScript

- public/docs/ts/latest/quickstart.jade
Adding appendix to TS quickstart regarding ES6 support and how to use a shim to get the example working on older browsers.
> docs(quickstart-ts): add note about ES6 shim

- public/docs/ts/latest/tutorial/index.jade
- public/index.jade
- public/resources/css/base/_type.scss
- public/resources/css/module/_code.scss
changes text from `how we roll` to `up next`
changes font size for code blocks from `15px` to `13px`
changes links from `edit on plunker` to `try in plunker`
re-orders tabs in code samples
> removes first demo

- public/docs/ts/latest/quickstart.jade
Docs referenced the postinstall script of `package.json` but the code window was entitled `tsconfig.json`. That was a mistake, right?
> docs(quickstart): fix typo, tsconfig.json -> package.json

- public/docs/_includes/styleguide/_code-examples.jade
Was actually trying to load `app.js` when that was just an illustration
> docs(styleguide): escape app.js script example

- .vscode/settings.json
VS Code will use the version of typescript installed locally for the docs samples
> chore: point VS Code to the examples's local version of typescript

- public/contribute.jade
The fix in #780 that we want to keep
> docs(contribute): fix link to Angular Material; close #780

- public/docs/ts/latest/guide/template-syntax.jade
also changed anchors to use id instead of name
> docs(template-syntax): clarify [()] de-sugaring

- public/docs/_examples/toh-1/dart-snippets/app_component_snippets_pt1.dart
- public/docs/_examples/toh-1/dart/lib/app_component.dart
- public/docs/_examples/toh-1/dart/pubspec.yaml
- public/docs/_examples/toh-1/dart/web/index.html
- public/docs/_examples/toh-1/dart/web/main.dart
- public/docs/dart/latest/tutorial/_data.json
- public/docs/dart/latest/tutorial/index.jade
- public/docs/dart/latest/tutorial/toh-pt1.jade
- public/docs/ts/latest/tutorial/index.jade
A quick conversion of the first two TOH pages to Dart, using #700 as a basis for toh-1.
(Thank you, @kasperpeulen!)
> docs(dart/toh): add intro & toh-1 pages

- public/docs/_examples/toh-2/dart-snippets/app_component_snippets_pt2.dart
- public/docs/_examples/toh-2/dart/lib/app_component.dart
- public/docs/_examples/toh-2/dart/pubspec.yaml
- public/docs/_examples/toh-2/dart/web/index.html
- public/docs/_examples/toh-2/dart/web/main.dart
- public/docs/dart/latest/tutorial/toh-pt2.jade
Based on @kasperpeulen's #700, with a few changes.
> docs(toh/dart): convert toh-2 to dart

- public/resources/css/base/_type.scss
- public/resources/css/module/_api.scss
- tools/api-builder/angular.io-package/templates/class.template.html
* Reverts `_type.scss` to a [past version](https://github.com/angular/angular.io/blob/6be9523c2aafd2d6fd4aae99d713039609d3b326/public/resources/css/base/_type.scss)
* Add Material Design Blue 600 link styling globally (in `_type.scss`)
* Narrow code styling to api docs using `_api.scss` (using `.api-doc-code`)
* Fixes: https://fix-cheatsheet.firebaseapp.com/docs/ts/latest/cheatsheet.html
* Links: https://fix-cheatsheet.firebaseapp.com/docs/ts/latest/api/common/Control-class.html
CLOSES
https://github.com/angular/angular.io/issues/1125
@naomiblack
> docs(code color and global links): narrow code styling changes only to api docs

- public/docs/dart/latest/guide/hierarchical-dependency-injection.jade
This PR uses hierarchical-dependency-injection as the guinea pig. The text is similar to what's used in copyedited TS pages such as https://angular.io/docs/ts/latest/guide/displaying-data.html.
@chalin and @thso, what do you think?
> docs(dart): proposed text for linking to Dart samples

- public/resources/css/module/_api.scss
- tools/api-builder/angular.io-package/templates/class.template.html
- tools/api-builder/angular.io-package/templates/decorator.template.html
- tools/api-builder/angular.io-package/templates/function.template.html
- tools/api-builder/angular.io-package/templates/var.template.html
- tools/api-builder/docs-package/processors/addNotYetDocumentedProperty.js
* Remove `Not yet documented` from the api doc. With the exception of `how to use` and `what it does`
* https://remove-not-yet-doc.firebaseapp.com/docs/ts/latest/api/
* ^Pick any api doc page (example: https://remove-not-yet-doc.firebaseapp.com/docs/ts/latest/api/common/AbstractControl-class.html)
* NOTE: @naomiblack you'll notice that `Class Description` is empty that's because it's an empty doc thing in the angular2 repo https://github.com/angular/angular/blob/2.0.0-beta.14/modules/angular2/src/common/forms/model.ts#L50-L252, the solution here is to remove that empty block in angular2 or actually document it.
CLOSES:
https://github.com/angular/angular.io/issues/1109
@naomiblack  @petebacondarwin
> chore(not yet documented): remove placeholder to reduce noise

- public/docs/ts/latest/cookbook/a1-a2-quick-reference.jade
- public/docs/ts/latest/cookbook/component-communication.jade
- public/docs/ts/latest/guide/displaying-data.jade
- public/docs/ts/latest/guide/forms.jade
- public/docs/ts/latest/guide/server-communication.jade
- public/docs/ts/latest/guide/structural-directives.jade
- public/docs/ts/latest/guide/template-syntax.jade
- public/docs/ts/latest/guide/user-input.jade
- public/docs/ts/latest/tutorial/toh-pt2.jade
**WIP Do not merge until ready and after beta.17** 
Continuation of PR #1205
Sweep both Dart and TS prose.
See [angular PR](https://github.com/angular/angular/pull/8264) and [related PR tests](https://github.com/angular/angular/pull/8264/files#diff-e11facd5c1fe0b0486fb91c5b94109f9R236)
> [WIP] docs: ngFor 'let' prose

- public/docs/_examples/pipes/dart/lib/exponential_strength_pipe.dart
- public/docs/_examples/pipes/dart/lib/fetch_json_pipe.dart
- public/docs/_examples/pipes/dart/pubspec.yaml
Dev guide pipes stopped working in beta.16; this rolls it back to the last known working version (beta.15).
> chore(dart): pipes example rolled back to beta.15

- public/docs/_examples/cb-component-communication/ts/app/app.component.html
- public/docs/_examples/cb-dependency-injection/ts/app/hero.service.ts
- public/docs/_examples/dependency-injection/e2e-spec.js
- public/docs/_examples/hierarchical-dependency-injection/e2e-spec.js
- public/docs/ts/latest/guide/router-aux.jade
That is just a grammatical error.
PS: My editor decided to get rid of some spaces on one file, that works for me but I can rebase if needed.
> docs: rename heros to heroes

- public/docs/_examples/component-styles/ts/app/quest-summary.component.ts
- public/docs/_examples/package.json
- public/docs/_examples/quickstart/ts/systemjs.config.1.js
- public/docs/_examples/quickstart/ts/tsconfig.1.json
- public/docs/_examples/style-guide/ts/03-05/app/shared/toast/toast.component.ts
- public/docs/_examples/style-guide/ts/03-06/app/shared/toast/toast.component.ts
- public/docs/_examples/style-guide/ts/04-10/app/shared/filter-text/filter-text.component.ts
- public/docs/_examples/style-guide/ts/04-10/app/shared/modal/modal.component.ts
- public/docs/_examples/style-guide/ts/04-10/app/shared/nav/nav.component.ts
- public/docs/_examples/style-guide/ts/04-10/app/shared/toast/toast.component.ts
- public/docs/_examples/style-guide/ts/04-10/app/typings.d.ts
- public/docs/_examples/testing/ts/app/bag.ts
- public/docs/_examples/tsconfig.json
- public/docs/ts/latest/quickstart.jade
as the CLI does. Also adds `typings.d.ts` declaring common js `module.id` object
> docs: switch to commonjs module generation

- public/_includes/_util-fns.jade
- public/docs/dart/latest/_util-fns.jade
- public/docs/dart/latest/guide/structural-directives.jade
- public/docs/ts/latest/guide/structural-directives.jade
- copyedits and other minor edits for TS
- a first version of the chapter for Dart
> docs(dev guide): structural-directives - ts minor edits, dart first version

- public/_includes/_util-fns.jade
- public/docs/_examples/attribute-directives/dart/lib/app_component.dart
- public/docs/_examples/attribute-directives/dart/lib/app_component.html
- public/docs/_examples/attribute-directives/dart/lib/app_component_1.html
- public/docs/_examples/attribute-directives/dart/lib/highlight_directive.dart
- public/docs/_examples/attribute-directives/dart/lib/highlight_directive_1.dart
- public/docs/_examples/attribute-directives/dart/lib/highlight_directive_2.dart
- public/docs/_examples/attribute-directives/ts/app/app.component.1.html
- public/docs/_examples/attribute-directives/ts/app/app.component.html
- public/docs/_examples/attribute-directives/ts/app/highlight.directive.1.ts
- public/docs/_examples/attribute-directives/ts/app/highlight.directive.ts
- public/docs/_examples/attribute-directives/ts/index.html
- public/docs/dart/latest/_util-fns.jade
- public/docs/dart/latest/guide/attribute-directives.jade
- public/docs/ts/latest/_util-fns.jade
- public/docs/ts/latest/guide/attribute-directives.jade
- public/docs/ts/latest/guide/structural-directives.jade
In https://github.com/angular/angular.io/commit/f4acc0ccbcb167d769edce892f1d3bfde0810707 (Dec. 2015) the **TS example code was simplified**, with the `myHighlight` attributed directive being applied to a `<p>` element directly, instead of the `<span>` (and so the span was eliminated). This commit also updates the TS prose, and makes all TS and Dart versions of the example consistent with this simplification (i.e., the elimination of the span).
**TS** guide/attribute-directives updates:
- example code clean-up; e2e tests pass
- `.jade` file:
- mainly copyedits, but also
- prep for extension by Dart .jade file
**Dart** guide/attribute-directives:
- Code has been fixed; it was in an inconsistent state, and not fully function.
- Dart `.jade` extends TS `.jade` file with minor overrides
Minor …
> docs(dev guide): attribute-directives - updated dart/ts code and new dart prose

- public/docs/_examples/attribute-directives/dart/lib/app_component_1.html
- public/docs/_examples/attribute-directives/ts/app/app.component.1.html
- public/docs/ts/latest/guide/attribute-directives.jade
Jade can’t parse inlined Angular adorned HTML properly, so it is best to put such source in a file and include with `makeExample`.
> docs(dev guide): attribute-directives - move html excerpt to .html file

- public/docs/dart/latest/_util-fns.jade
- public/docs/dart/latest/guide/hierarchical-dependency-injection.jade
- public/docs/dart/latest/guide/structural-directives.jade
- public/docs/ts/latest/guide/hierarchical-dependency-injection.jade
- public/docs/ts/latest/guide/structural-directives.jade
Replaced uses of `liveExLinks` mixin and then deleted its definition.
> docs(dev guide): cleanup of deprecated Jade mixin

- public/docs/ts/latest/guide/displaying-data.jade
This is the first step for closing #935 
The big image before the TOC gives a weird visualization, but I think that it should be there or perhaps delete it.
> docs(displaying-data): add table of contents

- public/docs/_layout.jade
- public/docs/dart/latest/cheatsheet.jade
- public/docs/js/latest/cheatsheet.jade
- public/resources/css/layout/_grids.scss
- public/resources/css/layout/_layout.scss
- public/resources/css/module/_showcase.scss
* Encapsulate all doc guides within a 10 sized column to reduce the lines of the guides
* Apply doc style guide to Quickstart, Guide, Cookbook, Tutorial, and Basics 
* Live: https://docs-right-margin.firebaseapp.com/docs/ts/latest/
@naomiblack @alexwolfe
> feat(style guide docs): encapsulate all doc guides within a 10 sized column

- public/docs/_examples/server-communication/dart/lib/toh/hero_service.dart
- public/docs/_examples/server-communication/ts/app/add-rxjs-operators.ts
- public/docs/_examples/server-communication/ts/app/hero-data.ts
- public/docs/_examples/server-communication/ts/app/main.ts
- public/docs/_examples/server-communication/ts/app/toh/hero-list.component.1.ts
- public/docs/_examples/server-communication/ts/app/toh/hero-list.component.ts
- public/docs/_examples/server-communication/ts/app/toh/hero.service.1.ts
- public/docs/_examples/server-communication/ts/app/toh/hero.service.ts
- public/docs/_examples/server-communication/ts/app/wiki/wiki-smart.component.ts
- public/docs/_examples/server-communication/ts/app/wiki/wiki.component.ts
- public/docs/_examples/server-communication/ts/app/wiki/wikipedia.service.ts
- public/docs/ts/latest/guide/server-communication.jade
Fixes #1265 by removing Status Code check AND adds operators individually rather than ALL the operators because the latter approach triggered 300 file loads in Plunkers.
> docs(http): remove status 200 guard and add RxJS operators individually

- public/_includes/_util-fns.jade
- public/docs/_examples/quickstart/ts/app/main.ts
- public/docs/ts/latest/quickstart.jade
Avoiding `ts` in the file path will make it a bit easier to construct the path to the Dart version (by simply appending to the path rather than having to massage the path).
This update allows us to be more DRY when referencing examples and excerpts. E.g.,
```jade
+makeExcerpt('quickstart/ts/app/app.component.ts', 'import', 'app/app.component.ts (import)')
```
can now be just
```jade
+makeExcerpt('app/app.component.ts', 'import')
```
Also defined new mixin named `makeExample1`, for examples, using this new argument scheme. The original `makeExample` has been left untouched.
Applied new mixins to quickstart.
> chore(docs): revise makeExcerpt mixin for DRYer ref to examples

- public/_includes/_util-fns.jade
- public/docs/dart/latest/_util-fns.jade
- public/docs/dart/latest/guide/index.jade
- public/docs/ts/latest/guide/index.jade
Also copy edited the TS version a bit.
NOTE: The TS version (and thus the Dart version) talks about "Reference" and "Resources" sections that don't exist. (API Reference does, but not Reference, as such.)
> docs(dart): update BASICS intro

- public/docs/dart/latest/_util-fns.jade
- public/docs/ts/latest/_util-fns.jade
- public/docs/ts/latest/guide/attribute-directives.jade
- public/docs/ts/latest/guide/component-styles.jade
- public/docs/ts/latest/guide/hierarchical-dependency-injection.jade
- public/docs/ts/latest/guide/lifecycle-hooks.jade
- public/docs/ts/latest/guide/pipes.jade
- public/docs/ts/latest/guide/server-communication.jade
- public/docs/ts/latest/guide/structural-directives.jade
- public/docs/ts/latest/quickstart.jade
This fixes various issues such as:
- Missing space in Dart version between the live demo and demo source links.
- Live example link directing to Plunker for Dart.
- Copyedits.
The main mixins (`liveExampleLink` and `liveExampleLink2`) used to support the generation of links now assume reasonable default values for their arguments, and in most cases the defaults are used.
> docs(dart): cleanup 'live example' links

- public/docs/_examples/server-communication/dart/.docsync.json
- public/docs/_examples/server-communication/dart/lib/app_component.dart
- public/docs/_examples/server-communication/dart/lib/toh/hero.dart
- public/docs/_examples/server-communication/dart/lib/toh/hero_service.dart
- public/docs/_examples/server-communication/dart/pubspec.yaml
- public/docs/_examples/server-communication/dart/web/main.dart
- public/docs/dart/latest/guide/_data.json
- public/docs/dart/latest/guide/server-communication.jade
- public/docs/js/latest/guide/_data.json
- public/docs/ts/latest/guide/_data.json
- public/docs/ts/latest/guide/server-communication.jade
- Dart code: fix issues raised by @thso during an earlier review.
- Dart code: remove `show x` clauses from `import`s.
- Dart add docsync config file.
- Prose: make consistent use of `_Http` variables; otherwise use "HTTP".
- Prose: add links to the demos list.
> docs(server-communication): cleanup, mainly for Dart

- public/docs/ts/latest/tutorial/toh-pt3.jade
- public/docs/ts/latest/tutorial/toh-pt4.jade
So @johnpapa got some feedback on the ToH and asked me to try to improve it.
Let me go step by step:
_Multiple components_
>Let's add that array property to the bottom of the @Component configuration object, immediately after the template and styles properties.
>>**Which file?**
>>**Also, does it matter where in @Component configuration this is put?**
I put a label in the example to specify which file and also reworded the sentence a bit to tell that where to put the array is a matter of choice than a fixed place.
>Let’s verify that we have the following structure
>>**You might want to say “.js and .map files not shown**
This part refers to the filetrees. I personally don't think that we need to explicitly say that the .js and .map files are not shown.
---
_Services_
>The Injector has a …
> docs(toh): put a bit of clarification

- public/docs/ts/latest/guide/npm-packages.jade
- public/docs/ts/latest/quickstart.jade
Other versions (4.x and 6.x) are problematic as today so we will recommend those versions for the time being.
> docs: add recommended node and npm versions

- public/docs/_examples/cb-dependency-injection/e2e-spec.js
- public/docs/_examples/cb-dependency-injection/ts/app/app.component.html
- public/docs/_examples/cb-dependency-injection/ts/app/app.component.ts
- public/docs/_examples/cb-dependency-injection/ts/app/hero-of-the-month-literals.component.ts
- public/docs/_examples/dependency-injection/e2e-spec.js
- public/docs/_examples/dependency-injection/ts/app/providers.component.ts
- public/docs/ts/latest/cookbook/dependency-injection.jade
- public/docs/ts/latest/guide/dependency-injection.jade
@wardbell I have extended both the DI cookbook and the dev guide to include the new object literal based syntax for defining providers. 
Is this what you had in mind?
The cookbook was definitely easier to update since all the variations on ```provide(..)``` are lumped together in the same component. This made it possible to show both versions in all cases with little effort.
In the dev guide the components are much more granular, so I think it would sacrifice code readability if we go through and show all the samples using both flavors. Instead I focused on explaining the new syntax as a yet another alternative (there are three alternatives now).  
cc: @PascalPrecht
> docs(DI articles - showing providers using object literals)

- public/docs/dart/latest/_util-fns.jade
Fixes #1513.
Note that `adjustExamplePath()` is being renamed to `adjustTsExamplePath4Dart()` in #1510.
> chore(dart/_util-fns): make adjustExamplePath idempotent

- public/_includes/_util-fns.jade
- public/docs/_examples/template-syntax/dart/lib/app_component.dart
- public/docs/_examples/template-syntax/dart/lib/app_component.html
- public/docs/_examples/template-syntax/ts/app/app.component.html
- public/docs/_examples/template-syntax/ts/app/app.component.ts
- public/docs/dart/latest/_util-fns.jade
- public/docs/dart/latest/guide/template-syntax.jade
- public/docs/ts/latest/guide/template-syntax.jade
Fixes #1460.
- Dart
- update prose to new doc design.
- enable e2e tests. Note: **tests pass**.
- TS: copyedits and changes to support Dart doc.
> docs(template-syntax): review and update Dart to new doc design

- public/_includes/_util-fns.jade
- public/docs/dart/latest/_util-fns.jade
- public/docs/dart/latest/guide/server-communication.jade
- public/docs/ts/latest/quickstart.jade
`makeExample` can now work with both doc folder relative and project relative paths.
> chore(_util-fns): generalize makeExample, drop makeProjExample

- public/docs/_examples/upgrade-adapter/ts/app/hero-detail.directive.ts
The `heroDetail` directive is shown as an example of a component directive, such as those built using the `.component()` helper in v1.5+. In order for the directive to be functionaly equivalent with the component directive created with `.component`, it needs to be restricted to elements only. (If the `restrict` is omitted, it defaults to `'AE'`, which would also match attributes.)
/cc @teropa
> docs(upgrade): restrict component directive to elements

- public/docs/_examples/toh-1/dart-snippets/app_component_snippets_pt1.dart
- public/docs/_examples/toh-1/dart/lib/app_component.dart
- public/docs/_examples/toh-1/dart/web/main.dart
- public/docs/dart/latest/tutorial/toh-pt1.jade
- Fixed HTML.
- Removed unnecessary snippet since it is in the code.
- Copyedit: (Hero property) -> (hero property).
> docs(toh-1/dart): minor edits

- public/docs/dart/latest/tutorial/index.jade
- public/docs/dart/latest/tutorial/toh-pt1.jade
- public/docs/dart/latest/tutorial/toh-pt2.jade
- public/docs/dart/latest/tutorial/toh-pt3.jade
- public/docs/dart/latest/tutorial/toh-pt4.jade
- public/docs/dart/latest/tutorial/toh-pt5.jade
- public/docs/ts/latest/tutorial/index.jade
- public/docs/ts/latest/tutorial/toh-pt1.jade
- public/docs/ts/latest/tutorial/toh-pt2.jade
- public/docs/ts/latest/tutorial/toh-pt3.jade
- public/docs/ts/latest/tutorial/toh-pt4.jade
- public/docs/ts/latest/tutorial/toh-pt5.jade
- public/docs/ts/latest/tutorial/toh-pt6.jade
> docs(toh): update live example links

- public/docs/_examples/dependency-injection/dart/lib/providers_component.dart
- public/docs/_examples/dependency-injection/e2e-spec.ts
- public/docs/_examples/dependency-injection/ts/app/providers.component.ts
- public/docs/dart/latest/guide/dependency-injection.jade
- public/docs/ts/latest/guide/dependency-injection.jade
Minor edits:
- Dart side adjustments following #1594.
- Renamed example '3a' to just '3' and tweaked the logger message
- Removed obsolete Dart block.
TS and Dart DI e2e tests pass.
> docs(basics/di): minor edits following TS switch to provider object literal

- public/docs/_examples/toh-2/dart/lib/app_component.dart
- public/docs/_examples/toh-2/dart/web/main.dart
- public/docs/dart/latest/tutorial/toh-pt2.jade
> docs(toh-2/dart): copyedits

- public/docs/_examples/quickstart/dart/web/index.html
See https://github.com/dart-lang/www.dartlang.org/issues/1526.
> example(dart/quickstart): use <script defer> rather than async

- tools/api-builder/angular.io-package/index.js
These exports should not be part of the docs and
cause the doc-gen to fail.
Closes #1667
> api-builder: ignore additional platform browser private exports

- public/docs/_examples/toh-4/dart/lib/app_component.dart
- public/docs/_examples/toh-5/dart/lib/app_component.css
- public/docs/_examples/toh-5/dart/lib/app_component.dart
- public/docs/_examples/toh-5/dart/lib/app_component_1.dart
- public/docs/_examples/toh-5/dart/lib/app_component_2.dart
- public/docs/_examples/toh-5/dart/lib/dashboard_component.css
- public/docs/_examples/toh-5/dart/lib/dashboard_component.dart
- public/docs/_examples/toh-5/dart/lib/dashboard_component.html
- public/docs/_examples/toh-5/dart/lib/dashboard_component_2.dart
- public/docs/_examples/toh-5/dart/lib/hero_detail_component.dart
- public/docs/_examples/toh-5/dart/lib/hero_service.dart
- public/docs/_examples/toh-5/dart/lib/heroes_component.dart
- public/docs/_examples/toh-5/dart/lib/heroes_component.html
- public/docs/_examples/toh-5/dart/lib/mock_heroes.dart
- public/docs/_examples/toh-5/dart/web/index.html
- public/docs/_examples/toh-5/dart/web/main.dart
- public/docs/_examples/toh-5/dart/web/styles_1.css
- public/docs/dart/latest/tutorial/toh-pt5.jade
- public/docs/ts/latest/tutorial/toh-pt5.jade
- Adjust text which used to say "create a new 'styles.css'" when we've been carrying it around since QuickStart.
- The HTTP tutorial chapter is no longer "forthcoming".
- This commit also adds a missing docregion to a toh-4 file that is referrenced in toh-5.
- Fixed prose over indentation (which appeared in over half the file).
- Copyedits.
Code:
- Add missing return types.
- Handle invalid numeric route hero ids.
- Rename HERO mockHeroes as used in earlier tutorial chapters.
- Use Dartisms (cleanup from ts2dart transpilation).
Contributing to #1628.
> docs(toh-5/dart): review edits and code cleanup

- public/docs/_examples/toh-3/dart/lib/app_component.dart
- public/docs/_examples/toh-3/dart/lib/hero.dart
- public/docs/_examples/toh-3/dart/lib/hero_detail_component.dart
- public/docs/dart/latest/glossary.jade
- public/docs/dart/latest/tutorial/toh-pt1.jade
- public/docs/dart/latest/tutorial/toh-pt2.jade
- public/docs/dart/latest/tutorial/toh-pt3.jade
- public/docs/ts/latest/glossary.jade
- Copyedits made to glossary as well.
- Note that "Scoped Package" has been removed from the Dart glossary.
Contributing to #1628.
> docs(toh-3/dart): copyedits and new snake_case glossary entry

- public/docs/_examples/toh-4/dart/lib/app_component.dart
- public/docs/_examples/toh-4/dart/lib/app_component_1.dart
- public/docs/_examples/toh-4/dart/lib/hero_detail_component.dart
- public/docs/_examples/toh-4/dart/lib/hero_service.dart
- public/docs/_examples/toh-4/dart/lib/hero_service_1.dart
- public/docs/_examples/toh-4/dart/lib/mock_heroes.dart
- public/docs/_examples/toh-4/dart/web/main.dart
- public/docs/_examples/toh-4/dart/web/main_1.dart
- public/docs/dart/latest/tutorial/toh-pt4.jade
> docs(toh-4/dart): copyedits

- public/docs/_examples/architecture/dart/pubspec.yaml
- public/docs/_examples/attribute-directives/dart/pubspec.yaml
- public/docs/_examples/component-styles/dart/pubspec.yaml
- public/docs/_examples/dependency-injection/dart/pubspec.yaml
- public/docs/_examples/displaying-data/dart/pubspec.yaml
- public/docs/_examples/forms/dart/pubspec.yaml
- public/docs/_examples/hierarchical-dependency-injection/dart/pubspec.yaml
- public/docs/_examples/lifecycle-hooks/dart/pubspec.yaml
- public/docs/_examples/pipes/dart/pubspec.yaml
- public/docs/_examples/quickstart/dart/pubspec.yaml
- public/docs/_examples/server-communication/dart/pubspec.yaml
- public/docs/_examples/structural-directives/dart/pubspec.yaml
- public/docs/_examples/template-syntax/dart/pubspec.yaml
- public/docs/_examples/toh-1/dart/pubspec.yaml
- public/docs/_examples/toh-2/dart/pubspec.yaml
- public/docs/_examples/toh-3/dart/pubspec.yaml
- public/docs/_examples/toh-4/dart/pubspec.yaml
- public/docs/_examples/toh-5/dart/pubspec.yaml
- public/docs/_examples/user-input/dart/pubspec.yaml
Make all `pubspec.yaml` files consistent with the [stagehand](http://stagehand.pub/) `web-angular` default.
Fixes #1642.
> chore(dart pubspec.yaml): consistent baseline

- public/docs/_examples/_protractor/typings.json
- public/docs/_examples/quickstart/ts/typings.1.json
- public/docs/_examples/typings.json
- public/docs/_examples/webpack/ts/typings.1.json
Current typings were causing the following error:
```
[13:06:52] [13:06:52] E/launcher - Error: TSError: ⨯ Unable to compile TypeScript
typings\globals\node\index.d.ts (415,11): Interface 'NodeBuffer' incorrectly extends interface 'Uint8Array'.
Types of property 'fill' are incompatible.
```
/cc @Foxandxss
> fix(e2e): update broken node typings

- public/resources/js/directives/api-list.js
* Add a "Stable" filter on the api doc list which will only show api elements that have the `@stable` tag
* Live preview: https://filter-by-stable.firebaseapp.com/docs/ts/latest/api/#!?apiType=Stable
angular2 has yet to incorporate the `@stable` tag, as a result, we will not be merging this branch until some work is done on that end.
@naomiblack
> feat(filter stable): filter by stability stable

- public/docs/_examples/systemjs.config.plunker.js
New forms plunkers were broken because SystemJS config was trying to fetch them on the wrong version.
> fix(plunkers): fix form plunkers

- public/_includes/_util-fns.jade
- public/docs/_examples/toh-6/ts/app/app.component.css
- public/docs/_examples/toh-6/ts/app/hero-detail.component.html
- public/docs/_examples/toh-6/ts/app/hero-detail.component.ts
- public/docs/_examples/toh-6/ts/app/hero.service.ts
- public/docs/_examples/toh-6/ts/app/heroes.component.html
- public/docs/_examples/toh-6/ts/app/heroes.component.ts
- public/docs/_examples/toh-6/ts/app/in-memory-data.service.ts
- public/docs/_examples/toh-6/ts/sample.css
- public/docs/ts/latest/tutorial/toh-pt6.jade
Changes to prose:
- Complete TODO item of displaying `heroes.component` errors.
- Mainly copyedits.
- Add of `block` statements so that prose can be used on Dart side.
- Show excerpt and briefly explain of changes (previously missing):
- `app/hero-detail.component.html`
- `app/heroes.component.ts` error handling
- Add missing file to changed/added files listing and makeTabs
- `toh-6/ts/app/in-memory-data.service.ts,
- `toh-6/ts/sample.css`
Code changes:
- Mainly copyedits
- Renamed `heroes.component.ts` `delete` to `deleteHero` to match
naming of other methods
Contributes to #1628.
> docs(toh-6/ts): minor edits and enhancements

- .travis.yml
- script/install.sh
This PR makes it easier to get a local repo back into a sane state after a change in typings (something that a few of us have had some challenges with recently :). Specifically, this PR addresses two things.
(1) On June 18th, @filipesilva made the following comment on the docs-authoring slack channel:
> in regards to setup, if you're ever uncertain just check `travis.yml`. It's the definite resource
I agree with this approach of relying on the travis config file. Furthermore, I think that it should be easy to manually create a clean repo (when cloning afresh isn't an option). This PR puts the 5 travis install commands into a single script: `./script/install.sh`. Note that the `angular` team has a similarly named script that they also use for travis installs.
With this PR, one can get a …
> chore(install): put all install commands into a single script

- public/docs/_examples/dependency-injection/dart/lib/providers_component.dart
- public/docs/_examples/template-syntax/dart/lib/hero_detail_component.dart
- public/docs/_examples/toh-2/dart/lib/app_component.dart
- public/docs/_examples/toh-3/dart/lib/app_component.dart
Dart-side updates following #1654.
dependency-injection:
- Renamed components in providers_component.dart
- E2e suites passed:
- public/docs/_examples/dependency-injection/dart
- public/docs/_examples/dependency-injection/ts
template-syntax:
- Removed unused global variable.
- Suites passed:
public/docs/_examples/template-syntax/dart
public/docs/_examples/template-syntax/ts
toh-2 & 3:
- Clean-up
> docs(guide/{di, ts, toh-[23]}): follow-up to #1654

- public/docs/_examples/toh-6/dart/.docsync.json
- public/docs/_examples/toh-6/dart/lib/app_component.css
- public/docs/_examples/toh-6/dart/lib/app_component.dart
- public/docs/_examples/toh-6/dart/lib/dashboard_component.css
- public/docs/_examples/toh-6/dart/lib/dashboard_component.dart
- public/docs/_examples/toh-6/dart/lib/dashboard_component.html
- public/docs/_examples/toh-6/dart/lib/hero.dart
- public/docs/_examples/toh-6/dart/lib/hero_detail_component.css
- public/docs/_examples/toh-6/dart/lib/hero_detail_component.dart
- public/docs/_examples/toh-6/dart/lib/hero_detail_component.html
- public/docs/_examples/toh-6/dart/lib/hero_service.dart
- public/docs/_examples/toh-6/dart/lib/heroes_component.css
- public/docs/_examples/toh-6/dart/lib/heroes_component.dart
- public/docs/_examples/toh-6/dart/lib/heroes_component.html
- public/docs/_examples/toh-6/dart/lib/in_memory_data_service.dart
- public/docs/_examples/toh-6/dart/pubspec.yaml
- public/docs/_examples/toh-6/dart/web/index.html
- public/docs/_examples/toh-6/dart/web/main.dart
- public/docs/_examples/toh-6/dart/web/sample.css
- public/docs/dart/latest/tutorial/toh-pt6.jade
NOTE: this PR depends on #1686.
Dart prose and example match the TS counterpart except that:
- No child-to-parent event emission occurs.
- Support for Add Hero is added as an unconditional feature of the Heroes view.
- http `_post` takes only a name
- http `delete` takes only a hero id.
- The Dart in-memory-data-service has been dropped in favor of an
implementation based on the "standard" `http.testing.MockClient` class.
Fixes #1595.
> docs(toh-6/dart): first edition of prose and example code

- public/docs/_examples/lifecycle-hooks/dart/lib/after_content_component.dart
- public/docs/_examples/lifecycle-hooks/dart/lib/after_view_component.dart
- public/docs/_examples/lifecycle-hooks/dart/lib/counter_component.dart
- public/docs/_examples/lifecycle-hooks/dart/lib/spy_component.dart
- public/docs/_examples/lifecycle-hooks/dart/lib/spy_directive.dart
Dart-side updates following #1654:
- Updates to follow style guide
- Enabled e2e tests (#1523).
- Fixes to ensure tests pass: in after_view_component.dart and
after_content_component.dart
- Changed test over comment field in template to be:<br>
`*ngIf="comment.isNotEmpty"`
- Suites passed:
- public/docs/_examples/lifecycle-hooks/dart
- public/docs/_examples/lifecycle-hooks/ts
> docs(guide/lifecycle-hooks): follow-up to #1654

- public/docs/_examples/attribute-directives/dart/lib/highlight_directive.dart
- public/docs/_examples/attribute-directives/dart/lib/highlight_directive_2.dart
- public/docs/_examples/attribute-directives/ts/app/highlight.directive.2.ts
- public/docs/_examples/attribute-directives/ts/app/highlight.directive.ts
- public/docs/ts/latest/guide/attribute-directives.jade
Mainly Dart-side review, following #1654:
- Updated Dart code to match TS.
- Ran dartfmt.
- Enabled e2e tests (#1523); suites passed:
- public/docs/_examples/attribute-directives/dart
- public/docs/_examples/attribute-directives/ts
- Prose copyedits.
> docs(guide/attribute-directives): follow-up to #1654

- .travis.yml
- script/install.sh
This PR adds a new matrix entry to travis builds that runs docs e2e tests against the latest preview builds. It is meant to add early warning about possible breakage on next release, and to automatically be triggered on master via a webhook on Angular 2 builds (see https://github.com/angular/angular/issues/9322).
This new build is set to be allowed to fail, and a PR will not wait for it to be finished before being marked passing the CI.
> chore(travis): add preview builds

- public/docs/_examples/quickstart/dart/lib/app_component.dart
- public/docs/_examples/quickstart/dart/pubspec.yaml
- public/docs/_examples/quickstart/dart/web/main.dart
- public/docs/dart/latest/quickstart.jade
- public/docs/dart/latest/tutorial/toh-pt5.jade
- public/docs/dart/latest/tutorial/toh-pt6.jade
- public/docs/ts/latest/quickstart.jade
Changes:
- Renamed `angular2_getting_started` to `angular2_quickstart` (to match TS).
- s/-/_/g in project names elsewhere (only toh-5 & -6 needed to be updated).
Checks:
- Generated docs have not BAD FILENAME
- Ran Dart e2e tests; suites passed:
- public/docs/_examples/quickstart/dart
Fixes #378.
> docs(dart/{quickstart,toh-[56]}): fix project names

- public/docs/_examples/forms/ts/app/hero-form.component.ts
Fixed incorrect import. Tests didn't pick it up because importing the wrong `NgForm` was technically harmless in this case because the symbol was only used as a parameter type constraint.
Discovered by Kara.
> docs(forms): fix import in HeroFormsComponent - @angular/common -> @angular/forms

- firebase.json
Redirect old glossary to correct location within the guide folder. This addresses the problem with bad fragments for people who are still navigating here from an old link.
Difficult to test because no firebase redirects work with CheckDeploy. Need to at least have a test server.
> chore(glossary/ts): redirect old glossary to correct location

- public/docs/dart/latest/cheatsheet.jade
Until we can generate the cheat sheet properly, at least alert reader of possible inaccuracies.
> docs(cheatsheet/dart): alert reader of possible inaccuracies

- .travis.yml
- gulpfile.js
- package.json
- public/_includes/_hero.jade
- public/docs/_layout-dart-api.jade
- public/docs/dart/latest/api/index.jade
- public/resources/js/directives/api-list.js
- scripts/patch.sh
- tools/api-builder/dart-package/index.js
- tools/api-builder/dart-package/processors/loadDartDocData.js
- tools/api-builder/dart-package/processors/loadDartDocHtml.js
- tools/api-builder/dart-package/services/apiListDataFileService.js
- tools/api-builder/dart-package/services/arrayFromIterable.js
- tools/api-builder/dart-package/services/dartPkgConfigInfo.js
- tools/api-builder/dart-package/services/logFactory.js
- tools/api-builder/dart-package/services/preprocessDartDocData.js
- tools/api-builder/dart-package/test.js
- tools/dart-api-builder/dab.js
Fixes #1880, which has a detailed task breakdown.
Supersedes #1593.
Note about the API subsite design: I had to resort to using Jade extends/includes; hence disabling Harp _layout/partials.
cc: @naomiblack @kwalrath @ferhatb @keertip
> docs(api/dart): add support for generation and display

- public/docs/_examples/toh-1/ts/index.html
- public/docs/_examples/toh-2/ts/index.html
- public/docs/_examples/toh-4/dart/web/index.html
- public/docs/_examples/toh-4/ts/app/app.component.1.ts
Misc fixes to problems with the tutorial examples, as detected by the new e2e tests. Now the toh-4 index.html is identical to those of the previous parts.
Fixes #1609.
Supersedes #1785.
> examples(tutorial): misc fixes to issues from failed e2e

- public/docs/_examples/architecture/dart/pubspec.yaml
- public/docs/_examples/attribute-directives/dart/pubspec.yaml
- public/docs/_examples/component-styles/dart/pubspec.yaml
- public/docs/_examples/dependency-injection/dart/pubspec.yaml
- public/docs/_examples/displaying-data/dart/pubspec.yaml
- public/docs/_examples/forms/dart/pubspec.yaml
- public/docs/_examples/hierarchical-dependency-injection/dart/pubspec.yaml
- public/docs/_examples/lifecycle-hooks/dart/pubspec.yaml
- public/docs/_examples/pipes/dart/lib/exponential_strength_pipe.dart
- public/docs/_examples/pipes/dart/lib/fetch_json_pipe.dart
- public/docs/_examples/pipes/dart/lib/flying_heroes_component.html
- public/docs/_examples/pipes/dart/lib/flying_heroes_pipe.dart
- public/docs/_examples/pipes/dart/lib/hero_list_component.dart
- public/docs/_examples/pipes/dart/pubspec.yaml
- public/docs/_examples/quickstart/dart/pubspec.yaml
- public/docs/_examples/server-communication/dart/pubspec.yaml
- public/docs/_examples/structural-directives/dart/pubspec.yaml
- public/docs/_examples/template-syntax/dart/pubspec.yaml
- public/docs/_examples/toh-1/dart/pubspec.yaml
- public/docs/_examples/toh-2/dart-snippets/app_component_snippets_pt2.dart
- public/docs/_examples/toh-2/dart/pubspec.yaml
- public/docs/_examples/toh-3/dart/pubspec.yaml
- public/docs/_examples/toh-4/dart/pubspec.yaml
- public/docs/_examples/toh-5/dart/pubspec.yaml
- public/docs/_examples/toh-6/dart/pubspec.yaml
- public/docs/_examples/user-input/dart/pubspec.yaml
- public/docs/dart/latest/_data.json
- public/docs/dart/latest/quickstart.jade
- pubspec.yaml
Update made to all `pubspec.yaml` files and to relevant prose.
Note that pipes was back a beta.15; the rest were at beta.17.
Updates to pipe example source code:
- Pipe `transform()` method parameters
- `ngFor` microsyntax, from `#` to `let`
Suites passed:
- public/docs/_examples/architecture/dart
- public/docs/_examples/attribute-directives/dart
- public/docs/_examples/dependency-injection/dart
- public/docs/_examples/displaying-data/dart
- public/docs/_examples/forms/dart
- public/docs/_examples/lifecycle-hooks/dart
- public/docs/_examples/quickstart/dart
- public/docs/_examples/server-communication/dart
- public/docs/_examples/template-syntax/dart
- public/docs/_examples/toh-1/dart
- public/docs/_examples/toh-2/dart
- public/docs/_examples/toh-3/dart
- public/docs/_examples/toh-4/dart …
> chore(ng2/dart): update from beta.1x to beta.18

- public/docs/_examples/toh-1/e2e-spec.ts
> tests(toh-1/e2e): cleanup and updates incl. use of async/await

- tools/api-builder/angular.io-package/templates/layout/_how-to-use.html
- tools/api-builder/angular.io-package/templates/layout/_what-it-does.html
* Hide "How To Use" and "What It Does" whenever no notes are found.
* https://github.com/angular/angular.io/issues/1963
@naomiblack
> hide notes if none are found

- public/docs/_examples/toh-5/ts/app/app.component.1.ts
For some reason there is a breaking change in TsLint that broke our build. Even with the rule disable, it would still fail.
The reality is that we don't need that `For testing only` line, is outside regions and e2e pass with normality.
I will debug the tslint issue on my own and report it.
> chore: fix linting

- gulpfile.js
Currently two entries are generated for top-level library members like classes, and the main API page for these members has no-so-useful breadcrumbs. E.g., the main API page for `PipeMetadata` has breadcrumb: `angular2 > angular2 > PipeMetadata`, vs. the proper breadcrumb `angular2 > angular2.core > PipeMetadata` that appears on the second copy of the API page entry.
TLDR; within the `angular2` package there is a top-level catch-all library of the same name the exports most of the contained libraries. This results in duplicate API page entries (one for `angular2.foo` and one for `angular2.some_sub_lib_id.foo`). Furthermore, all internal page links to `foo` go to `angualr2.foo` so we loose breadcrumb information. This commit fixes the issue by hiding the top-level `angular2` library …
> docs(api/dart): avoid duplicate entries and fix breadcrumbs

- public/docs/_examples/toh-6/dart/lib/dashboard_component.dart
- public/docs/_examples/toh-6/dart/lib/dashboard_component.html
- public/docs/_examples/toh-6/dart/lib/hero_search_component.css
- public/docs/_examples/toh-6/dart/lib/hero_search_component.dart
- public/docs/_examples/toh-6/dart/lib/hero_search_component.html
- public/docs/_examples/toh-6/dart/lib/hero_search_service.dart
- public/docs/_examples/toh-6/dart/lib/heroes_component.css
- public/docs/_examples/toh-6/dart/lib/in_memory_data_service.dart
- public/docs/_examples/toh-6/dart/pubspec.yaml
- public/docs/_examples/toh-6/dart/web/index.html
- public/docs/_examples/toh-6/dart/web/sample.css
- public/docs/_examples/toh-6/ts/app/dashboard.component.ts
- public/docs/_examples/toh-6/ts/app/hero-search.component.ts
- public/docs/dart/latest/tutorial/toh-pt6.jade
- public/docs/ts/latest/tutorial/toh-pt6.jade
TS minor edits:
- @wardbell @Foxandxss : as usual, [TS side edits are best viewed by **ignoring whitespace**](https://github.com/angular/angular.io/commit/94d432d4740fe58205aacd009549b3cb3af873e1?w=1).
Dart update:
- @kwalrath @thso: fixes #1924.
Note: in anticipation of #1751, `sample.css` has been eliminated from the Dart example.
> docs(toh-6): add hero search to Dart; minor edits to TS

- public/docs/dart/latest/glossary.jade
- public/docs/dart/latest/guide/_data.json
- public/docs/dart/latest/guide/forms-deprecated.jade
- public/docs/dart/latest/guide/glossary.jade
- public/docs/dart/latest/guide/router-deprecated.jade
- Fixes #1918.
- Also fixes wording in `dart/latest/guide/*-deprecated.jade` files as suggested by @kwalrath.
- Follow-up glossary work will be done under #2036.
> docs(glossary/dart): recover content

- public/docs/dart/latest/tutorial/toh-pt3.jade
- public/docs/ts/latest/cookbook/set-document-title.jade
- tools/api-builder/angular.io-package/index.js
@naomiblack & @IgorMinar I think this should solve the problem. Shall we change the processor so that it takes a regexp instead so that we don't have to keep adding these?
Closes #2024
> doc-gen: ignore new private module

- public/docs/_examples/component-styles/dart/.docsync.json
- public/docs/_examples/lifecycle-hooks/dart/.docsync.json
Note that component-styles and lifecycle-hooks examples have been sync’d for a while, though they were missing `.docsync.json` files.
cc @kwalrath
> chore(dart-doc-sync): data files for component-styles and lifecycle-hooks

- public/docs/_examples/toh-6/dart/web/main.dart
> docs(toh-6): show provider to use with a real back end

- public/docs/dart/latest/tutorial/toh-pt5.jade
Remove an import statement as the package is already imported at this stage of the tutorial.
> docs(toh-pt5/dart): remove an already existing line

- public/docs/_examples/pipes/e2e-spec.ts
Let's get Travis green again. I haven't been able to get the failing pipes test to pass, so this disables the two problematic tests until we can fix them.
cc @wardbell @Foxandxss @filipesilva
> chore(pipes): disable two broken e2e tests

- gulpfile.js
- tools/api-builder/dart-package/test.js
- tools/dart-api-builder/dab.js
- #2049, support ng.io doc relative links and code-regions
- Change dartdoc output folder to `docs/api` (from `doc/api`).
> chore(dart): api doc builder enhancements

- public/docs/_examples/template-syntax/dart/lib/app_component.dart
- public/docs/_examples/template-syntax/dart/lib/app_component.html
Enhancements to `NgStyle` section in support of its API docs.
- Add feature supporting interactive update of a paragraph’s style.
- Add full type declarations.
- Replace bogus implementation of `getStyles()`.
> docs(template-syntax/dart): enhancements to example code

- public/docs/ts/_cache/guide/hierarchical-dependency-injection.jade
- public/docs/ts/latest/guide/hierarchical-dependency-injection.jade
Contributes to #2077.
Depends on #2078.
> docs(hierarchical-di): post-RC5 Dart resync

- scripts/before-install.sh
- scripts/env-info-and-check.sh
- scripts/env-set.sh
Fix a few minor problems with Travis install & build scripts.
Other changes allow `before-install.sh` to be run locally.
> chore(install): fix install scripts & improve local usage

- public/_includes/_util-fns.jade
- public/docs/ts/latest/guide/router.jade
- Fixed two instances of markdown text not under `:marked` region (and so that text was not showing up in the generated html including the heading "Router Lifecycle Hooks").
- Fixed: code excerpt title `constructor` -> `isSelected`.
- Cleanup of all makeExample mixin uses.
Preliminary step to #2035: this cleanup will help make it easier to record differences with the deprecated router chapter (which must have app-relative makeExample paths).
> docs(router): fix markdown, and example mixin cleanup

- public/docs/_examples/toh-5/e2e-spec.ts
Improved test coverage. Also updated tests to make use of async/await (so tests are more readable).
This is part of work to get a full suite of e2e tutorial tests to run for Dart (#1619).
> chore(toh-5): improve e2e test coverage and readability (use async/await)

- gulpfile.js
Using `--fast` with most targets would just stop after doing `_copy-example-boilerplate`. This fixes the issue.
cc @kwalrath @Foxandxss
> chore(build): fix so --fast can be used with check-deploy etc

- public/docs/dart/latest/glossary.jade
- public/docs/dart/latest/guide/glossary.jade
- public/docs/js/latest/glossary.jade
- public/docs/js/latest/guide/glossary.jade
- public/docs/ts/_cache/glossary.jade
- public/docs/ts/latest/glossary.jade
- public/docs/ts/latest/guide/glossary.jade
This commit addresses issues with the glossary for all languages (JS, TS, Dart).
Fixes #1123, #1838, #2036.
Contributes to #1508.
This was originally started as post-RC5 Dart resync, but since mixing Harp partials with Jade mixins can be problematic, this commit does a general cleanup of the 3 x 2 = 6 glossary files (found in `{ts,js,dart}/latest/{.,guide}`).
This commit builds upon #2098 (which created the first `ts/_cache` copy of the glossary), but doesn't really depend on it.
> docs(glossary): general cleanup and fix links

- public/docs/_examples/architecture/dart/pubspec.yaml
- public/docs/_examples/attribute-directives/dart/pubspec.yaml
- public/docs/_examples/component-styles/dart/pubspec.yaml
- public/docs/_examples/dependency-injection/dart/pubspec.yaml
- public/docs/_examples/displaying-data/dart/pubspec.yaml
- public/docs/_examples/forms/dart/pubspec.yaml
- public/docs/_examples/hierarchical-dependency-injection/dart/pubspec.yaml
- public/docs/_examples/lifecycle-hooks/dart/pubspec.yaml
- public/docs/_examples/pipes/dart/pubspec.yaml
- public/docs/_examples/quickstart/dart/pubspec.yaml
- public/docs/_examples/server-communication/dart/pubspec.yaml
- public/docs/_examples/structural-directives/dart/pubspec.yaml
- public/docs/_examples/template-syntax/dart/pubspec.yaml
- public/docs/_examples/toh-1/dart/pubspec.yaml
- public/docs/_examples/toh-2/dart/pubspec.yaml
- public/docs/_examples/toh-3/dart/pubspec.yaml
- public/docs/_examples/toh-4/dart/pubspec.yaml
- public/docs/_examples/toh-5/dart/pubspec.yaml
- public/docs/_examples/toh-6/dart/pubspec.yaml
- public/docs/_examples/user-input/dart/pubspec.yaml
- public/docs/dart/latest/_data.json
- public/docs/dart/latest/quickstart.jade
- pubspec.yaml
All currently active E2E tests pass except for lifecycle-hooks which fails because of recent updates to that test file (it is fixed in #2141):
```
Suites passed:
public/docs/_examples/architecture/dart
public/docs/_examples/attribute-directives/dart
public/docs/_examples/dependency-injection/dart
public/docs/_examples/displaying-data/dart
public/docs/_examples/forms/dart
public/docs/_examples/pipes/dart
public/docs/_examples/quickstart/dart
public/docs/_examples/server-communication/dart
public/docs/_examples/template-syntax/dart
public/docs/_examples/toh-1/dart
public/docs/_examples/toh-2/dart
public/docs/_examples/toh-3/dart
public/docs/_examples/toh-4/dart
public/docs/_examples/toh-5/dart
public/docs/_examples/user-input/dart
Suites failed:
public/docs/_examples/lifecycle-hooks/dart …
```
> docs(dart): upgrade to beta.20

- public/docs/_examples/lifecycle-hooks/dart/lib/after_view_component.dart
- public/docs/_examples/lifecycle-hooks/dart/lib/do_check_component.dart
- public/docs/_examples/lifecycle-hooks/dart/lib/do_check_parent_component.html
- public/docs/_examples/lifecycle-hooks/dart/web/main.dart
- public/docs/_examples/lifecycle-hooks/ts/app/main.ts
- public/docs/_examples/lifecycle-hooks/ts/app/on-changes-parent.component.html
- public/docs/dart/latest/guide/lifecycle-hooks.jade
- public/docs/ts/_cache/guide/lifecycle-hooks.jade
- public/docs/ts/latest/guide/lifecycle-hooks.jade
- TS prose: removed mention of `routerOnActivate` which no longer exists in the new router.
- TS improvements to the sample code have also been propagated to the Dart sample.
Contributes to #2077.
E2E tests for lifecycle-hooks pass now.
> docs(lifecycle-hooks): post-RC5 Dart resync

- gulpfile.js
This flag (on by default) determines if `pub {upgrade,build}` is run
before launching e2e tests. It is useful to be able to disable when
tweaking the e2e tests themselves.
cc @kwalrath @Foxandxss
> chore(dart e2e): add --[no-]pub flag

- gulpfile.js
Remove dartdoc `—add-crossdart` flag.
cc @kwalrath
> chore(dartdoc): don't cross link to sources

- public/docs/dart/latest/guide/user-input.jade
- public/docs/ts/latest/guide/user-input.jade
> docs(user-input): add link to Dart sample

- public/docs/dart/latest/guide/forms.jade
- public/docs/dart/latest/guide/user-input.jade
- public/docs/ts/latest/guide/forms.jade
- public/docs/ts/latest/guide/user-input.jade
Contributes to #1598.
Also:
- Trimmed trailing whitespace -- view changes [ignoring whitespace](2176/files?w=1).
- Fixing user-input (since we don’t need the “Run the” in the link).
> docs(forms): add link to Dart sample

- gulpfile.js
- tools/api-builder/dart-package/test.js
- angular2 dartdoc files will be in `doc/api`
- angular2 site examples will be in `example`
> chore(api): Dart API source folders renamed

- public/docs/dart/latest/guide/dependency-injection.jade
- public/docs/dart/latest/guide/forms.jade
- public/docs/ts/_cache/guide/dependency-injection.jade
- public/docs/ts/_cache/guide/template-syntax.jade
- public/docs/ts/latest/guide/dependency-injection.jade
- public/docs/ts/latest/guide/template-syntax.jade
> docs(*): fix links to Dart API entries

- public/_includes/_hero.jade
- public/_includes/_version-dropdown.jade
- Re-enable dropdown on main API page.
- Remove Dart choice from TS & JS API entry pages dropdown.
Contributes to #2173.
> docs(api): fix cross-language dropdown menu

- public/docs/_examples/ngmodule/ts/app/hero/hero.module.3.ts
- public/docs/_examples/ngmodule/ts/app/hero/hero.module.ts
- public/docs/_examples/ngmodule/ts/contact.1b.plnkr.json
- public/docs/_examples/ngmodule/ts/contact.2.plnkr.json
- public/docs/_examples/ngmodule/ts/plnkr.json
- public/docs/_examples/ngmodule/ts/pre-shared.3.plnkr.json
- public/docs/_examples/systemjs.config.plunker.build.js
- public/docs/dart/latest/cookbook/_data.json
- public/docs/dart/latest/cookbook/ngmodule-faq.jade
- public/docs/js/latest/cookbook/_data.json
- public/docs/js/latest/cookbook/ngmodule-faq.jade
- public/docs/ts/latest/cookbook/_data.json
- public/docs/ts/latest/cookbook/ngmodule-faq.jade
- public/docs/ts/latest/guide/ngmodule.jade
includes splitting FAQs into its own cookbook.
> docs(ngmodule): fixes for defects discovered by John Papa

- public/resources/js/directives/live-example.js
- tools/plunker-builder/builder.js
This makes embedded plunkers to work in any condition.
> chore: add _self target to embedded plunkers

- public/docs/ts/latest/guide/index.jade
> docs(overview): fix live-example link

- public/docs/_examples/server-communication/ts/app/wiki/wikipedia.service.1.ts
- public/docs/_examples/server-communication/ts/app/wiki/wikipedia.service.ts
Clearly we're transforming the response, not the request.
> docs(server-communication): Fix typo in example

- public/docs/_examples/ngmodule/ts/app/core/core.module.ts
because BaseException removed from A2 public api
> chore: replace BaseException with new Error

- public/docs/_examples/ngmodule/ts/app/app.routing.3.ts
- public/docs/_examples/ngmodule/ts/app/app.routing.ts
- public/docs/_examples/ngmodule/ts/app/crisis/crisis.module.ts
- public/docs/_examples/ngmodule/ts/app/hero/hero.module.3.ts
- public/docs/_examples/ngmodule/ts/app/hero/hero.module.ts
- public/docs/ts/latest/guide/ngmodule.jade
Because AoT won't support `export default` for RC6.
> docs(ngmodule): replace `export default` with explicit export

- scripts/install-dart-sdk.sh
Because dartdoc from 1.19.0 has issues; see https://github.com/dart-lang/dartdoc/issues/1233.
cc @wardbell @kwalrath
> chore(travis): anchor Dart SDK version to 1.18.1

- public/docs/_examples/toh-4/dart/lib/hero_service.dart
- public/docs/_examples/toh-4/dart/lib/hero_service_1.dart
- public/docs/_examples/toh-4/ts/app/hero.service.1.ts
- public/docs/_examples/toh-4/ts/app/hero.service.ts
- public/docs/_examples/toh-5/dart/lib/hero_service.dart
- public/docs/_examples/toh-5/ts/app/hero.service.ts
Have `getHeroesSlowly()` delay and then return the value of `getHeroes()`. This makes it easier for user’s performing the tutorial to keep this slower method as they evolve toh-5 into toh-6.
@kwalrath @Foxandxss @filipesilva : note that I've partitioned the files. There is a TS commit and a Dart commit, each ready to be reviewed.
> example(toh-4,5): getHeroesSlowly() to return getHeroes()

- public/docs/_examples/toh-6/dart/lib/hero_detail_component.dart
- public/docs/_examples/toh-6/dart/lib/hero_detail_component.html
- public/docs/_examples/toh-6/dart/lib/hero_service.dart
- public/docs/_examples/toh-6/dart/lib/heroes_component.css
- public/docs/_examples/toh-6/dart/lib/heroes_component.dart
- public/docs/_examples/toh-6/dart/lib/heroes_component.html
- public/docs/_examples/toh-6/dart/lib/in_memory_data_service.dart
- public/docs/_examples/toh-6/dart/web/main.dart
- public/docs/_examples/toh-6/e2e-spec.ts
- public/docs/_examples/toh-6/ts/app/app.component.ts
- public/docs/_examples/toh-6/ts/app/app.module.ts
- public/docs/_examples/toh-6/ts/app/hero-detail.component.html
- public/docs/_examples/toh-6/ts/app/hero-detail.component.ts
- public/docs/_examples/toh-6/ts/app/hero.service.ts
- public/docs/_examples/toh-6/ts/app/heroes.component.css
- public/docs/_examples/toh-6/ts/app/heroes.component.html
- public/docs/_examples/toh-6/ts/app/heroes.component.ts
- public/docs/dart/latest/tutorial/_data.json
- public/docs/dart/latest/tutorial/toh-pt6.jade
- public/docs/js/latest/tutorial/_data.json
- public/docs/ts/_cache/tutorial/toh-pt6.jade
- public/docs/ts/latest/tutorial/_data.json
- public/docs/ts/latest/tutorial/toh-pt6.jade
Refactoring of "add, edit, delete heroes" section of toh-6 from one big bottom-up step into small independent feature slices, where the user achieves a "milesone" (i.e., can run the full app) after each feature section. The section rewrite is shorter and offers a better UX.
Other simplifications:
- Error handling is consistent: in the hero service we log to the console, everwhere else we just let errors bubble up.
- Hero service methods renamed based on function (create, update) rather then lower-level implementation (post, put).
- `@Output` properties have been eliminated (since they weren't explained).
E2E tests now pass on both the TS and Dart sides.
Contributes to #1619.
> docs(toh-6): refactoring of 'add, edit, delete heroes'

- .gitignore
- gulpfile.js
If the site has already been built once, then rebuild the site without re-harp-compiling the API docs use:
```
gulp check-deploy --lang=''
```
Otherwise specify the languages whose API docs are to be rebuilt; as usual, omitting the `--lang` flag is equivalent to `--lang=all` which is equivalent to `--lang=‘ts|js|dart’`.
Other changes to gulp tasks:
- Renamed `serve` to `harp-serve`.
- Removed `check-serve`. Use `harp-compile` followed by `serve-www’ instead.
- `harp-compile` now also defaults to `--lang=all`.
> chore(site): support site build w/o recompiling API docs

- public/docs/ts/_cache/tutorial/toh-pt5.jade
> chore(toh-5): refresh cache file

- public/docs/ts/_cache/quickstart.jade
- public/docs/ts/latest/quickstart.jade
Tweak prose so that `AppModule` shows up as `AppComponent` in Dart.
cc @kwalrath
> docs(quickstart): adjust recent change for Dart

- public/docs/_examples/quickstart/ts/systemjs.config.1.js
- public/docs/_examples/systemjs.config.js
- public/docs/_examples/systemjs.config.plunker.build.js
- public/docs/_examples/systemjs.config.plunker.js
They belong in the testing shim files
> chore: remove testing libs from systemjs.config

- public/docs/_examples/webpack/ts/config/webpack.prod.js
Issue https://github.com/angular/angular/issues/10618 recommends 'mangle: { keep_fnames: true, screw_ie8: true } for the webpack UglifyJs plugin
> since RC5 the webpack prod build is defect

- public/resources/css/module/_style-guide.scss
blue = consider
red = avoid
light gray = why
Addressing the point raised here ... https://github.com/angular/angular.io/issues/1958
Docs team discussed and agree that Green is best for Do, and Red for avoid. We'll keep the neutral blue for consider.
we decided not to use shades of colors as some folks (like me) have difficulty discerning shades.
cc @wardbell @Foxandxss
> green = do

- gulpfile.js
Followup to https://github.com/angular/angular.io/pull/1700
Some authors are still experiencing performance issues with a very high CPU utilization. This PR adds the `--focus` to `gulp serve-and-sync-devguide`, which works as follows:
```
// When using the --focus=name flag, only **/name/**/*.* example files and
// **/name.jade files are watched. This is useful for performance reasons.
// Example: gulp serve-and-sync --focus=architecture 
```
> chore(gulp): add focus flag

- public/docs/ts/latest/quickstart.jade
- Remove accidental space causing URL to be rendered incorrectly
This fixes https://github.com/angular/angular/issues/11267
> fix(quickstart): remove accidental space

- public/docs/ts/latest/tutorial/toh-pt5.jade
- public/docs/ts/latest/tutorial/toh-pt6.jade
fixes #2231
also addresses `<h1>` issue raised in PR #2256
> docs(toh-6): missing create instruction

- public/docs/ts/latest/guide/typescript-configuration.jade
> docs(typescript): fix broken link

- public/docs/ts/latest/quickstart.jade
Quickstart tells you to create a `app/app.module.ts` and then later it instructs you on creating the `app` folder (as reported in #2260).
I believe that we don't need the instruction on creating that folder since we are giving clear instructions in where those new files should belong.
Fixes #2260
> docs(quickstart): remove instruction

- public/_includes/_util-fns.jade
- public/docs/ts/latest/cookbook/component-communication.jade
- public/docs/ts/latest/cookbook/visual-studio-2015.jade
- public/docs/ts/latest/guide/server-communication.jade
- public/docs/ts/latest/guide/webpack.jade
- public/docs/ts/latest/quickstart.jade
Fixes to prose “syntax”. Anomalies detected by jade2ng.
Also updated the main _util-fn.jade in support of jade2ng as well.
> docs(*): misc fixes to prose in support of jade2ng

- gulpfile.js
Just do a full build if no API docs currently exist rather than building the site and then aborting with an error message at the end of it all.
> chore: improve UX of build w/o API

- public/docs/ts/latest/glossary.jade
- public/docs/ts/latest/guide/router-deprecated.jade
- public/docs/ts/latest/guide/router.jade
- Glossary: `#ecmascript=2015` is not a valid fragment.
- Router: `<a name=“…”>` needed to be `<a id=“…”>`.
@kwalrath 
cc @ericjim
> docs(*): fix broken links in glossary and router chapter

- public/docs/ts/latest/guide/cheatsheet.jade
The page `docs/ts/latest/guide/cheatsheet.html` is a mirror of `docs/ts/latest/cheatsheet.html`. Use Jade instead of Harp to create the mirror.
cc @kwalrath - note that this has no visible effect on the generated page.
> chore(cheatsheet): use Jade to generate mirror page

- public/docs/dart/latest/_data.json
- public/docs/dart/latest/cheatsheet.jade
- public/docs/dart/latest/guide/_data.json
- public/docs/dart/latest/guide/cheatsheet.jade
- public/docs/js/latest/_data.json
- public/docs/js/latest/cheatsheet.jade
- public/docs/js/latest/guide/_data.json
- public/docs/js/latest/guide/cheatsheet.jade
- public/docs/ts/latest/_data.json
- public/docs/ts/latest/cheatsheet.jade
- public/docs/ts/latest/guide/_data.json
Each page is designed to have a single banner; adjust the cheatsheet to follow this convention. Also eliminate the article nested within the `l-conent` div.
Propagated changes/cleanup to JS and Dart.
@kwalrath, cc @ericjim
> chore(cheatsheet): fix double banner issue

- public/docs/dart/latest/guide/browser-support.jade
- public/docs/js/latest/guide/browser-support.jade
- public/docs/ts/latest/guide/_data.json
- public/docs/ts/latest/guide/browser-support.jade
This is a first try at documenting browser support an polyfills.
The content needs to be reviewed and validated.
/cc @wardbell @IgorMinar @naomiblack
> docs(browser-support): document browser support and polyfills

- tools/api-builder/angular.io-package/templates/api-list-audit.template.html
- tools/api-builder/angular.io-package/templates/api-list-data.template.html
Fixes #2321 
@naomiblack and @IgorMinar
> fix(api-builder): escape double-quotes in JSON output

- gulpfile.js
Currently, running ` gulp build-compile --dgeni-log=error --lang=''` with no previously full (all langs) build will result in these errors:
```
[17:52:57] Error: ENOENT: no such file or directory, stat 'D:\work\angular.io\www-backup\docs\ts\latest\api'
[17:52:57] Error: ENOENT: no such file or directory, stat 'D:\work\angular.io\www-backup\docs\js\latest\api'
[17:52:57] Error: ENOENT: no such file or directory, stat 'D:\work\angular.io\www-backup\docs\dart\latest\api'
```
This PR fixes that behaviour. This is especially relevant for setups where a full build is never created.
/cc @chalin
> fix(build-compile): allow skipping langs in a fresh build

- scripts/install-dart-sdk.sh
Dartdoc has been fixed and can now generate the API docs for angular2, so we no longer need to be pinned to SDK v1.18.1.
cc @kwalrath
> chore(travis): use latest Dart SDK

- public/docs/_examples/animations/e2e-spec.ts
- public/docs/_examples/animations/ts/app/hero-list-multistep.component.ts
- public/docs/ts/latest/guide/animations.jade
I used `console.warn` to log the callbacks (which is what protractor can read by default) and filter all the messages to see if there is any from those callbacks. I haven't found a smarter way for this use case.
> docs(animation): add callbacks documentation

- public/docs/_examples/quickstart/ts/package.1.json
This seems to confuse people and we are actually not using it.
I know we are going to use it in the future for AoT but we can either bring it back when TS 2 is here (so new users don't get a lot of warnings) or just add the instructions to add it on the AoT cookbook.
> docs(quickstart): remove compiler-cli from dependencies

- tslint.json
the directive ones are incomplete so it breaks easily.
The host, we don't agree on that rule anymore so we are going to remove it.
This makes Travis green again.
> chore: update tslint rules

- .travis.yml
- scripts/deploy-install.sh
Currently our build-compile task fails against 2.0.0 because of an API docs building issue. It has since been fixed in https://github.com/angular/angular/pull/11619 but not included in 2.0.0.
This PR allows our setup to use a SHA instead of a tag to specify the latest release we should test against, and sets the SHA to that of the PR that fixes our issue.
/cc @IgorMinar @naomiblack @chalin
> chore: fix api docs issue on angular 2.0.0

- public/docs/ts/latest/guide/style-guide.jade
A fix necessary for ng2.io
cc @kwalrath @Foxandxss @ericjim
> docs(style-guide): attributes aren't comma separated

- package.json
@filipesilva's harp patch was just merged so we can start using the official pre-release again (as we had tried to do in #2301, but were forced to revert in #2308).
cc @naomiblack
> chore(harp): use official pre-release 0.21 of harp

- public/news.jade
It may be a bit outdated but the url of the RC7 announcement link was not correct.
> docs(news): Fix RC7 announcement link

- public/docs/_examples/forms/js/app/hero-form.component.js
Fix Unmatched '{' JavaScript syntax error in hero-form.component.js example
> docs(devguide): fix syntax error in hero-form.component.js

- public/docs/_examples/webpack/ts/config/karma-test-shim.js
This matches what the CLI does.
Fixes #2317
> docs(webpack): move to core-js in testing

- public/docs/js/latest/guide/forms.jade
chapter is gone here too.
Fixes #2344
> docs(forms): remove deprecated forms notice for js

- public/docs/dart/latest/_data.json
- public/docs/js/latest/_data.json
- public/docs/ts/latest/_data.json
Angular 2.0.0 is out so also cleaned up:
- Removed "Angular is a candidate release".
- Changed "API Preview" to "API Reference"
Fixes #2384.
Fixes #2385.
Contributes to #2407.
> docs: fix {ts,dart,js}/latest/_data.json

- public/docs/ts/latest/guide/index.jade
> docs(overview): update to new organization

- public/docs/dart/latest/cookbook/aot-compiler.jade
- public/docs/js/latest/cookbook/aot-compiler.jade
- public/docs/js/latest/cookbook/index.jade
- public/docs/ts/latest/cookbook/index.jade
Also added missing cookbook AoT chapter placeholders for JS and Dart, fixing 404s mentioned in #2389.
> docs(cookbook): don't use shredder on intro page

- public/docs/ts/latest/guide/testing.jade
Also converts all `a#` to just `#` for no other reason than that it's "cooler" Jade syntax
> docs(testing): explain rationale for stubbed routerLink tests

- public/docs/ts/latest/guide/animations.jade
Copy edits for the Animations page.
> docs(animations): update copy

- tools/plunker-builder/indexHtmlTranslator.js
zone 0.6.23 is making conflicts with plunker and it is generating some weird side effects (opening a plunker run window in a new tab).
> chore: fix zone.js for plunkers

- public/docs/dart/latest/guide/user-input.jade
- Remove nonexistent `<important>` element since it causes problems for ng2.io. This is probably a typo. It was more likely meant to be an anchor name than an element name.
- Fix two PENDING links.
cc @ericjim
> docs(user-input): misc fixes

- public/docs/ts/latest/guide/typescript-configuration.jade
I believe name of the typings config file is typings.json, not typings.config.
> docs(typescript): Fix name of typings config file

- public/docs/ts/latest/guide/testing.jade
When the testing page is rendered using Jade, the following warning is generated:
```
Transformers.markdown is deprecated, you must replace the :markdown
jade filter, with :marked and install jstransformer-marked before you
update to jade@2.0.0.
```
This fixes the issue.
cc @wardbell @ericjim
> docs(testing): use marked Jade filter rather than deprecated markdown

- public/resources/css/module/_side-nav.scss
Fixes: https://github.com/angular/angular.io/issues/2408
cc @chalin
> fix: boost transparency of sidenav

- public/resources/css/module/_footer.scss
Footer logo was overflowing at ~960px wide viewport. Added `background-size: contain` (shorthand), and `max-width: 100%` to contain wrapper, and background image within grid.
> fix(footer): Footer logo is overflowing

- public/docs/_examples/testing/ts/app/banner.component.spec.ts
- public/docs/_examples/testing/ts/app/shared/title-case.pipe.spec.ts
- public/docs/_examples/testing/ts/app/shared/twain.component.spec.ts
- public/docs/_examples/testing/ts/app/welcome.component.spec.ts
- public/docs/dart/latest/cookbook/_data.json
- public/docs/dart/latest/guide/_data.json
- public/docs/js/latest/cookbook/_data.json
- public/docs/js/latest/guide/_data.json
- public/docs/ts/latest/cookbook/_data.json
- public/docs/ts/latest/guide/_data.json
- public/docs/ts/latest/guide/testing.jade
- public/resources/css/module/_footer.scss
Part 1 of incorporating Igor's feedback.
> docs(testing): from Igor Minar feedback (Part 1)

- public/docs/ts/latest/guide/_data.json
- public/docs/ts/latest/guide/displaying-data.jade
Copy edits in guide/_data.json and displaying-data.jade.
> docs(Displaying Data): copy edits

- gulpfile.js
- public/docs/_examples/upgrade-phonecat-2-hybrid/ts/example-config.json
- public/docs/_examples/upgrade-phonecat-3-final/ts/example-config.json
For those examples that needs testing, this PR adds the ability to add a _flag_ into the `example-config.json` for copying the testing boilerplate.
> chore: ability to add unit test boilerplate

- public/docs/_examples/lifecycle-hooks/ts/app/peek-a-boo.component.ts
- public/docs/ts/latest/guide/lifecycle-hooks.jade
Per Ben Lesh suggestion. Also converts away from "we"
> docs(lifecycle-hooks): make it easier to get to call sequence

- public/docs/js/latest/guide/_data.json
- public/docs/js/latest/guide/index.jade
- public/docs/ts/latest/guide/index.jade
replay Patrice's PR #2448 which I deleted by accident
> docs(js/guide): don't use shredder & _data.json fixes

- public/docs/_examples/cb-dependency-injection/ts/app/app.module.ts
- public/docs/_examples/package.json
- public/docs/_examples/quickstart/ts/systemjs.config.1.js
- public/docs/_examples/server-communication/ts/app/app.module.ts
- public/docs/_examples/server-communication/ts/app/hero-data.ts
- public/docs/_examples/server-communication/ts/app/toh/hero.service.ts
- public/docs/_examples/style-guide/ts/app/main.ts
- public/docs/_examples/systemjs.config.js
- public/docs/_examples/systemjs.config.plunker.build.js
- public/docs/_examples/systemjs.config.plunker.js
- public/docs/_examples/toh-6/ts/app/app.module.ts
- public/docs/_examples/toh-6/ts/app/in-memory-data.service.ts
- public/docs/_examples/upgrade-phonecat-2-hybrid/ts/systemjs.config.1.js
- public/docs/_examples/upgrade-phonecat-3-final/ts/systemjs.config.1.js
- public/docs/ts/_cache/guide/server-communication.jade
- public/docs/ts/latest/guide/npm-packages.jade
- public/docs/ts/latest/guide/server-communication.jade
"angular2-in-mem-web-api" becomes "angular-in-memory-web-api"
also made ready for aot
**coordinate merge with [angular/in-mem-web-api PR #31](https://github.com/angular/in-memory-web-api/pull/31)**
> chore: update samples to "angular-in-memory-web-api"

- public/docs/ts/latest/guide/pipes.jade
> Fix broken link to DatePipe docs

- public/docs/_examples/toh-5/ts/app/hero-detail.component.1.ts
- public/docs/_examples/toh-5/ts/app/hero-detail.component.ts
- public/docs/_examples/toh-6/ts/app/hero-detail.component.ts
- public/docs/ts/latest/tutorial/toh-pt5.jade
Also updated references of "Component Router" to "Router"
> docs(toh): Replaced window.history with location service

- gulpfile.js
This PR fixes a problem we had with the `upgrade-phonecat-3-final` example where it failed CI due to missing defaults on our `gulp e2e` tasks. 
This caused our tests to report that an example had failed transpilation because we couldn't default to the normal build task.
/cc @wardbell @Foxandxss
> fix(gulp): fix build and run task defaults

- public/docs/_examples/toh-6/ts/app/hero.service.ts
Since the update function does use const url instead of let url, this seemed like a good consistency to have between similar blocks of code. I just found it a little jarring when I was going through the tutorial myself
> * docs(toh-6): update 'let' to 'const' for delete hero

- public/docs/ts/latest/guide/testing.jade
> Fixed minor typos in testing

- public/docs/ts/latest/guide/testing.jade
> Fixed link

- public/docs/ts/latest/guide/style-guide.jade
This sentence just misses a word.
> add missing word in bootstrapping remark

- public/docs/dart/latest/guide/router.jade
@chalin could you please review this? Someone on Slack thought we had no router docs... :)
> docs(dart/router): link to router tutorial instead of TS router docs

- public/docs/ts/latest/cookbook/i18n.jade
> fix(i18n): fix link and formatting error

- public/docs/ts/latest/guide/style-guide.jade
> docs(style-guide): fix folder structure in 04 to match what we do.

- public/docs/_examples/toh-5/ts/app/app.component.ts
- public/docs/_examples/toh-6/ts/app/app.component.ts
The path to `app.component.css` should start from current directory, not `app/`, since the file is already in `app/`
> docs: fixed path typo in tutorial(Routing, HTTP)

- public/resources/js/directives/api-list.js
Dart API reference page is blank following the merge of #2566. This minor fix adapts to the new API filter criteria.
Also, for Dart we don’t show the statuses at all since none of the API entries are tagged with a status.
cc @kwalrath @naomiblack @alexwolfe @ericjim
> docs(api): fix Dart API reference page

- public/docs/ts/latest/tutorial/toh-pt5.jade
The current link in the Routing tutorial leads to a 404 error.
This update fixes that to point to the correct GitHub "raw" file link. Nevertheless, in the "Quickstart" the link takes to the normal GitHub page, not the "raw" file.
---
Also, it isn't very clear that for relative "asset" loading (html and css files) it's needed to set the `moduleId` variable in every `@Component` declaration to `module.id`. Otherwise the loading fails. (It took me some time to discover that).
As in:
```ts
@Component({
moduleId: module.id,
selector: 'my-dashboard',
templateUrl: 'dashboard.component.html',
styleUrls: ['dashboard.component.css']
})
export class DashboardComponent implements OnInit {
...
```
Should I try to add that to the guide to make it more clear in another PR?
> Update styles.css link in Routing tutorial

- public/docs/ts/latest/guide/template-syntax.jade
> docs(template-syntax): correct ref var scope per #2458

- public/docs/ts/latest/tutorial/toh-pt6.jade
Fix minor typo in HTTP guide
Change:
```
... get back on familiar ground by immediately by converting that Observable ...
```
to:
```
... get back on familiar ground by immediately converting that Observable ...
```
> Fix minor typo in HTTP guide

- tools/plunker-builder/builder.js
Currently, plunkers are using the wrong `tsconfig.json`. This PR fixes that.
/cc @Foxandxss
> fix(plunkers):use correct tsconfig

- public/docs/ts/latest/guide/testing.jade
Now this link doesn't navigate to anywhere. I think this should be link to the faq section.
> docs(testing):fix hash link

- public/docs/ts/latest/glossary.jade
Small error I noticed while going through docs.
As stated throughout angular.io, `AppModule` should be in `app.module.ts`
> docs(glossary): fix app module filename

- .editorconfig
The `end_of_line` setting causes issues on Windows machines that have `autocrlf` set to true (the default): https://git-scm.com/book/tr/v2/Customizing-Git-Git-Configuration#Formatting-and-Whitespace
> chore: remove end_of_line from editorconfig

- public/docs/_examples/router/e2e-spec.ts
- public/docs/_examples/router/ts/app/admin/admin-dashboard.component.2.ts
- public/docs/_examples/router/ts/app/app-routing.module.5.ts
- public/docs/_examples/router/ts/app/app-routing.module.6.ts
- public/docs/_examples/router/ts/app/app-routing.module.ts
- public/docs/_examples/router/ts/app/app.module.7.ts
- public/docs/_examples/router/ts/app/app.module.ts
- public/docs/_examples/router/ts/app/crisis-center/crisis-center-routing.module.4.ts
- public/docs/_examples/router/ts/app/crisis-center/crisis-detail.component.1.ts
- public/docs/_examples/router/ts/app/crisis-center/crisis-detail.component.ts
- public/docs/_examples/router/ts/app/heroes/hero-detail.component.ts
- public/docs/_examples/router/ts/app/selective-preload-strategy.ts
- public/docs/_examples/router/ts/plnkr.json
- public/docs/ts/latest/guide/router.jade
Also updated animations section with `:enter` and `:leave` transition aliases
> docs(router): Added example of feature module pre-loading

- gulpfile.js
- tools/dart-api-builder/dab.js
NOTE: this commit **only impacts Dart API page generation**.
This code cleanup & refactoring is being done because this new scheme works for both ng1.io and ng2.io whereas the current scheme works only for ng1.io.
- gulp task: don’t copy over internal libraries since they aren't being processed anyways.
- Adjust anchor hrefs rather than use `<base href>` in generated API pages. The net effect is the same.
Fixes ng2.io issue 359
cc @ericjim
> chore: Dart API doc gen cleanup and refactoring

- public/docs/ts/latest/tutorial/toh-pt5.jade
Technically 'nestled' still makes sense in this context, but is a little too Christmas-y! - I assume you meant 'nested' :P
> Typo fix 'nestled'=>'nested'

- public/docs/_examples/architecture/dart/pubspec.yaml
- public/docs/_examples/attribute-directives/dart/pubspec.yaml
- public/docs/_examples/component-styles/dart/pubspec.yaml
- public/docs/_examples/dependency-injection/dart/pubspec.yaml
- public/docs/_examples/displaying-data/dart/pubspec.yaml
- public/docs/_examples/forms/dart/pubspec.yaml
- public/docs/_examples/hierarchical-dependency-injection/dart/pubspec.yaml
- public/docs/_examples/lifecycle-hooks/dart/pubspec.yaml
- public/docs/_examples/pipes/dart/pubspec.yaml
- public/docs/_examples/server-communication/dart/pubspec.yaml
- public/docs/_examples/structural-directives/dart/pubspec.yaml
- public/docs/_examples/template-syntax/dart/pubspec.yaml
- public/docs/_examples/toh-1/dart/pubspec.yaml
- public/docs/_examples/toh-2/dart/pubspec.yaml
- public/docs/_examples/toh-3/dart/pubspec.yaml
- public/docs/_examples/toh-4/dart/pubspec.yaml
- public/docs/_examples/toh-5/dart/pubspec.yaml
- public/docs/_examples/toh-6/dart/pubspec.yaml
- public/docs/_examples/user-input/dart/pubspec.yaml
- pubspec.yaml
This is part 2 of 2. The first round of changes went in via https://github.com/angular/angular.io/commit/e9d40ab2d793817b67be06e87c91d4a02db18773.
> chore(dart): update to ng Dart version 2.0.0

- public/docs/_examples/cb-form-validation/ts/index.html
- public/docs/_examples/forms/js/index.html
- public/docs/_examples/forms/ts/index.html
- public/docs/_examples/homepage-tabs/ts/index.html
- public/docs/_examples/homepage-todo/ts/index.html
- public/docs/_examples/package.json
- public/docs/_examples/quickstart/js/package.1.json
- public/docs/_examples/quickstart/ts/package.1.json
- tools/plunker-builder/indexHtmlTranslator.js
The main reason behind this change is to not confuse the end user with "Why do we have bootstrap as a dependency"? "Does Angular depend on bootstrap"?
The idea was to replicate the minimum css needed from bootstrap into those two forms guides but I think it is better for the time being to use a cdn (I saw that phonecat, AKA upgrade guide uses a cdn with bootstrap already) and then change it later.
> chore: remove bootstrap package

- public/docs/ts/latest/guide/router.jade
> docs(router): Fix typos

- public/docs/ts/latest/guide/router.jade
tweaks some other related language.
> docs(router): fix grammar typo in preloader section

- public/resources/css/module/_home-promos.scss
This code chunk was originally from Material 1. We’ve removed angular-material.css since its namespace collides with Material 2. This was originally part of quirks.scss in our original repo,
closes: https://github.com/angular/angular.io/issues/2704
> add flex system for front page and api reference.

- gulpfile.js
- public/resources/css/_angular.scss
- public/resources/css/base/_type.scss
Also restore `ng-cloak` definitions because we are resorting to stripping out `ng-cloak` where needed.
> chore(gulpfile): make ng2 build the default; add ng-build-and-copy task

- public/_includes/_hero-home.jade
- public/resources/css/module/_announcement-bar.scss
- src/app/announcement-bar/announcement-bar.component.html
fixes: https://github.com/angular/angular.io/issues/2712
Note: the slide indicators are tied to ngOnInit, which means they won't appear until the component is initialized.
> [ng2] Fix announcement thrashing

- public/_includes/_main-nav.jade
- public/_includes/_scripts-include.jade
- public/_includes/_version-dropdown.jade
- public/docs/_includes/_side-nav.jade
- public/resources/js/util.js
Support menu toggling w/o using A1 controller. Menus affected:
- Main menu
- Sidenav
- Language delection menu.
With this commit, we are able to exclude all A1 and MD1 scripts.
Fixes #2703.
> [ng2] add support menu toggling; exclude all A1 & md1 scripts

- gulpfile.js
With only `--prod` as a flag for, say, `ng build`, it doesn’t seem to work to enable production mode.
> [ng2] chore(gulpfile): ng2 build use --env=prod

- public/docs/_examples/lifecycle-hooks/ts/app/counter.component.ts
- public/docs/_examples/lifecycle-hooks/ts/app/on-changes.component.ts
- public/docs/_examples/lifecycle-hooks/ts/app/peek-a-boo.component.ts
> docs(lifecycle-hooks): `SimpleChange` -> `SimpleChanges` #2741

- public/docs/_examples/forms/dart/pubspec.yaml
- public/docs/_examples/template-syntax/dart/pubspec.yaml
`FORM_DIRECTIVES` no longer has to be imported as it is part of the `COMMON_DIRECTIVES` import.
> docs(dart): remove unnecessary directives import

- .firebaserc
- firebase.json
- gulpfile.js
Remove project name from `firebase.json`, since that is deprecated.
The `check-deploy` gulp task now checks that an active project is defined at the start of `check-deploy`.
To set the active project use: `firebase use <project-or-alias-name>`.
Fixes #2576
cc @kwalrath
> chore: add firebase project name to prompt

- gulpfile.js
- public/docs/_examples/_boilerplate/systemjs.config.web.build.js
- public/docs/_examples/_boilerplate/systemjs.config.web.js
- public/docs/_examples/testing/ts/browser-test-shim.js
- tools/plunker-builder/builder.js
**A simplified "Getting Started" experience is the driver behind these changes.**
The `systemjs.config.plunker....` files renamed to `systemjs.config.web...` because these `systemjs.config` variations are good for transpiling and running in web browser _anywhere_, not just in plunkers.
Pulls the compiling advice from `tsconfig.json` into the system configuration so that the `tsconfig.json` is not necessary when transpiling in the browser.
The web versions also JiT bootstrap the `AppModule` automatically so that the standard `app/main.ts` is not necessary. The plunker builder _excludes `app/main.ts`_.
**Override this automatic bootstrapping by setting `document['noBootstrap']=true`** as we must do in the `browser-test-shim` which controls the launch of the test harness.
These steps help …
> docs: systemjs.config.plunker -> systemjs.config.web w/ auto-bootstrap

- public/docs/_layout.jade
- public/docs/dart/latest/guide/i18n.jade
- public/docs/js/latest/guide/i18n.jade
- public/docs/ts/_cache/guide/dependency-injection.jade
- scripts/check-dart-api-links.sh
- Dart non-api doc pages w/ links to API entries will now have those links translated from a TS API reference URL to a Dart API reference URL.
- Created and ran a link checker to verify that all such links to API entries refer to Dart.
- Fixed links to pages that have moved:
- JS & Dart: `i18n` is under now `cookbook` not `guide`
- Dart: testing page is now directly under guide.
Contributes to #1895
Fixes #2273
> chore: fix broken links and transform API links for dart docs

- gulpfile.js
Naming the project would sometimes cause gulp to report `An unexpected error has occurred` with exit code 2.
> chore(deploy): don't name project in firebase deploy

- public/docs/dart/latest/guide/forms.jade
> docs(forms/dart): remove mention of FORM_DIRECTIVES

- public/docs/ts/_cache/guide/dependency-injection.jade
- public/docs/ts/latest/guide/dependency-injection.jade
- public/docs/ts/latest/guide/npm-packages.jade
- public/docs/ts/latest/guide/style-guide.jade
Contributes to #2772.
Also performed a partial sync of `_cache/guide/dependency-injection.jade`.
> docs: intra-site links should be relative

- public/docs/ts/latest/cookbook/a1-a2-quick-reference.jade
Link in "ANGULAR 1 TO 2 QUICK REFERENCE" was incorrect. Fixed from #Pipes to #filters-pipes
> Fix link to Filter/Pipes

- public/docs/_examples/ngmodule/ts/index.0.html
- public/docs/_examples/ngmodule/ts/index.1.html
- public/docs/_examples/ngmodule/ts/index.1b.html
- public/docs/_examples/ngmodule/ts/index.2.html
- public/docs/_examples/ngmodule/ts/index.3.html
- tools/plunker-builder/indexHtmlTranslator.js
This will hide the `System.import('app')` only for custom ones.
> docs(ngmodule): fix plunkers

- .gitignore
This file is generated when running `gulp e2e` and often enough committed by mistake.
/cc @foxandxss
> chore: ignore debug.log file

- tools/plunker-builder/builder.js
> chore: ability to open a plunker on a specific file

- public/docs/_examples/template-syntax/e2e-spec.ts
- public/docs/_examples/template-syntax/ts/app/app.component.html
- public/docs/_examples/template-syntax/ts/app/app.component.ts
- public/docs/_examples/template-syntax/ts/app/app.module.ts
- public/docs/_examples/template-syntax/ts/app/click.directive.ts
- public/docs/_examples/template-syntax/ts/app/my-sizer.component.ts
- public/docs/_examples/template-syntax/ts/app/sizer.component.ts
- public/docs/ts/latest/guide/template-syntax.jade
- Follow style guide: rename `sizer.component.ts` to `my-sizer.component.ts` (given the selector `my-sizer`); also appropriately rename class.
- Rename `AppComponent.fontSize` to `AppComponent.fontSizePx` because it is assigned to `[style.font-size.px]` and so represents a size in px, not a general font-size value (which could be, e.g., “x-large”).
- Added small interactive example of `NgStyle`.
> example(template-syntax): follow style-guide and other updates

- public/docs/dart/latest/tutorial/toh-pt1.jade
- public/docs/dart/latest/tutorial/toh-pt2.jade
- public/docs/dart/latest/tutorial/toh-pt4.jade
- public/docs/ts/_cache/tutorial/toh-pt5.jade
- public/docs/ts/_cache/tutorial/toh-pt6.jade
- public/docs/ts/latest/guide/template-syntax.jade
- public/docs/ts/latest/tutorial/_data.json
- public/docs/ts/latest/tutorial/index.jade
- public/docs/ts/latest/tutorial/toh-pt1.jade
- public/docs/ts/latest/tutorial/toh-pt2.jade
- public/docs/ts/latest/tutorial/toh-pt4.jade
- public/docs/ts/latest/tutorial/toh-pt5.jade
- public/docs/ts/latest/tutorial/toh-pt6.jade
Doc page headers are defined in `_data.json` files via a `title` attribute. Main page .jade files should not start with an `<h1>` header since Harp layout template generates a `<h1>` header from the `_data.json` files. Not all ToH pages followed this convention. This fixes the issue; and in one case I moved the `<h1>` text into `_data.json` as a `subtitle` attribute.
Also updated `_cache` files for all ToH.
> docs(toh): avoid dup header title

- public/resources/js/util.js
The function `getExampleName` is used, e.g., by the `<live-example>` directive. This change helps support page URLs with and with out `.html` suffixes.
> chore(util.js): getExampleName - support optional .html suffix

- public/docs/ts/latest/guide/index.jade
- Eliminate use of deprecated `clear=“all”` in `<br>`.
- No need for local `langName`; use global `_Lang` var instead.
- Remove duplicate id `learning-path`.
cc @ericjim
> docs: guide/index misc Jade fixes

- public/docs/_examples/toh-6/ts/app/main.ts
- public/docs/ts/latest/cookbook/aot-compiler.jade
Kioagar's PR #2790 makes additions/clarification:
* Add `main-aot.ts` and `main.ts` comparison in the key differences.
* Add a sub note below `tsconfig-aot.json` and `tsconfig.json` comparison to highlight and explain
the usage of `../../node_modules/@types/` instead of `node_modules/@types/`.
Ward tweaked these changes in this PR
> docs(cookbook-aot-compiler): improve Ahead-of-Time compilation cookbook

- public/_includes/_footer.jade
When user clicks in Books & Training item in footer the website should take them to Education section (anchor) in the middle of the page, not to the top where Development section is.
> clicking on Books & Training sends user to Education

- public/docs/ts/latest/guide/change-log.jade
**WIP: Update and merge when we commit docs for Angular v.2.2.0**
> chore(changelog): update docs changelog for Ng v.2.2.0

- public/docs/_examples/architecture/dart/lib/sales_tax_component.dart
- public/docs/_examples/architecture/e2e-spec.ts
> example(architecture/dart): drop currency pipe workaround

- public/docs/_examples/dependency-injection/dart/lib/app_component.dart
- public/docs/_examples/dependency-injection/dart/lib/providers_component.dart
- public/docs/_examples/dependency-injection/dart/web/index.html
- public/docs/_examples/dependency-injection/dart/web/main.dart
- public/docs/_examples/dependency-injection/ts/app/app.component.ts
- public/docs/_examples/dependency-injection/ts/app/app.module.ts
- public/docs/_examples/dependency-injection/ts/app/providers.component.ts
- public/docs/_examples/dependency-injection/ts/index.html
Fixes #2493
No need to dual boot `AppComponent` and `ProvidersComponent` only to ensure that we could demo optional injection; instead just inject null for the `@Optional` constructor parameter type.
**Prose is unaffected** by these changes.
```
Suites passed:
public/docs/_examples/dependency-injection/dart
public/docs/_examples/dependency-injection/ts
```
> e2e(dependency-injection): fix for Dart and simplification for TS

- public/_includes/_util-fns.jade
- public/docs/dart/latest/_util-fns.jade
- public/docs/dart/latest/tutorial/toh-pt5.jade
- public/docs/ts/_cache/guide/structural-directives.jade
- public/docs/ts/latest/guide/structural-directives.jade
- public/docs/ts/latest/tutorial/toh-pt5.jade
Only minor prose edits in this PR. No net change in the generated HTML for the TS side.
> docs(struct-directives): update Dart cache (w/ no-op changes to TS prose)

- public/resources/js/util.js
Currently, when visiting a page with a relative link e.g. https://angular.io/docs/ts/latest/guide/testing.html#!#top, `NgIoUtil.getExampleName` fails to match the example name. 
This results on `live-example` directives on that page missing the example name in the link: instead of linking to https://angular.io/resources/live-examples/testing/ts/plnkr.html it will link to https://angular.io/resources/live-examples//ts/plnkr.html (notice the missing `testing` and the double slashes).
/cc @Foxandxss
> fix(live-example): correctly match example name

- public/docs/ts/_cache/glossary.jade
- public/docs/ts/_cache/guide/lifecycle-hooks.jade
- public/docs/ts/_cache/guide/server-communication.jade
- public/docs/ts/latest/cookbook/index.jade
- public/docs/ts/latest/cookbook/ngmodule-faq.jade
- public/docs/ts/latest/glossary.jade
- public/docs/ts/latest/guide/browser-support.jade
- public/docs/ts/latest/guide/change-log.jade
- public/docs/ts/latest/guide/index.jade
- public/docs/ts/latest/guide/lifecycle-hooks.jade
- public/docs/ts/latest/guide/server-communication.jade
- public/docs/ts/latest/guide/testing.jade
- public/docs/ts/latest/guide/upgrade.jade
Only the page TOC should be at heading level 1. All other headings should start at level 2. This commit also removes duplicate headings, in continuation of #2796.
(This fix is necessary to support an auto-TOC feature.)
> docs: adjust page heading levels

- public/resources/css/layout/_layout.scss
- public/resources/js/directives/api-list.js
There should be no visible net effect. This should help ease the transition off Dart out of Angular.io
cc @chalin @kwalrath
> replace clearfix with a wrapping flexbox

- public/docs/ts/latest/guide/router.jade
The link *Importing from the router library* (https://angular.io/docs/ts/latest/guide/router.html#import) does not work.
I supposed that this was the corresponding section to be linked to.
> Update router.jade: Fix missing anchor id

- public/docs/dart/latest/cheatsheet.jade
This should ease the transition for Dart out of angular.io. This is similar to the changes done to api-list in https://github.com/angular/angular.io/pull/2819/files
cc @chalin @kwalrath
> remove grid fluid from dart api list

- public/docs/ts/_cache/guide/architecture.jade
- public/docs/ts/latest/guide/architecture.jade
- public/docs/ts/latest/guide/index.jade
- public/docs/ts/latest/guide/lifecycle-hooks.jade
- public/resources/css/layout/_layout.scss
This should ease the transition of Dart out of angular.io
cc @chalin @kwalrath
> chore: remove deprecated `clear=` and use clear layout helpers

- public/_includes/_util-fns.jade
- public/docs/dart/latest/_util-fns.jade
- public/docs/dart/latest/api/index.jade
- public/docs/dart/latest/guide/index.jade
- public/docs/ts/latest/guide/index.jade
- Also added links to chapters mentioned in table.
- Other minor copyedits.
> docs(guide & api): feedback/issue links for Dart should refer to Dart repos

- public/docs/_examples/_boilerplate/systemjs.config.web.build.js
- public/docs/_examples/_boilerplate/systemjs.config.web.js
To facilitate goal of a QuickStart without an AppModule. Almost no other sample should use this feature.
> docs(systemjs.web): can create a default for missing AppModule.ts

- public/docs/dart/latest/quickstart.jade
- public/docs/ts/_cache/quickstart.jade
- public/docs/ts/latest/quickstart.jade
**[The middle commit](https://github.com/angular/angular.io/commit/a22b0b6ab54b96af3db92f3899f3dc91469e8524?w=1)** of this PR is the only **significant commit** (the others are just cache file sync'ing), and it is **best reviewed by ignoring whitespace**.
I know that a new QS is on its way, but folks have been **filing bugs over the outdated Dart QS**. This PR at least syncs the Dart version with the TS version of QS.
cc @ericjim @kwalrath 
Fixes #2753,  #2829
> docs(Dart): sync with TS version of quickstart

- public/docs/_examples/_boilerplate/systemjs.config.web.build.js
- public/docs/_examples/_boilerplate/systemjs.config.web.js
- public/docs/_examples/ngmodule/ts/index.0.html
- public/docs/_examples/ngmodule/ts/index.1.html
- public/docs/_examples/ngmodule/ts/index.1b.html
- public/docs/_examples/ngmodule/ts/index.2.html
- public/docs/_examples/ngmodule/ts/index.3.html
- public/docs/_examples/testing/ts/browser-test-shim.js
- tools/plunker-builder/builder.js
- tools/plunker-builder/indexHtmlTranslator.js
For specific plunkers, e.g. "QuickStart (reboot edition)" PR #2762, that shouldn't have AppModule or main.ts
Rescinds the automatic bootstrapping and exclusion of `main.ts` in #2786 and #2756
Only autoBootstraps when `window.autoBootstrap === true`.
> docs(systemjs.web): auto-bootstrap option that creates its own AppModule and boots it.

- gulpfile.js
- public/_includes/_version-dropdown.jade
- public/docs/js/latest/quickstart.jade
**[Best reviewed by ignoring whitespace diffs](https://github.com/angular/angular.io/pull/2832/files?w=1)**.
In particular, don’t show the language dropdown for the docs change-log page (since JS and Dart don’t have a change log).
Together with #2830, this
fixes #2150
> docs: fix remaining broken links

- public/docs/ts/_cache/guide/server-communication.jade
- public/docs/ts/latest/guide/server-communication.jade
The TS path was wrongly being shown for Dart.
> docs(server-comm): fix path to heroes.json for Dart

- package.json
- public/docs/_examples/_boilerplate/package.json
- public/docs/_examples/_boilerplate/tsconfig.json
- public/docs/_examples/cb-aot-compiler/ts/tsconfig-aot.json
- public/docs/_examples/package.json
- public/docs/_examples/quickstart/js/package.1.json
- public/docs/_examples/quickstart/ts/package.1.json
- public/docs/_examples/quickstart/ts/tsconfig.1.json
- public/docs/_examples/styleguide/package.1.json
- public/docs/_examples/toh-6/ts/tsconfig-aot.json
- public/docs/_examples/tsconfig.json
- public/docs/_examples/upgrade-phonecat-2-hybrid/ts/package.ng1.json
- public/docs/_examples/webpack/ts/package.webpack.json
- public/docs/ts/latest/guide/typescript-configuration.jade
> chore: use tsconfig lib

- tools/plunker-builder/indexHtmlTranslator.js
Don't strip 
```
<script>
System.import('app').catch(function(err){ console.error(err); });
</script>
```
from `index.html` now that all but QS plunkers should have both `main.ts` and `AppModule`
> chore(plunker-builder): don't strip `import ('app')` from index

- public/docs/_examples/toh-5/dart/lib/dashboard_component.html
- public/docs/_examples/toh-5/dart/lib/hero_detail_component.dart
- public/docs/_examples/toh-6/dart/lib/dashboard_component.dart
- public/docs/_examples/toh-6/dart/lib/dashboard_component.html
- public/docs/_examples/toh-6/dart/lib/hero_detail_component.dart
The route name was changed to `'HeroDetail'` but either of `'/HeroDetail'` or `'../HeroDetail'` would have worked.
> examples(toh-5, toh-6): fix Dart e2e

- public/docs/ts/_cache/quickstart.jade
- public/docs/ts/latest/quickstart.jade
Recovering definition lost during updates in #2839.
Supersedes #2847
Fixes #2838
> docs(quickstart): recover definition of _quickstartSrcURL

- public/docs/_examples/user-input/ts/app/keyup.components.ts
- public/docs/ts/latest/guide/user-input.jade
Original PR had some issues. Testing to see if a local rebase resolved. Original branch is user-input-edits. This one, Jessica-user-input-edits, is a copy of the original with a rebase.
> [WIP] docs(user-input): Jessica's user input edits

- public/docs/_examples/forms/ts/app/hero-form.component.html
- public/docs/_examples/forms/ts/app/hero-form.component.ts
- public/docs/ts/latest/guide/forms.jade
Update the docs to match the latest api since there's a `reset()` method for the form.
> docs(forms): replace hack with call to `reset` #2066

- public/docs/dart/latest/tutorial/toh-pt5.jade
- public/docs/ts/_cache/tutorial/toh-pt5.jade
- public/docs/ts/_cache/tutorial/toh-pt6.jade
- public/docs/ts/latest/tutorial/toh-pt5.jade
- Dart prose: also switched from "we" to "you".
- Fixed broken link in TS. Most other changes are to use "if docs ts".
cc @filipesilva @Foxandxss - you can ignore updates to cache files.
> docs(toh-5/6): update Dart to match TS, with minor tweaks to TS

- gulpfile.js
- public/docs/README.md
E.g., `gulp _shred-devguide-examples --filter=dep`
Also removed docs/README.md since it was reporting something that is no longer true (we don’t commit `_fragments` anymore).
> chore(gulp): selectively shred guide examples using --filter

- public/docs/_examples/_boilerplate/styles.css
Supersedes #2872 but ensures that we don’t loose `.items li.selected`.
> examples(styles): drop duplicate `items` classes but keep `li.selected`

- public/resources/js/directives/live-example.js
Adds default title (tooltip) of the example text unless overiden with "title" attribute
The "embedded-style" attribute causes link to open in new tab in the embedded style.
Use for samples that have a confusingly large number of files.
The "embedded" attribute option remains and displays _inline_ in the _same_ tab.
Also adjusted the documentation comments
> chore: add default title and embedded-style options to <live-example>

- public/docs/ts/latest/guide/style-guide.jade
I was walking through the documentation and noticed a markdown issue. Cheers! 🍻
> Add missing ` from styleguide rule

- public/docs/ts/latest/guide/router.jade
<router-outlet> does not wrap the views, the views are inserted next to its closing tag, not within its content.
> Corrected RouterOutlet description

- public/resources/js/directives/live-example.js
Open link in the embedded style by default.
This is almost always more readable then the original editor "flat" style with a flat list of files on the left.
Added "flat-style" attribute option if you prefer to force a plunker into the original, flat editor style
> chore(plunker): open in embedded-style by default

- public/docs/_examples/toh-6/ts/app/hero.service.ts
closes issue #2883. Fix the two problems described there.
> docs(toh-6): fix hero.service per issue #2883

- public/docs/_examples/toh-6/dart/lib/in_memory_data_service.dart
In the ToH examples, the initial db has always been populated with some heroes. Deleting all heroes causes no problems (one can add more heroes after that). The reported issue is for the situation where the initial heroes db is empty.
Fixes https://github.com/angular-examples/toh-6/issues/2
> examples(toh-6/dart): support case where `_initialHeroes` is empty

- public/docs/_examples/_boilerplate/systemjs.config.web.build.js
- public/docs/_examples/_boilerplate/systemjs.config.web.js
- public/docs/_examples/cb-component-communication/ts/app/name-child.component.ts
- public/docs/_examples/cb-component-communication/ts/app/name-parent.component.ts
- public/docs/_examples/package.json
Simplify name-child component.
Update TS version in package.json and the web systemjs.configs (won't take effect until update SHA in index.html)
Inspired by issue #2881
> chore(cb-component-communication): tweak code/update TS version

- public/docs/_examples/cb-aot-compiler/ts/app/app.component.ts
- public/docs/_examples/cb-aot-compiler/ts/index.html
- public/docs/ts/latest/cookbook/aot-compiler.jade
@wardbell Adding module.id to the AoT CB
Moved the Component-relative Template URLS (with minor tweaks) higher up in the prose to explain it as part of the first sample.
> docs(cb-aot): add missing module.id to sample

- public/docs/_examples/testing/ts/karma-test-shim.js
- public/docs/_examples/testing/ts/karma.conf.js
- public/docs/ts/latest/guide/change-log.jade
* karma.config + karma-test-shim can handle multiple spec source paths;
see quickstart issue: https://github.com/angular/quickstart/issues/294
* Displays Jasmine Runner output in the karma-launched browser
* cosmetic `karma.config.js` changes
> chore(testing): karma config files support multiple builtPaths

- public/docs/_examples/webpack/ts/tsconfig.1.json
Pull request for this [issue](https://github.com/angular/angular.io/issues/2890).
> docs(webpack): fix for tsconfig.json provided in example

- public/docs/_examples/architecture/dart/pubspec.yaml
- public/docs/_examples/attribute-directives/dart/pubspec.yaml
- public/docs/_examples/component-styles/dart/pubspec.yaml
- public/docs/_examples/dependency-injection/dart/pubspec.yaml
- public/docs/_examples/displaying-data/dart/pubspec.yaml
- public/docs/_examples/forms/dart/pubspec.yaml
- public/docs/_examples/hierarchical-dependency-injection/dart/pubspec.yaml
- public/docs/_examples/lifecycle-hooks/dart/pubspec.yaml
- public/docs/_examples/pipes/dart/pubspec.yaml
- public/docs/_examples/quickstart/dart/pubspec.yaml
- public/docs/_examples/server-communication/dart/pubspec.yaml
- public/docs/_examples/structural-directives/dart/pubspec.yaml
- public/docs/_examples/template-syntax/dart/pubspec.yaml
- public/docs/_examples/toh-1/dart/pubspec.yaml
- public/docs/_examples/toh-2/dart/pubspec.yaml
- public/docs/_examples/toh-3/dart/pubspec.yaml
- public/docs/_examples/toh-4/dart/pubspec.yaml
- public/docs/_examples/toh-5/dart/pubspec.yaml
- public/docs/_examples/toh-6/dart/pubspec.yaml
- public/docs/_examples/user-input/dart/pubspec.yaml
- public/docs/dart/latest/_data.json
- pubspec.yaml
- tools/doc-shredder/_test/test_source/multiregion/pubspec.yaml
- tools/doc-shredder/_test/test_source/no-multiregion/pubspec.yaml
- All Dart e2e tests pass (see below).
- I've ensured that the Dart samples aren't impacted by the 2.2.0 breaking change (on constructor arguments with certain annotations). 
```
Suites passed:
public/docs/_examples/architecture/dart
public/docs/_examples/attribute-directives/dart
public/docs/_examples/dependency-injection/dart
public/docs/_examples/displaying-data/dart
public/docs/_examples/forms/dart
public/docs/_examples/lifecycle-hooks/dart
public/docs/_examples/pipes/dart
public/docs/_examples/quickstart/dart
public/docs/_examples/server-communication/dart
public/docs/_examples/template-syntax/dart
public/docs/_examples/toh-1/dart
public/docs/_examples/toh-2/dart
public/docs/_examples/toh-3/dart
public/docs/_examples/toh-4/dart
public/docs/_examples/toh-5/dart …
```
> [Dart] upgrade to 2.2.0

- public/docs/_examples/toh-5/dart/lib/heroes_component.dart
- public/docs/dart/latest/tutorial/toh-pt1.jade
- public/docs/dart/latest/tutorial/toh-pt2.jade
- public/docs/dart/latest/tutorial/toh-pt3.jade
- public/docs/dart/latest/tutorial/toh-pt4.jade
- public/docs/dart/latest/tutorial/toh-pt5.jade
- public/docs/dart/latest/tutorial/toh-pt6.jade
- public/docs/ts/_cache/tutorial/toh-pt5.jade
- public/docs/ts/_cache/tutorial/toh-pt6.jade
- public/docs/ts/latest/tutorial/toh-pt2.jade
- public/docs/ts/latest/tutorial/toh-pt3.jade
- public/docs/ts/latest/tutorial/toh-pt4.jade
- public/docs/ts/latest/tutorial/toh-pt5.jade
- public/docs/ts/latest/tutorial/toh-pt6.jade
In the Dart toh-5: ensure `HeroesComponent` doc region `renaming` doesn't show a router.
> docs(toh): fix code-example format and Dart code excerpt

- public/_includes/_hero.jade
- public/docs/dart/latest/_data.json
- public/docs/dart/latest/guide/_data.json
- public/docs/js/latest/_data.json
- public/docs/js/latest/guide/_data.json
- public/docs/ts/latest/_data.json
- public/docs/ts/latest/guide/_data.json
- public/resources/js/directives/cheatsheet.js
Continuation of #2796, "duplicate header cleanup".
This PR also streamlines the cheatsheet page: the language and version are now shown in the header rather than in the page content.
> ![screen shot 2016-12-01 at 8 09 32 am](https://cloud.githubusercontent.com/assets/4140793/20802356/a6ce91ea-b7a0-11e6-82b7-a13968d555d0.png)
The Angular version is also shown on the API Reference page.
cc @kwalrath
> docs(api/cheatsheet): show ng version + lang in page header

- public/docs/_examples/pipes/ts/app/fetch-json.pipe.ts
- public/docs/_examples/pipes/ts/app/hero-async-message.component.ts
- public/docs/_examples/pipes/ts/app/hero-list.component.ts
- public/docs/_examples/pipes/ts/app/main.ts
- public/docs/_examples/pipes/ts/app/rxjs-extensions.ts
- public/docs/ts/_cache/guide/pipes.jade
- public/docs/ts/latest/guide/pipes.jade
Cleans up some specific complaints about the pipes documentation. That guide (which is old) could benefit from some rethinking. This PR is a tiny step in the right direction.
> docs(pipes): improve FetchJsonPipe discussion

- public/docs/_examples/attribute-directives/ts/app/highlight.directive.1.ts
- public/docs/_examples/attribute-directives/ts/app/highlight.directive.2.ts
- public/docs/_examples/attribute-directives/ts/app/highlight.directive.ts
- public/docs/_examples/ngmodule/ts/app/contact/highlight.directive.ts
- public/docs/_examples/ngmodule/ts/app/hero/highlight.directive.ts
- public/docs/_examples/ngmodule/ts/app/highlight.directive.ts
- public/docs/_examples/ngmodule/ts/app/shared/highlight.directive.ts
- public/docs/_examples/style-guide/ts/02-08/app/shared/input-highlight.directive.ts
- public/docs/_examples/testing/ts/app/about.component.spec.ts
- public/docs/_examples/testing/ts/app/bag/bag.spec.ts
- public/docs/_examples/testing/ts/app/bag/bag.ts
- public/docs/_examples/testing/ts/app/shared/highlight.directive.spec.ts
- public/docs/_examples/testing/ts/app/shared/highlight.directive.ts
- public/docs/ts/latest/guide/attribute-directives.jade
- public/docs/ts/latest/guide/testing.jade
There is one more file that I don't know quite how to approach:
[Testing](https://angular.io/docs/ts/latest/guide/testing.html)
> [WIP]docs(sweep): remove renderer throughout

- public/docs/ts/latest/guide/style-guide.jade
Fix a typo on the T-DRY section.
> docs(style-guide): fix typo

- scripts/before-install.sh
This wasn’t necessary before, but it seems to be necessary now.
cc @filipesilva @Foxandxss
> chore: also install -g gulp on Travis

- public/docs/_examples/toh-6/dart/lib/hero_service.dart
- public/docs/_examples/toh-6/dart/lib/in_memory_data_service.dart
- public/docs/ts/_cache/tutorial/toh-pt6.jade
- public/docs/ts/latest/tutorial/toh-pt6.jade
Dart follow-up to #2906
```
Suites passed:
public/docs/_examples/toh-6/dart
```
> docs(toh-6/dart): getHero makes HTTP get-by-id

- public/docs/_examples/pipes/dart/lib/fetch_json_pipe.dart
- public/docs/_examples/pipes/dart/lib/hero_list_component.dart
- public/docs/ts/_cache/guide/pipes.jade
- public/docs/ts/latest/guide/pipes.jade
Followup to #2923
```
Suites passed:
public/docs/_examples/pipes/dart
```
cc @wardbell - as usual, this is mainly updates to Dart files but with minor tweaks to the TS Jade. There was actually a `:marked` missing so some text wasn't showing up. I've fixed that.
> docs(pipes/dart): improve FetchJsonPipe discussion

- public/docs/_examples/toh-5/dart/lib/dashboard_component.dart
- public/docs/_examples/toh-5/ts/app/dashboard.component.ts
Fixes https://github.com/dart-lang/site-webdev/issues/203
> docs(toh-5/dart): fix and clean out dashboard_component regions

- public/docs/dart/latest/glossary.jade
- public/docs/dart/latest/guide/dependency-injection.jade
- public/docs/dart/latest/guide/server-communication.jade
- public/docs/ts/latest/glossary.jade
Fixes a broken link+anchor in TS too.
Addresses, in part https://github.com/dart-lang/site-webdev/issues/204
> docs: fix broken links (mainly for Dart)

- public/docs/dart/latest/guide/lifecycle-hooks.jade
- public/docs/ts/_cache/glossary.jade
- public/docs/ts/_cache/guide/lifecycle-hooks.jade
- public/docs/ts/latest/guide/lifecycle-hooks.jade
> docs(lifecycle-hooks): Dart sync with TS updates

- public/docs/_examples/package.json
Followup to https://github.com/angular/angular.io/pull/2684, it is no longer needed.
/cc @wardbell @Foxandxss @cnishina
> ci: update protractor

- public/docs/_examples/package.json
So that `Observable<Response>` returned by `Http` calls involving the in-mem-web-api are "cold".
That means they don't occur until someone subscribes.
See [in-mem repo's change log for 0.2.0](https://github.com/angular/in-memory-web-api/blob/master/CHANGELOG.md#020-2016-12-11).
> chore: update example package.json to use in-mem-web-api 0.2.0

- public/docs/ts/latest/guide/router.jade
Starts from the typo identified by PR #2945, then re-phrases it and the surrounding passage.
> docs(router): fix typo originally identified by PR #2945

- public/docs/_examples/testing/ts/karma.conf.js
As discovered in QS, see [PR#314](https://github.com/angular/quickstart/pull/314)
> chore(testing): correct typo in karma.conf builtPaths

- public/docs/_examples/.gitignore
- public/docs/_examples/package.json
Tweak to `.gitignore` so that only the `tsconfig.json` files in subdirectories are ignored, not the one directly in this `_examples` folder.
Also, add a package.json script definition for `http-server` for more convenient access (w/o invoking tsc as is forced in the script definition given in `_boilerplate/package.json`.
cc @kwalrath
> chore(examples): don't gitignore _examples/tsconfig.json

- public/docs/ts/_cache/tutorial/toh-pt5.jade
Looks like this was supposed to refer to the `HeroDetailComponent` instead (there is no `HeroesDetailComponent`)
> docs(toh-5): fix HeroesDetailComponent typo

- public/docs/_examples/_boilerplate/systemjs.config.web.build.js
- public/docs/_examples/_boilerplate/systemjs.config.web.js
- public/docs/_examples/setup/ts/systemjs.config.extras.web.js
- public/docs/_examples/testing/ts/app/hero/hero-detail.component.ts
- public/docs/_examples/testing/ts/systemjs.config.extras.web.js
- tools/plunker-builder/builder.js
Solves sudden problem with plunker not handling the non-plunker version.
See illustrative plunker: http://plnkr.co/edit/osNMXqB4pgZugEckBDVF?p=info
Also switch from `pluck` to `map` because `pluck` typing stopped working.
> chore(plunker): sub systemjs.config.extras.web.js for systemjs.config.extras.js

- public/docs/ts/_cache/glossary.jade
- public/docs/ts/_cache/tutorial/toh-pt6.jade
- public/docs/ts/latest/tutorial/toh-pt5.jade
Note the backport of a cache change (#2965) for toh-5.
> docs(ts/_cache): misc sync

- public/docs/ts/latest/cookbook/_data.json
- public/docs/ts/latest/cookbook/i18n.jade
Shannon's copy edits to Internationalization.
> docs(i18n): copy edits to internationalization cookbook

- public/docs/_examples/server-communication/ts/app/app.module.ts
- public/docs/_examples/server-communication/ts/app/default-request-options.service.ts
- public/docs/ts/latest/guide/server-communication.jade
John Papa pointed out that this makes user testing easier if you care about headers in those tests.
> docs(http): use a class for default `RequestOptions` override

- public/docs/ts/latest/tutorial/toh-pt5.jade
> docs(toh-pt5): add instruc for adding `moduleId` to `AppComponent` (#2967)

- .gitignore
- public/docs/ts/latest/guide/architecture.jade
Mainly adding Jade blocks. Other minor tweaks.
Best [reviewed by **ignoring whitespace differences**](https://github.com/angular/angular.io/pull/2990/files?w=1).
cc @kwalrath
> docs(architecture): add Jade blocks for Dart, and other tweaks

- public/docs/ts/latest/guide/architecture.jade
Minor adjustments, in particular, gets rid of custom styling in favor of using plain markdown for pipe example. This fixes the layout for some displays.
Followup to #2990
cc @kwalrath
> docs(architecture): copyedits + adjusted jade blocks

- public/docs/ts/latest/guide/template-syntax.jade
Main fix is to file name (incorrectly) previously shown as `HeroDetailComponent.ts`.
> docs(template-syntax): fix filename for code excerpt

- public/docs/_examples/package.json
When https://github.com/angular/protractor/pull/3848 is ready it should fix the webdriver types issues, and the pinning can be reverted.
Will bring up the zone breakage with a repro in it's repo.
> fix(ci): pin webdriver and zone versions

- public/docs/_examples/security/ts/app/bypass-security.component.html
- public/docs/_examples/security/ts/app/inner-html-binding.component.ts
- public/docs/ts/latest/guide/security.jade
There are very few changes in the .jade file; as can be seen by [**ignoring whitespace diffs**](3017/files?w=1).
> docs(security): hide TOC for Dart; other minor copyedits

- public/docs/_examples/animations/e2e-spec.ts
https://github.com/angular/angular.io/pull/3018 broke our animations test because it was still relying on a type present in webdriver typings. This PR uses the type from `selenium-webdriver` instead.
> test(deps): fix webdriver logging entry type

- tools/plunker-builder/builder.js
Currently plunkers for AoT enabled chapters (such as ToH-6) will emit a few AoT-only files.
This PR removes those files from plunker auto-generation.
//cc @Foxandxss
> build(plunkers): don't emit AoT files

- public/docs/ts/latest/cookbook/ngmodule-faq.jade
This PR fixes a typo in the NgModule FAQ Cookbook.
> docs(ngmodule-faq): fix typo

- public/docs/ts/latest/guide/ngmodule.jade
This PR fixes a typo in the ngmodule documentation.
> docs(ngmodule): fix typo

- public/docs/ts/latest/tutorial/toh-pt5.jade
This PR fixes a typo in the Tour of Heroes tutorial part 5.
> docs(toh-5): fix typo

- public/docs/ts/latest/guide/setup.jade
See issue raised in [QuickStart seed](https://github.com/angular/quickstart/issues/345#issuecomment-270025336).
> docs(setup): note that `npm start` fails in Bash for Windows

- public/docs/ts/latest/guide/architecture.jade
This PR updates the wording so it aligns with the actual code that is displayed under the wording.
Before:
Here's a `HeroService` that fetches heroes and returns them in a resolved Promise.
After:
Here's a `HeroService` that uses a Promise to fetch heroes.
Code:
```typescript
getHeroes() {
this.backend.getAll(Hero).then( (heroes: Hero[]) => {
this.logger.log(`Fetched ${heroes.length} heroes.`);
this.heroes.push(...heroes); // fill cache
});
return this.heroes;
}
```
The code does not return a promise so I believe the new wording is more accurate.
> docs(architecture): update wording

- public/docs/ts/latest/guide/setup.jade
This PR fixes a small typo in the Setup guide.
> docs(setup): fix typo

- public/docs/_examples/quickstart/ts/tsconfig.1.json
- public/docs/ts/latest/guide/typescript-configuration.jade
In https://angular.io/docs/ts/latest/guide/typescript-configuration.html we are showing the example tsconfig, which currently has additional properties (`typeRoots`, `compileOnSave`, `exclude`) used only by docs that do not match the one used in Quickstart.
This PR adds another file to quickstart that matches the one in https://github.com/angular/quickstart/blob/master/tsconfig.json.
/cc @Foxandxss
> fix(ts-config): fix tsconfig ref

- public/docs/ts/latest/guide/template-syntax.jade
> docs(template-syntax): interpolation only for strings #3041

- public/docs/_examples/style-guide/ts/05-14/app/shared/toast/toast.component.avoid.ts
- public/docs/_examples/style-guide/ts/05-14/app/shared/toast/toast.component.ts
- public/docs/ts/latest/guide/style-guide.jade
Copy edits to the style guide. @wardbell I toned down some of the case recommendations but can revert if you prefer.
> docs(style-guide): edit copy

- public/docs/_examples/template-syntax/ts/app/app.component.html
- public/docs/_examples/template-syntax/ts/app/app.component.ts
- public/docs/_examples/template-syntax/ts/template-syntax.css
- public/docs/ts/latest/guide/template-syntax.jade
closes #3072, whose criticism prompted these changes.
> docs(template-syntax): ngClass and ngStyle binding examples made not so horrible

- LICENSE
- README.md
- public/_includes/_footer.jade
- public/license.txt
- tools/plunker-builder/plunkerBuilder.js
> Fix update new Year

- public/docs/_examples/setup/ts/non-essential-files.txt
- public/docs/ts/latest/guide/setup-systemjs-anatomy.jade
- public/docs/ts/latest/guide/setup.jade
Need these instructions to make the tutorial more seamless. May help others too.
> docs(setup): instructs to delete non-essential files

- public/docs/_examples/router/ts/app/auth-guard.service.3.ts
In this excerpt without the checkLogin method it might indicate to users that they have to create a new class.
> Fixing router guard documentation

- public/docs/_examples/testing/ts/karma.conf.js
Add leading slash to appAssets variable
Discovered in issue https://github.com/angular/quickstart/issues/329
> docs(testing): karma.conf add slash appAssets

- public/resources/js/util.js
> chore: fix plunkers for IE11

- public/_includes/_util-fns.jade
- public/docs/ts/latest/guide/displaying-data.jade
- public/docs/ts/latest/guide/router.jade
- public/docs/ts/latest/guide/template-syntax.jade
> chore: s/falsey/falsy

- public/docs/js/latest/guide/forms.jade
- public/docs/ts/latest/guide/forms.jade
Clean-up after changes made in #2691.
Before:
After:
> docs(forms): remove unnecessary step of installing Bootstrap

- public/docs/ts/latest/guide/pipes.jade
The link to the API Reference page with the search box pre-filled with “pipe” wasn’t working anymore. This is because the API Reference search query parameter name is now `query` (it used to be `apiFilter`).
cc @kwalrath
> docs(pipes): fix link to api page w/ search box properly filled in

- public/docs/_examples/dependency-injection/ts/app/app.component.ts
- public/docs/_examples/testing/ts/app/bag/bag.ts
- public/docs/_examples/user-input/ts/app/little-tour.component.ts
Note how the `user-input/ts/app/little-tour.component.ts` click binding had no quotes whatsoever.
Cf. https://github.com/dart-lang/site-webdev/issues/285
cc @kwalrath
> examples: consistently quote event binding expressions

- public/docs/ts/latest/tutorial/toh-pt6.jade
Fix: we can’t have a markdown `<span>` ranging over multiple paragraphs; instead we use the `+ifDocsFor()` mixin.
The text of the paragraphs in question wasn't changed, as can be seen by a look at the diff ignoring whitespace.
cc @kwalrath
> docs(toh6): fix span if-docs applied to multiple paragraphs

- public/docs/_examples/security/ts/app/bypass-security.component.html
Simplify the example by just displaying the videoUrl (the string value of which is contained in `dangerousVideoUrl`). We don’t need the URL to be changeable anymore than we need the dangerousUrl to be editable.
cc @kwalrath 
Fixes #3121
> example(security): display video URL as plain text

- public/docs/ts/latest/guide/template-syntax.jade
> docs(template-syntax): fix x event binding typo

- public/docs/ts/latest/guide/router.jade
- Copyedits
- Link directly to APP_BASE_HREF API entry, no need for a callout.
- Put dragon-anchor routerLink example *before* the detailed bulleted list that analyzes it.
> docs(router): copyedits and moved code excerpt earlier

- public/docs/_examples/forms/ts/app/hero-form.component.html
- public/docs/_examples/forms/ts/app/hero-form.component.ts
- public/docs/ts/latest/guide/forms.jade
Copyedits from syncing with Dart version of page.
- Copyedits, some from Kathy (from an early revision of the forms page).
- Also, there were some missing closing code ticks (\`), and missing & extraneous `:marked`.
- Removed side note detailing `ngModel`; we're now referring reader to `ngModel` template syntax section instead.
cc @kwalrath @kapunahelewong
> docs(forms): copyedits

- public/presskit.jade
> chore(presskit): fix bullets mistake from last commit

- public/docs/ts/latest/guide/_data.json
This pull request fixes an issue with the recent deployment guide docs (pull request #3043).
The changes to the relevant [_data.json](https://github.com/angular/angular.io/commit/8a537b122535f5f614a0123c23e89a2a40885228#diff-51333d74a1356c6bef2d5c03fb6cdf68R156) referenced `production-deploy`, while the jade template was named `deployment`. This pull request also updates the alphabetic ordering for the deployment guide in the navigation sidebar to reflect the "Deployment" title.
> docs(deployment): fix broken deployment nav link and ordering

- public/docs/ts/latest/guide/deployment.jade
> docs(deployment): fix links to aot cookbook

- public/docs/_examples/hierarchical-dependency-injection/ts/app/heroes.service.ts
**WIP - Do not merge until the question below has been answered**
Current `heroes.service.ts` code in the form of 
```
new Observable<Hero[]>((subscriber: Subscriber<Hero[]>) => {...}); // (1)
```
That conforms to the type of the parameter for [`Observable` constructor](https://github.com/blesh/RxJS/blob/master/src/Observable.ts#L33).
But it appears that [`Subscriber` isn't supposed to be used in "public API"](https://github.com/blesh/RxJS/blob/master/src/Subscriber.ts#L12)
and that the conventional thing to do (which works also) is to write.
```
new Observable<Hero[]>((observer: Observer<Hero[]>) => {...}); // (2)
```
I have asked those who know which is the preferred style ... (1) or (2) ... and if (2 ... as this PR would do), why is the arg to the ctor (and to the `create` method) …
> [WIP] chore(hierarchical-dependency-injection): Subscriber -> Observer

- public/docs/_examples/dependency-injection/ts/app/heroes/hero.service.1.ts
- public/docs/_examples/dependency-injection/ts/app/providers.component.ts
- public/docs/_examples/user-input/ts/app/keyup.components.ts
- public/docs/ts/latest/guide/appmodule.jade
Fixing spacing typos in order to be consistent.
> docs: fix typos

- public/docs/ts/latest/guide/router.jade
I believe the current crisis id match the resulting path matrix notation
> Fix typo in router.jade

- public/docs/_examples/webpack/ts-snippets/webpack.config.snippets.ts
Ref. https://angular.io/docs/ts/latest/guide/webpack.html#!#loaders
> docs(webpack) missing commas in webpack snippet code

- public/docs/ts/latest/guide/router.jade
Fix error:
> The appRoutes array of routes describes how to navigate. 
Pass it to the **Router.forRoot** method in the module imports to configure the router.
To:
> The appRoutes array of routes describes how to navigate. 
Pass it to the **RouterModule.forRoot** method in the module imports to configure the router.
> docs(router): fix Router.forRoot -> RouterModule.forRoot

- harp.json
Currently, the links to Twitter on Kapunahele Wong's and Ward Bell's bios both point to https://twitter.com/undefined. These links are accessible when their bios are opened. This PR adds their proper Twitter handle, so their respective links point to the right place.
> Update 2 Twitter Handels in harp.json

- public/docs/_examples/_boilerplate/src/systemjs.config.web.build.js
- public/docs/_examples/_boilerplate/src/systemjs.config.web.js
- public/docs/_examples/quickstart/ts/plnkr.json
- public/docs/_examples/quickstart/ts/src/index.html
- public/docs/ts/latest/cli-quickstart.jade
- public/docs/ts/latest/guide/_data.json
- public/docs/ts/latest/guide/appmodule.jade
- public/docs/ts/latest/guide/architecture.jade
- public/docs/ts/latest/guide/learning-angular.jade
- public/docs/ts/latest/guide/ngmodule.jade
- public/docs/ts/latest/guide/setup.jade
We seemed to create more confusion by omitting app.module (and main) in QS than we gained in simplicity of QS. Every other example requires these files and you must learn about `app.module.ts` before you can add _anything_ to an Angular app.
This PR restores those two file to QS sample and plunker _but doesn't talk about them_ in QS, leaving _that discussion_ to the Setup guide.  Therefore, from a prose perspective, the QS is unchanged.
It also removes the `appmodule.jade` guide which ONLY talked about how to overcome the missing AppModule limitations of the QS.
@StephenFluin approved this change verbally but should give his LGTM.
@IgorMinar was involved in our original, mutual decision to omit these two files and should give his LGTM.
> chore(quickstart): restore app.module and main

- public/docs/ts/latest/guide/change-log.jade
Link in changelog was pointing to old location of i18n docs (https://angular.io/docs/ts/latest/guide/i18n.html) instead of new one (https://angular.io/docs/ts/latest/cookbook/i18n.html)
> docs - change-log - Fix i18n link in changelog

- public/docs/ts/latest/guide/attribute-directives.jade
Change `Import` to `Input` which is used in the example
```
import { Directive, ElementRef, HostListener, Input } from '@angular/core';
```
> docs ts/latest/guide/attribute-directives fix typo

- public/docs/ts/latest/cli-quickstart.jade
Updated the `cli-quickstart.jade` file to the new Angular CLI installation command:
```
npm install -g @angular/cli
```
> Update the Angular CLI installation command

- public/docs/_examples/package.json
Latest types requires Typescript 2.1 which we don't use yet.
This fixes the travis build.
> chore: lock jasmine types

- public/docs/ts/latest/guide/reactive-forms.jade
Fix broken link AbstractControl Class API
> docs(reactive-forms): fix broken link API

- public/docs/_examples/setup/ts/quickstart-specs.plnkr.json
- public/docs/_examples/testing/ts/1st-specs.plnkr.json
- public/docs/_examples/testing/ts/app-specs.plnkr.json
- public/docs/_examples/testing/ts/bag-specs.plnkr.json
- public/docs/_examples/testing/ts/banner-inline-specs.plnkr.json
- public/docs/_examples/testing/ts/banner-specs.plnkr.json
- tools/plunker-builder/builder.js
- tools/plunker-builder/indexHtmlTranslator.js
The part where we hide some `System.import` are still in place.
> chore: add systemjs.config.js back to plunkers

- public/docs/_examples/dependency-injection/ts/src/app/heroes/hero.service.provider.ts
So it wasn't a real space what we had, now we do. The interesting thing is that plunker complains but `tsc` doesn't.
Fixes #3228
> docs(dependency-injection): fix html space

- public/docs/ts/latest/guide/hierarchical-dependency-injection.jade
> docs(hierarchical-di): clarify that component injector may be a proxy

- public/docs/js/latest/quickstart.jade
There was a typo in the docs, telling that you can also use dart language from the combo box while there was no docs for dart in combo-box.
> Removed a typo.

- public/docs/ts/latest/guide/upgrade.jade
Upgrade guide has an incorrect AngularJS versions in it:
- `AngularJS.x` instead of `AngularJS 1.x`
- `AngularJS.5` instead of `AngularJS 1.5`
> docs(upgrade): Fix typos in AngularJS versions (1.5 and 1.x)

- public/docs/ts/latest/guide/dependency-injection.jade
There is a broken link in the [dependency injection guide](https://angular.io/docs/ts/latest/guide/dependency-injection.html), pointing to the [ngModule FAQ](https://angular.io/docs/ts/latest/cookbook/ngmodule-faq.html#!#q-root-component-or-module)
> docs(di): fix broken link to ngmodules faq

- public/docs/ts/latest/cookbook/dependency-injection.jade
In the referenced section the Alex component is being injected into Cathy, not Carol.
> docs(di): reference the correct component

- public/docs/ts/latest/guide/_data.json
- public/docs/ts/latest/guide/attribute-directives.jade
- public/docs/ts/latest/guide/testing.jade
These are copy related tech edits.
> docs(testing): tech edits

- public/docs/_examples/attribute-directives/ts/src/app/app.component.1.html
- public/docs/ts/latest/guide/attribute-directives.jade
Cleaning up a few copy details.
> docs(attribute-directives): copy tweaks

- public/docs/ts/latest/tutorial/toh-pt5.jade
@wardbell - I realize that all the doc example code now has a `<base href>` from the start. We're also doing that on the Dart side of the docs. But currently there is **_no_ mention of `<base href>` in the tutorial routing page**. Yet this element is so central to routing that there should at least be a brief mention of it, if only to point to the Routing guide.
This PR adds a line and a callout for `<base href>`.
It also fixes a path issue.
cc @kwalrath 
Here is the addition:
> ![screen shot 2017-02-20 at 9 57 36 am](https://cloud.githubusercontent.com/assets/4140793/23136775/1f022374-f753-11e6-937f-239271f06c8f.png)
> docs(toh-5): copyedit + add callout to importance of base href

- public/docs/ts/latest/guide/learning-angular.jade
- public/docs/ts/latest/guide/pipes.jade
- JS event --> DOM event
- The Jade block isn't used by Dart anymore.
- In `learning-angular.jade`, removed trailing whitespace.
cc @kwalrath
> doc(pipes): copyedit and removed Jade block used for Dart

- public/docs/ts/latest/guide/animations.jade
Copy edits to Animations. 
Added blue headers on the code snippets to show which files the snippets are from. This helps to clarify referencing the live example in tandem with reading the doc. Other edits include a few minor copy updates and an additional sentence to further explain the code example that followed.
Ready for review.
> docs(animations): copy edits

- public/docs/ts/latest/guide/upgrade.jade
Fixes small 'resulit' typo in component downgrade section
> docs(upgrade): Fix 'resulit' typo

- public/docs/ts/latest/guide/deployment.jade
The sample url for production server is "http://www.mysite.com/mysrc/app/"
but the identified subfolder is "my/app", which doesn't match.
> Fix base tag subfolder example

- public/docs/ts/latest/glossary.jade
Change Pipe glossary entry; it  used to suggested that one could implemented a custom pipe by annotating a function with `@Pipe`.
Cf. https://github.com/dart-lang/site-webdev/pull/415
cc @kwalrath
> docs(glossary): Pipes entry update - custom pipes are not functions

- public/docs/_examples/toh-6/ts/src/app/hero-search.component.css
Change the height of the search results so that the height of each
places the text inside directly in the middle.
Apply a styling similar to the dashboard's heroes when hovering
over a search result.
> fix(toh-6): update search result styling

- public/docs/ts/latest/guide/reactive-forms.jade
> Correct the import explanation to include Address

- public/docs/_examples/reactive-forms/ts/src/app/hero-detail-7.component.ts
this is part of the fix for #3257
> Need a reference point for the address import

- tools/example-zipper/exampleZipper.js
To beat error “SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode”.
> fix(zipper): add ‘use strict’ to exampleZipper.js

- public/docs/ts/latest/_data.json
- public/docs/ts/latest/cookbook/_data.json
- public/docs/ts/latest/guide/_data.json
- public/docs/ts/latest/tutorial/_data.json
Add periods to end of sentences in _data.json for toh, guide, and cookbook.
> docs(toh, guide, cookbook): add periods to banners

- public/docs/_examples/hierarchical-dependency-injection/ts/src/app/hero-tax-return.component.ts
- public/docs/_examples/hierarchical-dependency-injection/ts/src/app/villains-list.component.html
- public/docs/_examples/hierarchical-dependency-injection/ts/src/app/villains-list.component.ts
- public/docs/ts/latest/guide/hierarchical-dependency-injection.jade
- Move `@Input()` to be on setter rather than getter.
- Fix spelling of field `villaines` --> `villains`
- `TaxReturnComponent` --> `HeroTaxReturnComponent`
- Other misc copyedits
> docs(hier-dep-inj): fix comp name, spelling in field name, copyedits

- public/docs/_examples/attribute-directives/e2e-spec.ts
- public/docs/_examples/attribute-directives/ts/src/app/app.component.1.html
- public/docs/_examples/attribute-directives/ts/src/app/app.component.1.ts
- public/docs/_examples/attribute-directives/ts/src/app/app.component.html
- public/docs/_examples/attribute-directives/ts/src/app/app.component.ts
- public/docs/_examples/attribute-directives/ts/src/app/highlight.directive.2.ts
- public/docs/_examples/attribute-directives/ts/src/app/highlight.directive.ts
- public/docs/ts/latest/guide/attribute-directives.jade
- Prose: copyedits, including fix to misnamed directive class (`MyHighlightDirective` --> `HighlightDirective`).
- E2E update to avoid warning of multiple matching elements.
- Code: remove obsolete template region.
- Remove obsolete Jade blocks (no longer required by Dart).
- Replace Jade syntax with plain markdown.
- Remove a few unnecessary `:marked`.
> docs(attribute-directives): copyedits + fix e2e warning

- public/docs/ts/latest/guide/npm-packages.jade
Applied guidelines to copy and punctuation, smoothed out language in "Why peerDependencies?" section, cleaned up whitespace.
> docs(npm-packages): edit copy to guidelines

- public/docs/ts/latest/guide/browser-support.jade
Copy edits to apply guidelines. Changed "licence" to "license" because the styles and spelling throughout docs are standard American. Happy to revert if "licence" is the preference.
> docs(browser-support): copy edits

- public/docs/ts/latest/cli-quickstart.jade
Fix the incorrect filename used on line 98.
All other changes are whitespace cleanup.
Fixes [#3333](https://github.com/angular/angular.io/issues/3333)
> docs(cli-quickstart): fix incorrect filename for example

- public/docs/ts/latest/guide/webpack.jade
As the monospaced format is used for file names and code snippets everywhere in the documentation, in this place italic format would be better for my mind.
> Typo: Change text format from monospaced to italic

- public/docs/_examples/template-syntax/ts/src/app/app.component.html
- public/docs/_examples/template-syntax/ts/src/app/app.component.ts
- public/docs/_examples/template-syntax/ts/src/app/hero-detail.component.ts
- public/docs/_examples/template-syntax/ts/src/app/hero-form.component.html
- public/docs/_examples/template-syntax/ts/src/app/hero.ts
- public/docs/ts/latest/guide/template-syntax.jade
- onSave "no propagation" case _was_ propagating. Fixed.
- `firstName` --> `name` (a few were missed during a previous edit).
- Hercules had a _rate_ of 325, not an id; fixed so it matches figure.
- Missing closing `</div>` in form HTML
- Prose: fix json representation of Hercules (since Hero class has changed).
- Added missing AppComponent properties used in template but not declared in class; which will likely result in errors when compiled with AOT.
- Some "back to top" were not formatted properly after a figure.
- Copyedits, e.g., Angular modules such the --> such as the
- Removed Jade blocks no longer used by Dart.
> docs(template-syntax): code fixes and copyedits

- public/docs/_examples/server-communication/ts/src/app/toh/hero.service.ts
- public/docs/ts/latest/guide/server-communication.jade
Bring copy into alignment with guidelines, make the TOC reflect the shape of the doc. Changed language on line 489 to clarify for non-native English speakers.
> docs(http-client): edit copy and true TOC to doc shape

- public/docs/_examples/structural-directives/ts/src/app/app.component.html
- public/docs/_examples/structural-directives/ts/src/app/unless.directive.ts
- public/docs/ts/latest/guide/displaying-data.jade
- public/docs/ts/latest/guide/structural-directives.jade
- Fix variable name `li` --> `i`
- a --> an `UnlessDirective`
- Jade had both #ngswitch and #ngSwitch as link targets;
fixed to use same capitalization as template syntax page.
- Drop "scrap.txt" file
- Fixed broke fragment target (was missing #)
- `app/` --> `src/app/` in prose summary
- Other copy edits
> docs(structural-directives): copyedits and some tweaks to code

- public/docs/ts/latest/guide/structural-directives.jade
This is a follow-up to https://github.com/angular/angular.io/pull/3345#issuecomment-285511144.
- No changes were done to the `<ng-container>` section prose.
- At the end of the template section I linked the "write your own structural directive" text to the "unless" directive section (because now there is `<ng-container>` in between the two).
@wardbell: @kapunahelewong and I discussed the section relocation, and she agrees with the change -- other edits to this guide, if any, will come in follow-up PRs.
> docs(structural-directives): move ng-container section later in page

- tools/api-builder/angular.io-package/processors/addJadeDataDocsProcessor.js
There is a new API element in the angular/angular repo on master that ends in `Decorator` but is not a decorator. I.E. it doesn't have a `callMember`. This change accommodates that.
> fix(api-builder): tighten up check for decorator

- public/docs/_examples/server-communication/ts/src/app/toh/hero-list.component.ts
- public/docs/_examples/server-communication/ts/src/app/toh/hero.service.ts
- public/docs/ts/latest/guide/server-communication.jade
- Minor prose copyedits.
- Renamed `HeroService.addHero()` to `create()`, so as to match the ToH sample.
> docs(server-comm): copyedits

- public/docs/ts/latest/guide/architecture.jade
- public/docs/ts/latest/guide/hierarchical-dependency-injection.jade
- public/docs/ts/latest/guide/template-syntax.jade
- public/docs/ts/latest/tutorial/toh-pt5.jade
- @Foxandxss - this contains the fix to https://github.com/angular/angular.io/commit/e6741efd8f4fad20ca519d8eb99ec0c7d102577d#commitcomment-21321447 or #3362
- ToC should be named just "Contents"
- Removed unnecessary `block style-urls`.
- Dropped extra `</div>`
- Trimmed trailing whitespace in last .jade file.
> docs(arch,hier-dep,temp-syntax,toh-5): misc copyedits

- public/docs/_examples/router/e2e-spec.ts
- public/docs/_examples/template-syntax/ts/src/app/app.component.ts
- Await for alert dialog and use it in test for canceling crisis detail change.
- Tests now use async/await. It makes them easier to read.
- Remove "monkey patch" alerter comment.
> e2e(router): fix test for canceling of crisis detail change

- public/docs/ts/latest/guide/setup-systemjs-anatomy.jade
This PR contains minor copy edits to apply guidelines.
> docs(setup-anatomy): edit copy to guidelines

- public/docs/ts/latest/guide/lifecycle-hooks.jade
This PR contains:
- copy edits to guidelines
- update of TOC to reflect headings in doc
- minor edits for clarity
> docs(lifecycle-hooks): copy edits and update TOC

- public/docs/ts/latest/cookbook/form-validation.jade
This PR includes several updates:
- Edit copy to reflect guidelines standards.
- Explain `useExisting` in the Custom Validations section (at the end of doc). 
- Make the TOC reflect the shape of the doc.
> docs(forms-validation): edit copy & add explanation of useExisting

- public/docs/_examples/_boilerplate/src/systemjs-angular-loader.js
- public/docs/_examples/_boilerplate/src/systemjs.config.web.build.js
- public/docs/_examples/_boilerplate/src/systemjs.config.web.js
Seems like embedded plunkers needs a different parsing, I didn't expect that.
> chore: fix moduleId loader on plunkers

- public/docs/ts/latest/cookbook/ngmodule-faq.jade
- public/docs/ts/latest/glossary.jade
- public/docs/ts/latest/guide/dependency-injection.jade
- public/docs/ts/latest/guide/pipes.jade
- public/docs/ts/latest/guide/setup-systemjs-anatomy.jade
- public/docs/ts/latest/guide/testing.jade
- public/docs/ts/latest/guide/typescript-configuration.jade
These errors are being missed by the Jade parser
but the more stringent Pug parser treats them as
errors.
> fix(*): fix PUG syntax errors

- public/docs/ts/latest/guide/webpack.jade
- Copy edits to apply guidelines.
- Some minor edits for clarity.
- Change "entries" to "entry" when referring to entry object.
- Update table of contents to reflect body of doc.
> docs(webpack): copy edits to apply guidelines and fix entry object prose

- public/docs/_examples/toh-5/ts/src/app/hero-detail.component.1.ts
- public/docs/_examples/toh-5/ts/src/app/heroes.component.css
- public/docs/ts/latest/tutorial/toh-pt4.jade
- public/docs/ts/latest/tutorial/toh-pt5.jade
- public/docs/ts/latest/tutorial/toh-pt6.jade
This PR finishes the pass from 3077, checking TOH 4, 5, 6, and making two small changes to the example.
In routing, I added some code examples to demonstrate how to go about moving template and style content out of the @Component metadata and into separate files.
Otherwise, the changes are to make sure the merge conflicts were thoroughly sorted out from 3077 and to check against our guidelines.
Thank you!
> docs(toh): copy edit and fixes in 4, 5, 6 and example

- public/docs/ts/latest/cookbook/index.jade
Applying guidelines to Cookbook Overview. Removed sentence about icon in upper right of banner since it isn't there.
> docs(cookbook-overview): copy edits

- public/docs/_examples/toh-6/ts/src/app/hero.service.ts
To keep things uniform, i suspect this should be cast like `getHero` & `getHeroes`.
> create() should return Hero model.

- public/docs/_examples/animations/ts/src/app/app.module.ts
- public/docs/_examples/package.json
- public/docs/_examples/router/ts/src/app/app.module.ts
- public/docs/ts/latest/guide/animations.jade
- public/docs/ts/latest/guide/dependency-injection.jade
- public/docs/ts/latest/guide/router.jade
> docs: followup amends for 4.0 release

- tools/api-builder/angular.io-package/index.js
This invalid path was causing the static upgrade library to be missed from the API documentation.
Fixes https://github.com/angular/angular/issues/15524
> fix(api-builder): fix path to upgrade/static library

- public/docs/ts/latest/cookbook/ngmodule-faq.jade
Importing a module does _not_ automatically re-export the imported module's imports rather than exports.
> docs(ngmodule-faq):fix conceptual issues

- public/docs/ts/latest/glossary.jade
Dropped blocks and ifDocs mixins no longer needed for Dart or TS docs.
Since dropping blocks shifts the text,
[this PR is **best reviewed** by **_ignoring whitespace differences_**](3455/files?w=1).
> docs(glossary): copyedits and dropped unused Dart blocks

- public/docs/ts/latest/tutorial/toh-pt6.jade
- Remove statement that doesn't apply: "We recommend registering app-wide services in the root
`AppModule` *providers*" - but that isn't being done.
- Adding parentheses after method names; a few were missed in the previous pass.
- `debounce()` --> `debounceTime()`
- Remove obsolete Dart prose.
- Fix heading indentation.
- Added missing closing `</span>`.
- Fix misnamed Jade variables.
cc @kapunahelewong
> docs(toh-6): copyedits

- public/docs/ts/latest/cookbook/visual-studio-2015.jade
- public/docs/ts/latest/guide/deployment.jade
- public/docs/ts/latest/guide/testing.jade
This PR adds `src` to the instructions.
> docs(vs-cookbook, deployment): update for use in VS 2015

- public/docs/_examples/cb-dynamic-component-loader/ts/plnkr.json
- public/docs/_examples/cb-dynamic-component-loader/ts/src/app/ad-banner.component.ts
- public/docs/ts/latest/cookbook/dynamic-component-loader.jade
- Addition of explanatory prose for `loadComponent()`.
- Apply guidelines.
- Some restructuring (move makeTabs to end, add a couple of smaller snippet excerpts)
> [WIP] docs(dynamic-component-loader): add explanations for methods, add doc structure

- public/docs/ts/latest/tutorial/toh-pt6.jade
I found an error on HTTP section in tutorial documentation
> docs(aio) : update htttp.get() to http.get()

- public/docs/ts/latest/guide/reactive-forms.jade
This PR fixes a typo in the link to lifecycle-hooks.
Fixes #3462.
> docs(reactive-forms): fix typo in link

- public/docs/ts/latest/tutorial/toh-pt5.jade
This PR includes two updates: 
- Capitalize router --> Router because it's referring to the import statement and injecting it into the constructor, as opposed to the variable named `router`.
- Update screenshot of dashboard to reflect the correct title.
Fixes #3385 #3444
> docs(toh-pt5): fix capitalization of Router & update screenshot

- public/docs/_examples/forms/ts/src/app/hero-form.component.html
- public/docs/ts/latest/guide/forms.jade
- Added explanation of why `<form>` works without a template reference variable.
- Moved explanation of `ngForm` higher in the doc so that it is in the same place as `ngForm` is first used.
Fixes #3251.
> docs(forms): move template reference var higher in doc

- tools/api-builder/angular.io-package/templates/lib/githubLinks.html
the angular repo has changed its structure
> fix: github link in documentation

- public/docs/_examples/testing/ts/src/app/app.component.router.spec.ts
- public/docs/_examples/testing/ts/src/app/bag/async-helper.spec.ts
- public/docs/_examples/testing/ts/src/app/bag/bag.no-testbed.spec.ts
- public/docs/_examples/testing/ts/src/app/bag/bag.spec.ts
- public/docs/_examples/testing/ts/src/app/hero/hero-detail.component.no-testbed.spec.ts
- public/docs/_examples/testing/ts/src/app/hero/hero-detail.component.spec.ts
- public/docs/_examples/testing/ts/src/app/shared/twain.component.spec.ts
Repairs induced by Angular v.4
> docs(testing): port to Angular v4

- public/docs/ts/latest/guide/deployment.jade
**What is the current behavior? (You can also link to an open issue here)**
The following message is wrong , it has changed :
Angular 2 is running in the development mode. Call enableProdMode() to enable the production mode.
**What is the new behavior?**
Angular is running in the development mode. Call enableProdMode() to enable the production mode.
> fix(guide): Message in dev mode has changed

- public/docs/ts/latest/guide/structural-directives.jade
Guide suggests reading *ngIf* and *ngFor* sources. They are linked to github now.
> improvement(guide:structural-directives): add links to source

- public/docs/_examples/webpack/ts/config/webpack.common.js
- public/docs/_examples/webpack/ts/config/webpack.dev.js
> docs(webpack): update for v4

- public/docs/_examples/pipes/e2e-spec.ts
- public/docs/_examples/user-input/e2e-spec.ts
They seems to work again @chalin !
> chore: enable old ignored tests

- public/docs/ts/latest/guide/style-guide.jade
> docs(style-guide): a few fixes

- public/docs/_examples/_boilerplate/src/systemjs-angular-loader.js
> chore: make the moduleid loader working on safari
